'use strict';
(() => {
const { $, $$, esc, icon, state, register, createWindow, menubar, status, persist, notify, fileName, t ,locale}=XP;
register('notepad',(fileId,blank=false,externalFile=null)=>{
  const file=externalFile||state.files.find(f=>f.id===fileId&&!f.deleted);let currentId=externalFile?null:file?.id||null,name=file?.name||t("text_untitled"),wrap=false,readOnly=!!externalFile;
  const w=createWindow({title:`${name} – ${t("text_notepad")}`,icon:'notepad',app:'notepad',width:650,height:440});
  async function save(asNew=false){if(readOnly&&!asNew)return false;let nextName=name;if(!currentId||asNew){const result=await XP.prompt(t("text_save_as_1a3c9922"),t("text_name_for_the_document_it_goes_to_my_documents"),name===t("text_untitled")?t("text_note_txt"):name);if(!result)return false;nextName=fileName(result);if(!nextName)return false;if(!/\.[a-z0-9]+$/i.test(nextName))nextName+='.txt';const existing=state.files.find(f=>f.name===nextName&&f.parent==='documents'&&!f.deleted);if(existing&&existing.id!==currentId){if(!await XP.confirm(t("text_overwrite_file"),t("text_name_already_exists_do_you_want_to_replace_it",{name:nextName})))return false;currentId=existing.id;}else if(asNew||!currentId)currentId=XP.uniqueId();name=nextName;if(readOnly){readOnly=false;textarea.readOnly=false;}}
    const previous=state.files.find(f=>f.id===currentId);const ok=XP.saveFile({id:currentId,name,type:'text',parent:previous?.parent||'documents',content:textarea.value});w.setTitle(`${name} – ${t("text_notepad")}`);savedText=textarea.value;if(ok){state.draft='';persist();}updateStatus(ok?'Mentve':t("text_the_save_did_not_succeed"));return ok;
  }
  let savedText=file?file.content:(blank?'':state.draft||'');
  menubar(w,{
    [t("text_file")]:()=>[{label:t("text_new"),shortcut:'Ctrl+N',action:()=>XP.open('notepad',null,true)},{label:t("text_open_6eca8a50"),shortcut:'Ctrl+O',action:()=>XP.open('explorer','documents')},{label:t("text_save"),shortcut:'Ctrl+S',disabled:readOnly,action:()=>save()},{label:t("text_save_as"),action:()=>save(true)},null,{label:t("text_download_to_the_computer"),action:()=>XP.download(name===t("text_untitled")?t("text_note_txt"):name,textarea.value)},null,{label:t("text_exit"),action:()=>w.close()}],
    [t("text_edit")]:()=>[{label:t("text_clear_selection"),disabled:readOnly,action:()=>{textarea.setRangeText('',textarea.selectionStart,textarea.selectionEnd,'end');textarea.dispatchEvent(new Event('input'));}},{label:t("text_select_all"),shortcut:'Ctrl+A',action:()=>{textarea.focus();textarea.select();}},{label:t("text_date_and_time"),shortcut:'F5',disabled:readOnly,action:insertDate},{label:t("text_search_35795fbf"),shortcut:'Ctrl+F',action:findText}],
    [t("text_format")]:()=>[{label:t("text_word_wrap"),checked:wrap,action:()=>{wrap=!wrap;textarea.classList.toggle('wrap',wrap);}},{label:t("text_larger_text"),action:()=>textarea.style.fontSize=Math.min(30,parseInt(getComputedStyle(textarea).fontSize)+2)+'px'},{label:t("text_smaller_text"),action:()=>textarea.style.fontSize=Math.max(10,parseInt(getComputedStyle(textarea).fontSize)-2)+'px'}],
    [t("text_help")]:[{label:t("text_about_notepad"),action:()=>XP.dialog(t("text_notepad"),t("text_the_draft_is_kept_on_its_own_ctrl_s_saves_it_under_a_name_in_my_docume_da0edf37"))}]
  });
  const textarea=document.createElement('textarea');textarea.className='notepad-text';textarea.setAttribute('aria-label',t("text_notepad_text"));textarea.spellcheck=false;textarea.readOnly=readOnly;textarea.value=savedText;w.body.append(textarea);
  const bar=status(w,readOnly?t("text_read_only"):currentId?t("text_saved_document"):t("text_the_draft_is_saved_as_you_type"),t("text_ln_row_col_col",{row:1,col:1}));
  function updateStatus(msg){if(msg)$('span',bar).textContent=msg;const lines=textarea.value.slice(0,textarea.selectionStart).split('\n');$('.status-part',bar).textContent=t("text_ln_row_col_col",{row:lines.length,col:lines.at(-1).length+1});}
  function insertDate(){if(readOnly)return;textarea.setRangeText(XP.now().toLocaleString(locale()),textarea.selectionStart,textarea.selectionEnd,'end');textarea.dispatchEvent(new Event('input'));textarea.focus();}
  async function findText(){const q=await XP.prompt(t("text_search"),t("text_find_what"));if(!q)return;let index=textarea.value.toLowerCase().indexOf(q.toLowerCase(),textarea.selectionEnd);if(index<0)index=textarea.value.toLowerCase().indexOf(q.toLowerCase());if(index<0)notify(t("text_notepad"),t("text_cannot_find_text",{text:q}));else{textarea.focus();textarea.setSelectionRange(index,index+q.length);}}
  textarea.addEventListener('input',()=>{if(currentId){const previous=state.files.find(f=>f.id===currentId);if(previous&&!previous.deleted){XP.saveFile({...previous,content:textarea.value});updateStatus(t("text_saved_automatically"));}else{state.draft=textarea.value;persist();updateStatus(t("text_the_file_is_in_the_recycle_bin_the_draft_is_kept"));}}else{state.draft=textarea.value;persist();updateStatus(t("text_draft_saved_ctrl_s_saves_it_as_a_file"));}savedText=textarea.value;});
  textarea.addEventListener('keyup',()=>updateStatus());textarea.addEventListener('click',()=>updateStatus());
  w.el.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();save(e.shiftKey);}if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();findText();}if(e.ctrlKey&&e.key.toLowerCase()==='o'){e.preventDefault();XP.open('explorer','documents');}if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();XP.open('notepad',null,true);}if(e.key==='F5'){e.preventDefault();insertDate();}if(e.key==='Tab'&&e.target===textarea&&!readOnly){e.preventDefault();textarea.setRangeText('\t',textarea.selectionStart,textarea.selectionEnd,'end');textarea.dispatchEvent(new Event('input'));}});
  setTimeout(()=>textarea.focus(),0);return w;
});

register('paint',(fileId)=>{
  const file=state.files.find(f=>f.id===fileId&&!f.deleted);let name=file?.name||t("text_untitled"),currentId=file?.id||null,tool='pencil',color='#000000',size=3,drawing=false,start=null,snapshot=null,undo=[],redo=[];
  const w=createWindow({title:`${name} – Paint`,icon:'paint',app:'paint',width:780,height:565});
  function checkpoint(){undo.push(canvas.toDataURL());if(undo.length>20)undo.shift();redo=[];}
  function loadImage(src){return new Promise(resolve=>{const im=new Image();im.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0);resolve();};im.onerror=resolve;im.src=src;});}
  function saveDraft(){state.paintDraft=canvas.toDataURL('image/png');persist();}
  async function undoPaint(){if(!undo.length)return;redo.push(canvas.toDataURL());await loadImage(undo.pop());saveDraft();}
  async function redoPaint(){if(!redo.length)return;undo.push(canvas.toDataURL());await loadImage(redo.pop());saveDraft();}
  async function save(asNew=false){if(!currentId||asNew){const result=await XP.prompt(t("text_save_picture"),t("text_name_for_the_picture_it_goes_to_my_pictures"),name===t("text_untitled")?t("text_drawing_png"):name);let nextName=fileName(result);if(!nextName)return;if(!nextName.toLowerCase().endsWith('.png'))nextName+='.png';const existing=state.files.find(f=>f.name===nextName&&f.parent==='pictures'&&!f.deleted);if(existing&&existing.id!==currentId&&!await XP.confirm(t("text_overwrite"),t("text_replace_the_picture_name",{name:nextName})))return;name=nextName;currentId=existing?.id||XP.uniqueId();}const ok=XP.saveFile({id:currentId,name,type:'image',parent:'pictures',content:canvas.toDataURL('image/png')});w.setTitle(`${name} – Paint`);$('span',bar).textContent=ok?t("text_the_picture_was_saved_to_my_pictures"):t("text_the_save_did_not_succeed_9f23a644");}
  menubar(w,{[t("text_file")]:[{label:t("text_new"),action:async()=>{if(await XP.confirm(t("text_new_drawing"),t("text_start_again_with_an_empty_canvas_saved_pictures_are_kept"))){checkpoint();ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);currentId=null;name=t("text_untitled");w.setTitle(t("text_untitled_paint"));saveDraft();}}},{label:t("text_open_6eca8a50"),action:()=>XP.open('explorer','pictures')},{label:t("text_save"),shortcut:'Ctrl+S',action:()=>save()},{label:t("text_save_as"),action:()=>save(true)},{label:t("text_download_png"),action:()=>canvas.toBlob(blob=>XP.download(name===t("text_untitled")?t("text_drawing_png"):name,blob),'image/png')},null,{label:t("text_exit"),action:()=>w.close()}],[t("text_edit")]:()=>[{label:t("text_undo"),shortcut:'Ctrl+Z',disabled:!undo.length,action:undoPaint},{label:t("text_redo"),shortcut:'Ctrl+Y',disabled:!redo.length,action:redoPaint}],[t("text_image")]:[{label:t("text_clear_image"),action:()=>{checkpoint();ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);saveDraft();}},{label:t("text_invert_colours"),action:()=>{checkpoint();const d=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<d.data.length;i+=4){d.data[i]=255-d.data[i];d.data[i+1]=255-d.data[i+1];d.data[i+2]=255-d.data[i+2];}ctx.putImageData(d,0,0);saveDraft();}}],[t("text_help")]:[{label:t("text_using_paint"),action:()=>XP.dialog('Paint',t("text_pick_a_tool_and_a_colour_pencil_brush_eraser_fill_line_rectangle_ellip_4edd5093"))} ]});
  const layout=document.createElement('div');layout.className='paint-layout';const tools=[['pencil','✎',t("text_pencil")],['brush','▰',t("text_brush")],['eraser','▱',t("text_eraser")],['fill','▨',t("text_fill_with_colour")],['line','╱',t("text_line")],['rect','□',t("text_rectangle")],['ellipse','○',t("text_ellipse")],['text','A',t("text_text")],['picker','⌖',t("text_pick_colour")]];layout.innerHTML=`<aside class="paint-tools">${tools.map(([t,g,label])=>`<button class="paint-tool ${t===tool?'active':''}" data-tool="${t}" title="${label}" aria-label="${label}">${g}</button>`).join('')}<label class="paint-size">${esc(t("text_thickness"))}<input type="range" min="1" max="24" value="3" aria-label="${esc(t("text_brush_width"))}"></label></aside><div class="canvas-scroll"><canvas class="paint-canvas" width="660" height="370" aria-label="${esc(t("text_paint_canvas"))}"></canvas></div>`;w.body.append(layout);const canvas=$('canvas',layout),ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);
  const colors=['#000000','#808080','#800000','#808000','#008000','#008080','#000080','#800080','#808040','#004040','#0080ff','#004080','#8000ff','#804000','#ffffff','#c0c0c0','#ff0000','#ffff00','#00ff00','#00ffff','#0000ff','#ff00ff','#ffff80','#00ff80','#80ffff','#8080ff','#ff0080','#ff8040'];
  const palette=document.createElement('div');palette.className='paint-colors';palette.innerHTML=`<div class="paint-current"><span style="background:${color}"></span></div><div class="paint-palette">${colors.map(c=>`<button style="background:${c}" data-color="${c}" title="${c}" aria-label="${esc(t("text_colour_name",{name:c}))}"></button>`).join('')}</div><input type="color" value="#000000" aria-label="${esc(t("text_custom_colour"))}">`;w.body.append(palette);const bar=status(w,t("text_for_help_click_the_help_menu"),t("text_660_370_pixels"));
  layout.onclick=e=>{const b=e.target.closest('[data-tool]');if(b){tool=b.dataset.tool;$$('[data-tool]',layout).forEach(t=>t.classList.toggle('active',t===b));$('span',bar).textContent=b.title;}};
  function setColor(c){color=c;$('.paint-current span',palette).style.background=c;$('input[type=color]',palette).value=c;}
  palette.onclick=e=>{const b=e.target.closest('[data-color]');if(b)setColor(b.dataset.color);};$('input[type=color]',palette).oninput=e=>setColor(e.target.value);$('input[type=range]',layout).oninput=e=>size=Number(e.target.value);
  const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width-1,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height-1,(e.clientY-r.top)*canvas.height/r.height))};};
  function flood(x,y){const img=ctx.getImageData(0,0,canvas.width,canvas.height),d=img.data;const at=(Math.floor(y)*canvas.width+Math.floor(x))*4;const original=[...d.slice(at,at+4)],replacement=[parseInt(color.slice(1,3),16),parseInt(color.slice(3,5),16),parseInt(color.slice(5,7),16),255];if(original.every((c,i)=>c===replacement[i]))return;const stack=[Math.floor(y)*canvas.width+Math.floor(x)];const matches=p=>original.every((c,i)=>d[p*4+i]===c);while(stack.length){const p=stack.pop();if(!matches(p))continue;for(let k=0;k<4;k++)d[p*4+k]=replacement[k];const x=p%canvas.width,y=Math.floor(p/canvas.width);if(x>0)stack.push(p-1);if(x<canvas.width-1)stack.push(p+1);if(y>0)stack.push(p-canvas.width);if(y<canvas.height-1)stack.push(p+canvas.width);}ctx.putImageData(img,0,0);}
  canvas.onpointerdown=async e=>{if(e.button!==0)return;e.preventDefault();const p=point(e);if(tool==='picker'){const d=ctx.getImageData(p.x,p.y,1,1).data;setColor('#'+[...d.slice(0,3)].map(v=>v.toString(16).padStart(2,'0')).join(''));return;}if(tool==='text'){const text=await XP.prompt(t("text_text"),t("text_text_to_place_on_the_picture"));if(text){checkpoint();ctx.fillStyle=color;ctx.font=`${Math.max(14,size*4)}px Arial`;ctx.fillText(text,p.x,p.y);saveDraft();}return;}checkpoint();if(tool==='fill'){flood(p.x,p.y);saveDraft();return;}drawing=true;start=p;snapshot=ctx.getImageData(0,0,canvas.width,canvas.height);canvas.setPointerCapture(e.pointerId);ctx.strokeStyle=tool==='eraser'?'#fff':color;ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=tool==='brush'?size*3:tool==='eraser'?size*5:size;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(p.x,p.y);if(['pencil','brush','eraser'].includes(tool)){ctx.lineTo(p.x+.01,p.y);ctx.stroke();}};
  canvas.onpointermove=e=>{const p=point(e);$('.status-part',bar).textContent=t("text_x_y_pixels",{x:Math.round(p.x),y:Math.round(p.y)});if(!drawing)return;if(['pencil','brush','eraser'].includes(tool)){ctx.lineTo(p.x,p.y);ctx.stroke();}else{ctx.putImageData(snapshot,0,0);ctx.beginPath();if(tool==='line'){ctx.moveTo(start.x,start.y);ctx.lineTo(p.x,p.y);}if(tool==='rect')ctx.rect(start.x,start.y,p.x-start.x,p.y-start.y);if(tool==='ellipse')ctx.ellipse((start.x+p.x)/2,(start.y+p.y)/2,Math.abs(p.x-start.x)/2,Math.abs(p.y-start.y)/2,0,0,Math.PI*2);ctx.stroke();}};
  const stop=()=>{if(!drawing)return;drawing=false;saveDraft();};canvas.onpointerup=stop;canvas.onpointercancel=stop;canvas.onlostpointercapture=stop;
  w.el.addEventListener('keydown',e=>{if(e.ctrlKey&&['s','z','y'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='s')save();if(e.key.toLowerCase()==='z')undoPaint();if(e.key.toLowerCase()==='y')redoPaint();}});
  if(file?.content)loadImage(file.content);else if(state.paintDraft)loadImage(state.paintDraft);return w;
});

register('calculator',()=>{
 if(XP.singleton('calculator'))return;const w=createWindow({title:t("text_calculator"),icon:'calculator',app:'calculator',width:310,height:337,fixed:true});let value='0',stored=null,op=null,fresh=true,memory=0,lastOp=null,lastValue=null;
 menubar(w,{[t("text_edit")]:[{label:t("text_result_to_notepad"),action:()=>{state.draft=value;XP.open('notepad');}}],[t("text_view")]:[{label:t("text_normal"),checked:true,action:()=>{}}],[t("text_help")]:[{label:t("text_usage"),action:()=>XP.dialog(t("text_calculator"),t("text_use_the_buttons_or_the_keyboard_enter_result_escape_clear_backspace_delete"))} ]});
 const body=document.createElement('div');body.className='calc';body.innerHTML=`<div class="calc-display" role="status" aria-label="${esc(t("text_result"))}">0</div><div class="calc-top"><button class="xp-button" data-key="back">Backspace</button><button class="xp-button" data-key="CE">CE</button><button class="xp-button" data-key="C">C</button></div><div class="calc-grid"></div><div class="calc-foot">${esc(t("text_the_keyboard_works_too"))}</div>`;w.body.append(body);
 const keys=['MC','7','8','9','/','MR','4','5','6','*','MS','1','2','3','-','M+','0','±','.','+','√','%','1/x','=','C'];$('.calc-grid',body).innerHTML=keys.map(k=>`<button class="xp-button calc-key ${['/','*','-','+','='].includes(k)?'op':''}" data-key="${k}">${k==='*'?'×':k==='/'?'÷':k}</button>`).join('');
 const calculate=(a,b,o)=>o==='+'?a+b:o==='-'?a-b:o==='*'?a*b:o==='/'?(b===0?NaN:a/b):b;
 function show(){if(!Number.isFinite(Number(value)))value=t("text_error");$('.calc-display',body).textContent=value===t("text_error")?value:!fresh?value:String(Number(Number(value).toPrecision(12)));$('.calc-foot',body).textContent=memory?t("text_m_in_memory")+memory:t("text_the_keyboard_works_too");}
 function key(k){if(/^\d$/.test(k)){value=fresh||value==='0'||value===t("text_error")?k:value.length<15?value+k:value;fresh=false;}else if(k==='.'){if(fresh||value===t("text_error")){value='0';fresh=false;}if(!value.includes('.'))value+='.';}else if(k==='C'){value='0';stored=null;op=null;lastOp=null;lastValue=null;fresh=true;}else if(k==='CE'){value='0';fresh=true;}else if(k==='back'){value=fresh?'0':value.slice(0,-1)||'0';}else if(['+','-','*','/'].includes(k)){if(op&&!fresh)value=String(calculate(stored,Number(value),op));stored=Number(value);op=k;fresh=true;}else if(k==='='){if(op){lastOp=op;lastValue=Number(value);value=String(calculate(stored,lastValue,op));op=null;}else if(lastOp)value=String(calculate(Number(value),lastValue,lastOp));fresh=true;}else if(k==='±')value=String(-Number(value));else if(k==='√'){value=String(Math.sqrt(Number(value)));fresh=true;}else if(k==='1/x'){value=String(Number(value)===0?NaN:1/Number(value));fresh=true;}else if(k==='%')value=String(stored!==null?stored*Number(value)/100:Number(value)/100);else if(k==='MC')memory=0;else if(k==='MR'){value=String(memory);fresh=true;}else if(k==='MS')memory=Number(value)||0;else if(k==='M+')memory+=Number(value)||0;show();}
 body.onclick=e=>{const b=e.target.closest('[data-key]');if(b)key(b.dataset.key);};const listener=e=>{if(XP.active!==w.id||XP.modal||e.ctrlKey||e.altKey)return;const k=e.key==='Enter'?'=':e.key==='Escape'?'C':e.key==='Backspace'?'back':e.key===','?'.':e.key;if(/^[0-9.+\-*/=%]$/.test(k)||['C','back'].includes(k)){e.preventDefault();key(k);}};document.addEventListener('keydown',listener);w.cleanup.push(()=>document.removeEventListener('keydown',listener));return w;
});

register('cmd',()=>{
 const w=createWindow({title:t("text_c_windows_system32_cmd_exe"),icon:'cmd',app:'cmd',width:690,height:390});const body=document.createElement('div');body.className='cmd-body';body.innerHTML=`<pre>Microsoft Windows XP [Version 5.1.2600]\n(C) Copyright 1985-2001 Microsoft Corp.\n\n</pre><form class="cmd-line"><span></span><input type="text" aria-label="${esc(t("text_command"))}" autocomplete="off" spellcheck="false"></form>`;w.body.append(body);const output=$('pre',body),input=$('input',body);let current='profile',history=[],index=0;
 const virtual={
  c:{name:'C:',parent:null,children:[['WINDOWS','windows'],['Program Files','program-files'],['Documents and Settings','documents-settings']]},
  windows:{name:'WINDOWS',parent:'c',children:[['system32','system32'],['Fonts','fonts'],['explorer.exe',null,'file'],['win.ini',null,'file']]},
  system32:{name:'system32',parent:'windows',children:[['drivers','drivers'],['cmd.exe',null,'file'],['notepad.exe',null,'file'],['mspaint.exe',null,'file']]},drivers:{name:'drivers',parent:'system32',children:[]},fonts:{name:'Fonts',parent:'windows',children:[]},
  'program-files':{name:'Program Files',parent:'c',children:[['Internet Explorer','program-ie'],['Windows Media Player','program-wmp'],['Windows NT','program-nt']]},
  'program-ie':{name:'Internet Explorer',parent:'program-files',children:[['iexplore.exe',null,'file']]},'program-wmp':{name:'Windows Media Player',parent:'program-files',children:[['wmplayer.exe',null,'file']]},'program-nt':{name:'Windows NT',parent:'program-files',children:[]},
  'documents-settings':{name:'Documents and Settings',parent:'c',children:[[state.user,'profile'],['All Users','all-users'],['Default User','default-user']]},
  profile:{name:state.user,parent:'documents-settings',children:[[t("text_desktop"),'desktop'],[t("text_my_documents"),'documents'],['Favorites','favorites']]},
  'all-users':{name:'All Users',parent:'documents-settings',children:[[t("text_desktop"),null],['Shared Documents',null]]},'default-user':{name:'Default User',parent:'documents-settings',children:[]},favorites:{name:'Favorites',parent:'profile',children:[]},
  desktop:{name:t("text_desktop"),parent:'profile'},documents:{name:t("text_my_documents"),parent:'profile'},pictures:{name:t("text_my_pictures"),parent:'documents'},music:{name:t("text_my_music"),parent:'documents'}
 };
 const node=id=>id.startsWith('file:')?state.files.find(file=>file.id===id.slice(5)&&!file.deleted):virtual[id];
 const parent=id=>{if(!id.startsWith('file:'))return virtual[id]?.parent;const owner=node(id)?.parent||'documents';return virtual[owner]?owner:`file:${owner}`;};
 const pathOf=id=>{if(id==='c')return 'C:\\';const names=[];for(let cursor=id;cursor&&cursor!=='c';cursor=parent(cursor))names.unshift(node(cursor)?.name||'');return 'C:\\'+names.join('\\');};
 const entries=id=>{
  const fixed=(virtual[id]?.children||[]).map(([name,target,type])=>({name,id:target,type:type||'folder'}));
  if(id==='documents')fixed.push({name:t("text_my_pictures"),id:'pictures',type:'folder'},{name:t("text_my_music"),id:'music',type:'folder'});
  const storage=id.startsWith('file:')?id.slice(5):['desktop','documents','pictures','music'].includes(id)?id:null;
  return [...fixed,...(storage?state.files.filter(file=>!file.deleted&&file.parent===storage).map(file=>({name:file.name,id:`file:${file.id}`,type:file.type,file})):[])];
 };
 const clean=value=>String(value||'').trim().replace(/^"|"$/g,'');
 const findChild=(id,name)=>entries(id).find(entry=>entry.id&&entry.name.toLocaleLowerCase(locale())===clean(name).toLocaleLowerCase(locale()));
 function resolvePath(value){
  let wanted=clean(value).replace(/\//g,'\\'),cursor=current;if(!wanted)return cursor;
  if(/^c:/i.test(wanted)){cursor='c';wanted=wanted.slice(2).replace(/^\\+/,'');}else if(wanted.startsWith('\\')){cursor='c';wanted=wanted.replace(/^\\+/,'');}
  for(const part of wanted.split('\\').filter(Boolean)){if(part==='.')continue;if(part==='..'){cursor=parent(cursor)||cursor;continue;}const found=findChild(cursor,part);if(!found||found.type!=='folder')return null;cursor=found.id;}
  return cursor;
 }
 const writableParent=()=>current.startsWith('file:')?current.slice(5):['desktop','documents','pictures','music'].includes(current)?current:null;
 const write=text=>output.textContent+=text+'\n';const help=t("text_cmd_help_vfs");
 $('form',body).onsubmit=async e=>{e.preventDefault();const command=input.value.trim(),shownPath=pathOf(current);write(shownPath+'>'+command);input.value='';if(command){history.push(command);index=history.length;}const match=command.match(/^(\S+)(?:\s+([\s\S]*))?$/)||[],raw=match[1]||'',cmd=raw.toLowerCase(),arg=match[2]||'';let result='';
  const redirect=cmd==='echo'&&arg.match(/^([\s\S]*?)\s*>\s*(.+)$/);
  if(redirect){const storage=writableParent(),name=fileName(clean(redirect[2]));if(!storage||!name)result=t("text_access_is_denied");else{const existing=state.files.find(file=>!file.deleted&&file.parent===storage&&file.name.toLowerCase()===name.toLowerCase());XP.saveFile({id:existing?.id||XP.uniqueId(),name,type:'text',parent:storage,content:redirect[1]});}}
  else if(cmd==='help')result=help;else if(cmd==='cls')output.textContent='';else if(cmd==='ver')result='Microsoft Windows XP [Version 5.1.2600]';else if(cmd==='date')result=XP.now().toLocaleDateString(locale());else if(cmd==='time')result=XP.now().toLocaleTimeString(locale());else if(cmd==='whoami')result=state.user;else if(cmd==='echo')result=arg;
  else if(cmd==='dir'){const target=arg?resolvePath(arg):current;if(!target)result=t("text_the_system_cannot_find_the_path_specified");else{const list=entries(target);result=t("text_volume_in_drive_c_is_windows_xp")+` Directory of ${pathOf(target)}\n\n`+list.map(entry=>`${new Date(entry.file?.modified||Date.now()).toLocaleDateString(locale())}  ${entry.type==='folder'?'<DIR>       ':String(new Blob([entry.file?.content||'']).size).padStart(12)}  ${entry.name}`).join('\n')+`\n               ${list.length} File(s)`;}}
  else if(cmd==='type'){const found=findChild(current,arg);result=found?.file?.type==='text'?found.file.content:t("text_the_system_cannot_find_the_text_file_specified");}
  else if(cmd==='cd'||cmd==='chdir'){if(!arg)result=pathOf(current);else{const target=resolvePath(arg);if(target)current=target;else result=t("text_the_system_cannot_find_the_path_specified");}}
  else if(cmd==='mkdir'||cmd==='md'){const storage=writableParent(),name=fileName(clean(arg));if(!storage||!name)result=t("text_access_is_denied");else if(entries(current).some(entry=>entry.name.toLowerCase()===name.toLowerCase()))result=t("text_a_subdirectory_or_file_already_exists");else XP.saveFile({id:XP.uniqueId(),name,type:'folder',parent:storage});}
  else if(cmd==='del'||cmd==='erase'){const found=findChild(current,arg);if(!found?.file||found.file.type==='folder')result=t("text_the_system_cannot_find_the_text_file_specified");else XP.deleteFile(found.file.id);}
  else if(cmd==='start'){const map={notepad:'notepad',mspaint:'paint',calc:'calculator',iexplore:'ie',msimn:'outlook',taskmgr:'taskmgr',compmgmt:'compmgmt',winmine:'mines',sol:'solitaire',pinball:'pinball',freecell:'freecell',spider:'spider',mshearts:'hearts',explorer:'explorer',control:'control',wscui:'security',wmplayer:'player'};if(map[arg.toLowerCase()])XP.open(map[arg.toLowerCase()]);else result=t("text_the_program_was_not_found_for_example_start_notepad");}
  else if(cmd==='color'){const colors={'0a':'#55ff55','07':'#c0c0c0','0f':'#ffffff','0b':'#55ffff'};if(colors[arg.toLowerCase()])body.style.color=colors[arg.toLowerCase()];else result=t("text_colours_to_choose_from_0a_07_0f_0b");}else if(cmd==='exit'){w.close();return;}else if(cmd==='ping'){const host=arg||'localhost';result=t("text_pinging_host_127_0_0_1_with_32_bytes_of_data",{host})+Array(4).fill(t("text_reply_from_127_0_0_1_bytes_32_time_1ms_ttl_128")).join('\n')+t("text_ping_statistics_for_127_0_0_1_packets_sent_4_received_4_lost_0_0_loss_21df0791");}else if(cmd)result=t("text_command_is_not_recognized_as_an_internal_or_external_command_type_help_b6e9dd48",{command:raw});if(result)write(result+'\n');$('.cmd-line span',body).textContent=pathOf(current)+'>';body.scrollTop=body.scrollHeight;};
 $('.cmd-line span',body).textContent=pathOf(current)+'>';
 input.onkeydown=e=>{if(e.key==='ArrowUp'){e.preventDefault();input.value=history[Math.max(0,--index)]||'';}if(e.key==='ArrowDown'){e.preventDefault();input.value=history[Math.min(history.length,++index)]||'';}};body.onclick=()=>input.focus();setTimeout(()=>input.focus(),0);return w;
});
})();
