'use strict';
(() => {
const { $, $$, esc, icon, state, register, createWindow, menubar, status, persist, notify, fileName }=XP;
register('notepad',(fileId,blank=false)=>{
  const file=state.files.find(f=>f.id===fileId&&!f.deleted);let currentId=file?.id||null,name=file?.name||'Névtelen',wrap=false;
  const w=createWindow({title:`${name} – Jegyzettömb`,icon:'notepad',app:'notepad',width:650,height:440});
  async function save(asNew=false){let nextName=name;if(!currentId||asNew){const result=await XP.prompt('Mentés másként','A dokumentum neve (a Dokumentumok mappába kerül):',name==='Névtelen'?'Jegyzet.txt':name);if(!result)return false;nextName=fileName(result);if(!nextName)return false;if(!/\.[a-z0-9]+$/i.test(nextName))nextName+='.txt';const existing=state.files.find(f=>f.name===nextName&&f.parent==='documents'&&!f.deleted);if(existing&&existing.id!==currentId){if(!await XP.confirm('Fájl felülírása',`A(z) „${nextName}” már létezik. Felülírod?`))return false;currentId=existing.id;}else if(asNew||!currentId)currentId=XP.uniqueId();name=nextName;}
    const previous=state.files.find(f=>f.id===currentId);const ok=XP.saveFile({id:currentId,name,type:'text',parent:previous?.parent||'documents',content:textarea.value});w.setTitle(`${name} – Jegyzettömb`);savedText=textarea.value;if(ok){state.draft='';persist();}updateStatus(ok?'Mentve':'A mentés nem sikerült');return ok;
  }
  let savedText=file?file.content:(blank?'':state.draft||'');
  menubar(w,{
    'Fájl':[{label:'Új',shortcut:'Ctrl+N',action:()=>XP.open('notepad',null,true)},{label:'Megnyitás…',shortcut:'Ctrl+O',action:()=>XP.open('explorer','documents')},{label:'Mentés',shortcut:'Ctrl+S',action:()=>save()},{label:'Mentés másként…',action:()=>save(true)},null,{label:'Letöltés a számítógépre',action:()=>XP.download(name==='Névtelen'?'Jegyzet.txt':name,textarea.value)},null,{label:'Kilépés',action:()=>w.close()}],
    'Szerkesztés':[{label:'Kijelölés törlése',action:()=>{textarea.setRangeText('',textarea.selectionStart,textarea.selectionEnd,'end');textarea.dispatchEvent(new Event('input'));}},{label:'Az összes kijelölése',shortcut:'Ctrl+A',action:()=>{textarea.focus();textarea.select();}},{label:'Dátum és idő',shortcut:'F5',action:insertDate},{label:'Keresés…',shortcut:'Ctrl+F',action:findText}],
    'Formátum':()=>[{label:'Automatikus sortörés',checked:wrap,action:()=>{wrap=!wrap;textarea.classList.toggle('wrap',wrap);}},{label:'Betűméret növelése',action:()=>textarea.style.fontSize=Math.min(30,parseInt(getComputedStyle(textarea).fontSize)+2)+'px'},{label:'Betűméret csökkentése',action:()=>textarea.style.fontSize=Math.max(10,parseInt(getComputedStyle(textarea).fontSize)-2)+'px'}],
    'Súgó':[{label:'A Jegyzettömb névjegye',action:()=>XP.dialog('Jegyzettömb','A piszkozat automatikusan megmarad.\nA Ctrl+S billentyűvel névvel is elmentheted a Dokumentumok közé. A mentett dokumentum további módosításai automatikusan mentődnek.')}]
  });
  const textarea=document.createElement('textarea');textarea.className='notepad-text';textarea.setAttribute('aria-label','Jegyzettömb szöveg');textarea.spellcheck=false;textarea.value=savedText;w.body.append(textarea);
  const bar=status(w,currentId?'Mentett dokumentum':'A piszkozat automatikusan mentődik','1. sor, 1. oszlop');
  function updateStatus(msg){if(msg)$('span',bar).textContent=msg;const lines=textarea.value.slice(0,textarea.selectionStart).split('\n');$('.status-part',bar).textContent=`${lines.length}. sor, ${lines.at(-1).length+1}. oszlop`;}
  function insertDate(){textarea.setRangeText(new Date().toLocaleString('hu-HU'),textarea.selectionStart,textarea.selectionEnd,'end');textarea.dispatchEvent(new Event('input'));textarea.focus();}
  async function findText(){const q=await XP.prompt('Keresés','Keresendő szöveg:');if(!q)return;let index=textarea.value.toLowerCase().indexOf(q.toLowerCase(),textarea.selectionEnd);if(index<0)index=textarea.value.toLowerCase().indexOf(q.toLowerCase());if(index<0)notify('Jegyzettömb',`„${q}” nem található.`);else{textarea.focus();textarea.setSelectionRange(index,index+q.length);}}
  textarea.addEventListener('input',()=>{if(currentId){const previous=state.files.find(f=>f.id===currentId);if(previous&&!previous.deleted){XP.saveFile({...previous,content:textarea.value});updateStatus('Automatikusan mentve');}else{state.draft=textarea.value;persist();updateStatus('A fájl a Lomtárban van. A piszkozat megmarad.');}}else{state.draft=textarea.value;persist();updateStatus('Piszkozat mentve · Ctrl+S: mentés fájlként');}savedText=textarea.value;});
  textarea.addEventListener('keyup',()=>updateStatus());textarea.addEventListener('click',()=>updateStatus());
  w.el.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();save(e.shiftKey);}if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();findText();}if(e.ctrlKey&&e.key.toLowerCase()==='o'){e.preventDefault();XP.open('explorer','documents');}if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();XP.open('notepad',null,true);}if(e.key==='F5'){e.preventDefault();insertDate();}if(e.key==='Tab'&&e.target===textarea){e.preventDefault();textarea.setRangeText('\t',textarea.selectionStart,textarea.selectionEnd,'end');textarea.dispatchEvent(new Event('input'));}});
  setTimeout(()=>textarea.focus(),0);return w;
});

register('paint',(fileId)=>{
  const file=state.files.find(f=>f.id===fileId&&!f.deleted);let name=file?.name||'Névtelen',currentId=file?.id||null,tool='pencil',color='#000000',size=3,drawing=false,start=null,snapshot=null,undo=[],redo=[];
  const w=createWindow({title:`${name} – Paint`,icon:'paint',app:'paint',width:780,height:565});
  function checkpoint(){undo.push(canvas.toDataURL());if(undo.length>20)undo.shift();redo=[];}
  function loadImage(src){return new Promise(resolve=>{const im=new Image();im.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0);resolve();};im.onerror=resolve;im.src=src;});}
  function saveDraft(){state.paintDraft=canvas.toDataURL('image/png');persist();}
  async function undoPaint(){if(!undo.length)return;redo.push(canvas.toDataURL());await loadImage(undo.pop());saveDraft();}
  async function redoPaint(){if(!redo.length)return;undo.push(canvas.toDataURL());await loadImage(redo.pop());saveDraft();}
  async function save(asNew=false){if(!currentId||asNew){const result=await XP.prompt('Kép mentése','A kép neve (a Képek mappába kerül):',name==='Névtelen'?'Rajz.png':name);let nextName=fileName(result);if(!nextName)return;if(!nextName.toLowerCase().endsWith('.png'))nextName+='.png';const existing=state.files.find(f=>f.name===nextName&&f.parent==='pictures'&&!f.deleted);if(existing&&existing.id!==currentId&&!await XP.confirm('Felülírás',`Felülírod ezt a képet: „${nextName}”?`))return;name=nextName;currentId=existing?.id||XP.uniqueId();}const ok=XP.saveFile({id:currentId,name,type:'image',parent:'pictures',content:canvas.toDataURL('image/png')});w.setTitle(`${name} – Paint`);$('span',bar).textContent=ok?'A kép mentve a Képek mappába.':'A mentés nem sikerült.';}
  menubar(w,{'Fájl':[{label:'Új',action:async()=>{if(await XP.confirm('Új rajz','Üres vászonnal kezded újra? Az elmentett képek megmaradnak.')){checkpoint();ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);currentId=null;name='Névtelen';w.setTitle('Névtelen – Paint');saveDraft();}}},{label:'Megnyitás…',action:()=>XP.open('explorer','pictures')},{label:'Mentés',shortcut:'Ctrl+S',action:()=>save()},{label:'Mentés másként…',action:()=>save(true)},{label:'PNG letöltése',action:()=>canvas.toBlob(blob=>XP.download(name==='Névtelen'?'Rajz.png':name,blob),'image/png')},null,{label:'Kilépés',action:()=>w.close()}],'Szerkesztés':()=>[{label:'Visszavonás',shortcut:'Ctrl+Z',disabled:!undo.length,action:undoPaint},{label:'Ismét',shortcut:'Ctrl+Y',disabled:!redo.length,action:redoPaint}],'Kép':[{label:'Kép törlése',action:()=>{checkpoint();ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);saveDraft();}},{label:'Színek megfordítása',action:()=>{checkpoint();const d=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<d.data.length;i+=4){d.data[i]=255-d.data[i];d.data[i+1]=255-d.data[i+1];d.data[i+2]=255-d.data[i+2];}ctx.putImageData(d,0,0);saveDraft();}}],'Súgó':[{label:'A Paint használata',action:()=>XP.dialog('Paint','Válassz egy eszközt és egy színt.\nA ceruza, ecset, radír, kitöltés, vonal, téglalap, ellipszis és szöveg használható. A rajz piszkozata automatikusan megmarad.')} ]});
  const layout=document.createElement('div');layout.className='paint-layout';const tools=[['pencil','✎','Ceruza'],['brush','▰','Ecset'],['eraser','▱','Radír'],['fill','▨','Kitöltés'],['line','╱','Vonal'],['rect','□','Téglalap'],['ellipse','○','Ellipszis'],['text','A','Szöveg'],['picker','⌖','Pipetta']];layout.innerHTML=`<aside class="paint-tools">${tools.map(([t,g,label])=>`<button class="paint-tool ${t===tool?'active':''}" data-tool="${t}" title="${label}" aria-label="${label}">${g}</button>`).join('')}<label class="paint-size">Vastagság<input type="range" min="1" max="24" value="3" aria-label="Ecsetvastagság"></label></aside><div class="canvas-scroll"><canvas class="paint-canvas" width="660" height="370" aria-label="Paint rajzvászon"></canvas></div>`;w.body.append(layout);const canvas=$('canvas',layout),ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);
  const colors=['#000000','#808080','#800000','#808000','#008000','#008080','#000080','#800080','#808040','#004040','#0080ff','#004080','#8000ff','#804000','#ffffff','#c0c0c0','#ff0000','#ffff00','#00ff00','#00ffff','#0000ff','#ff00ff','#ffff80','#00ff80','#80ffff','#8080ff','#ff0080','#ff8040'];
  const palette=document.createElement('div');palette.className='paint-colors';palette.innerHTML=`<div class="paint-current"><span style="background:${color}"></span></div><div class="paint-palette">${colors.map(c=>`<button style="background:${c}" data-color="${c}" title="${c}" aria-label="Szín ${c}"></button>`).join('')}</div><input type="color" value="#000000" aria-label="Egyéni szín">`;w.body.append(palette);const bar=status(w,'Súgóért kattints a Súgó menüre.','660 × 370 képpont');
  layout.onclick=e=>{const b=e.target.closest('[data-tool]');if(b){tool=b.dataset.tool;$$('[data-tool]',layout).forEach(t=>t.classList.toggle('active',t===b));$('span',bar).textContent=b.title;}};
  function setColor(c){color=c;$('.paint-current span',palette).style.background=c;$('input[type=color]',palette).value=c;}
  palette.onclick=e=>{const b=e.target.closest('[data-color]');if(b)setColor(b.dataset.color);};$('input[type=color]',palette).oninput=e=>setColor(e.target.value);$('input[type=range]',layout).oninput=e=>size=Number(e.target.value);
  const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width-1,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height-1,(e.clientY-r.top)*canvas.height/r.height))};};
  function flood(x,y){const img=ctx.getImageData(0,0,canvas.width,canvas.height),d=img.data;const at=(Math.floor(y)*canvas.width+Math.floor(x))*4;const original=[...d.slice(at,at+4)],replacement=[parseInt(color.slice(1,3),16),parseInt(color.slice(3,5),16),parseInt(color.slice(5,7),16),255];if(original.every((c,i)=>c===replacement[i]))return;const stack=[Math.floor(y)*canvas.width+Math.floor(x)];const matches=p=>original.every((c,i)=>d[p*4+i]===c);while(stack.length){const p=stack.pop();if(!matches(p))continue;for(let k=0;k<4;k++)d[p*4+k]=replacement[k];const x=p%canvas.width,y=Math.floor(p/canvas.width);if(x>0)stack.push(p-1);if(x<canvas.width-1)stack.push(p+1);if(y>0)stack.push(p-canvas.width);if(y<canvas.height-1)stack.push(p+canvas.width);}ctx.putImageData(img,0,0);}
  canvas.onpointerdown=async e=>{if(e.button!==0)return;e.preventDefault();const p=point(e);if(tool==='picker'){const d=ctx.getImageData(p.x,p.y,1,1).data;setColor('#'+[...d.slice(0,3)].map(v=>v.toString(16).padStart(2,'0')).join(''));return;}if(tool==='text'){const text=await XP.prompt('Szöveg','A képre írandó szöveg:');if(text){checkpoint();ctx.fillStyle=color;ctx.font=`${Math.max(14,size*4)}px Arial`;ctx.fillText(text,p.x,p.y);saveDraft();}return;}checkpoint();if(tool==='fill'){flood(p.x,p.y);saveDraft();return;}drawing=true;start=p;snapshot=ctx.getImageData(0,0,canvas.width,canvas.height);canvas.setPointerCapture(e.pointerId);ctx.strokeStyle=tool==='eraser'?'#fff':color;ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=tool==='brush'?size*3:tool==='eraser'?size*5:size;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(p.x,p.y);if(['pencil','brush','eraser'].includes(tool)){ctx.lineTo(p.x+.01,p.y);ctx.stroke();}};
  canvas.onpointermove=e=>{const p=point(e);$('.status-part',bar).textContent=`${Math.round(p.x)}, ${Math.round(p.y)} képpont`;if(!drawing)return;if(['pencil','brush','eraser'].includes(tool)){ctx.lineTo(p.x,p.y);ctx.stroke();}else{ctx.putImageData(snapshot,0,0);ctx.beginPath();if(tool==='line'){ctx.moveTo(start.x,start.y);ctx.lineTo(p.x,p.y);}if(tool==='rect')ctx.rect(start.x,start.y,p.x-start.x,p.y-start.y);if(tool==='ellipse')ctx.ellipse((start.x+p.x)/2,(start.y+p.y)/2,Math.abs(p.x-start.x)/2,Math.abs(p.y-start.y)/2,0,0,Math.PI*2);ctx.stroke();}};
  const stop=()=>{if(!drawing)return;drawing=false;saveDraft();};canvas.onpointerup=stop;canvas.onpointercancel=stop;canvas.onlostpointercapture=stop;
  w.el.addEventListener('keydown',e=>{if(e.ctrlKey&&['s','z','y'].includes(e.key.toLowerCase())){e.preventDefault();if(e.key.toLowerCase()==='s')save();if(e.key.toLowerCase()==='z')undoPaint();if(e.key.toLowerCase()==='y')redoPaint();}});
  if(file?.content)loadImage(file.content);else if(state.paintDraft)loadImage(state.paintDraft);return w;
});

register('calculator',()=>{
 if(XP.singleton('calculator'))return;const w=createWindow({title:'Számológép',icon:'calculator',app:'calculator',width:310,height:337,fixed:true});let value='0',stored=null,op=null,fresh=true,memory=0,lastOp=null,lastValue=null;
 menubar(w,{'Szerkesztés':[{label:'Eredmény a Jegyzettömbbe',action:()=>{state.draft=value;XP.open('notepad');}}],'Nézet':[{label:'Normál',checked:true,action:()=>{}}],'Súgó':[{label:'Használat',action:()=>XP.dialog('Számológép','Használd a számgombokat vagy a billentyűzetet.\nEnter: eredmény, Escape: törlés, Backspace: visszatörlés.')} ]});
 const body=document.createElement('div');body.className='calc';body.innerHTML='<div class="calc-display" role="status" aria-label="Eredmény">0</div><div class="calc-top"><button class="xp-button" data-key="back">Backspace</button><button class="xp-button" data-key="CE">CE</button><button class="xp-button" data-key="C">C</button></div><div class="calc-grid"></div><div class="calc-foot">A billentyűzettel is használható.</div>';w.body.append(body);
 const keys=['MC','7','8','9','/','MR','4','5','6','*','MS','1','2','3','-','M+','0','±','.','+','√','%','1/x','=','C'];$('.calc-grid',body).innerHTML=keys.map(k=>`<button class="xp-button calc-key ${['/','*','-','+','='].includes(k)?'op':''}" data-key="${k}">${k==='*'?'×':k==='/'?'÷':k}</button>`).join('');
 const calculate=(a,b,o)=>o==='+'?a+b:o==='-'?a-b:o==='*'?a*b:o==='/'?(b===0?NaN:a/b):b;
 function show(){if(!Number.isFinite(Number(value)))value='Hiba';$('.calc-display',body).textContent=value==='Hiba'?value:!fresh?value:String(Number(Number(value).toPrecision(12)));$('.calc-foot',body).textContent=memory?'M · Memóriában: '+memory:'A billentyűzettel is használható.';}
 function key(k){if(/^\d$/.test(k)){value=fresh||value==='0'||value==='Hiba'?k:value.length<15?value+k:value;fresh=false;}else if(k==='.'){if(fresh||value==='Hiba'){value='0';fresh=false;}if(!value.includes('.'))value+='.';}else if(k==='C'){value='0';stored=null;op=null;lastOp=null;lastValue=null;fresh=true;}else if(k==='CE'){value='0';fresh=true;}else if(k==='back'){value=fresh?'0':value.slice(0,-1)||'0';}else if(['+','-','*','/'].includes(k)){if(op&&!fresh)value=String(calculate(stored,Number(value),op));stored=Number(value);op=k;fresh=true;}else if(k==='='){if(op){lastOp=op;lastValue=Number(value);value=String(calculate(stored,lastValue,op));op=null;}else if(lastOp)value=String(calculate(Number(value),lastValue,lastOp));fresh=true;}else if(k==='±')value=String(-Number(value));else if(k==='√'){value=String(Math.sqrt(Number(value)));fresh=true;}else if(k==='1/x'){value=String(Number(value)===0?NaN:1/Number(value));fresh=true;}else if(k==='%')value=String(stored!==null?stored*Number(value)/100:Number(value)/100);else if(k==='MC')memory=0;else if(k==='MR'){value=String(memory);fresh=true;}else if(k==='MS')memory=Number(value)||0;else if(k==='M+')memory+=Number(value)||0;show();}
 body.onclick=e=>{const b=e.target.closest('[data-key]');if(b)key(b.dataset.key);};const listener=e=>{if(XP.active!==w.id||XP.modal||e.ctrlKey||e.altKey)return;const k=e.key==='Enter'?'=':e.key==='Escape'?'C':e.key==='Backspace'?'back':e.key===','?'.':e.key;if(/^[0-9.+\-*/=%]$/.test(k)||['C','back'].includes(k)){e.preventDefault();key(k);}};document.addEventListener('keydown',listener);w.cleanup.push(()=>document.removeEventListener('keydown',listener));return w;
});

register('cmd',()=>{
 const w=createWindow({title:'C:\\WINDOWS\\system32\\cmd.exe',icon:'cmd',app:'cmd',width:690,height:390});const body=document.createElement('div');body.className='cmd-body';body.innerHTML=`<pre>Microsoft Windows XP [Version 5.1.2600]\n(C) Copyright 1985-2001 Microsoft Corp.\n\n</pre><form class="cmd-line"><span>C:\\Documents and Settings\\${esc(state.user)}&gt;</span><input type="text" aria-label="Parancs" autocomplete="off" spellcheck="false"></form>`;w.body.append(body);const output=$('pre',body),input=$('input',body);let path=`C:\\Documents and Settings\\${state.user}`,history=[],index=0;
 const write=text=>output.textContent+=text+'\n';const help='Elérhető parancsok:\n  help      Ez a súgó\n  dir       Saját dokumentumok listázása\n  cd        Könyvtár váltása (.., \\, Dokumentumok)\n  type NÉV  Szöveges fájl megjelenítése\n  echo      Szöveg kiírása\n  cls       Képernyő törlése\n  ver       Verzió\n  date      Dátum\n  time      Idő\n  whoami    Felhasználó\n  start     Program indítása (notepad, mspaint, calc, iexplore)\n  color     Szövegszín (0a, 07, 0f)\n  exit      Bezárás';
 $('form',body).onsubmit=e=>{e.preventDefault();const command=input.value.trim();write(path+'>'+command);input.value='';if(command){history.push(command);index=history.length;}const [raw,...args]=command.split(/\s+/),cmd=raw.toLowerCase(),arg=args.join(' ');let result='';if(cmd==='help')result=help;else if(cmd==='cls')output.textContent='';else if(cmd==='ver')result='Microsoft Windows XP [Version 5.1.2600]';else if(cmd==='date')result=new Date().toLocaleDateString('hu-HU');else if(cmd==='time')result=new Date().toLocaleTimeString('hu-HU');else if(cmd==='whoami')result=state.user;else if(cmd==='echo')result=arg;else if(cmd==='dir')result=' A C: meghajtó kötete: WINDOWS_XP\n\n'+state.files.filter(f=>!f.deleted).map(f=>`${new Date(f.modified).toLocaleDateString('hu-HU')}  ${f.type==='folder'?'<DIR>   ':String(new Blob([f.content||'']).size).padStart(8)}  ${f.name}`).join('\n');else if(cmd==='type'){const f=state.files.find(f=>!f.deleted&&f.name.toLowerCase()===arg.replaceAll('"','').toLowerCase());result=f?.type==='text'?f.content:'A rendszer nem találja a megadott szöveges fájlt.';}else if(cmd==='cd'){if(arg==='..')path=path.slice(0,path.lastIndexOf('\\'))||'C:\\';else if(arg==='\\'||arg.toLowerCase()==='c:\\')path='C:\\';else if(arg.toLowerCase()==='dokumentumok'||arg.toLowerCase()==='my documents')path=`C:\\Documents and Settings\\${state.user}\\Dokumentumok`;else if(!arg)result=path;else result='A rendszer nem találja a megadott elérési utat.';}else if(cmd==='start'){const map={notepad:'notepad',mspaint:'paint',calc:'calculator',iexplore:'ie',winmine:'mines',sol:'solitaire',pinball:'pinball',explorer:'explorer',control:'control',wmplayer:'player'};if(map[arg.toLowerCase()])XP.open(map[arg.toLowerCase()]);else result='A program nem található. Példa: start notepad';}else if(cmd==='color'){const colors={'0a':'#55ff55','07':'#c0c0c0','0f':'#ffffff','0b':'#55ffff'};if(colors[arg.toLowerCase()])body.style.color=colors[arg.toLowerCase()];else result='Választható színek: 0a, 07, 0f, 0b';}else if(cmd==='exit'){w.close();return;}else if(cmd==='ping')result='Helyi szimuláció: nincs külső hálózati kapcsolat.';else if(cmd)result=`'${raw}' nem ismerhető fel belső vagy külső parancsként.\nA parancsok listájához írd be: help`;if(result)write(result+'\n');$('.cmd-line span',body).textContent=path+'>';body.scrollTop=body.scrollHeight;};
 input.onkeydown=e=>{if(e.key==='ArrowUp'){e.preventDefault();input.value=history[Math.max(0,--index)]||'';}if(e.key==='ArrowDown'){e.preventDefault();input.value=history[Math.min(history.length,++index)]||'';}};body.onclick=()=>input.focus();setTimeout(()=>input.focus(),0);return w;
});
})();
