'use strict';
(() => {
const {$,$$,esc,icon,state,register,createWindow,menubar,status,persist,notify,t}=XP;
register('mines',()=>{
 if(XP.singleton('mines'))return;const w=createWindow({title:t('Aknakereső'),icon:'mines',app:'mines',width:275,height:375,fixed:true});
 let cols=9,rows=9,total=10,board=[],started=false,finished=false,elapsed=0,flagMode=false,startTime=0,difficulty=t('Kezdő');
 const around=i=>{const x=i%cols,y=Math.floor(i/cols),list=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(nx>=0&&nx<cols&&ny>=0&&ny<rows)list.push(ny*cols+nx);}return list;};
 menubar(w,{[t('Játék')]:()=>[{label:t('Új játék'),shortcut:'F2',action:()=>reset()},{label:t('Kezdő · 9 × 9'),checked:cols===9,action:()=>reset(9,9,10,t('Kezdő'))},{label:t('Haladó · 16 × 16'),checked:cols===16,action:()=>reset(16,16,40,t('Haladó'))},null,{label:t('Legjobb eredmények…'),action:()=>XP.dialog(t('Aknakereső – Eredmények'),state.mineBest?Object.entries(state.mineBest).map(([level,sec])=>`${level}: ${sec} másodperc`).join('\n'):t('Még nincs megnyert játék. Hajrá!'))},null,{label:t('Kilépés'),action:()=>w.close()}],[t('Súgó')]:[{label:t('Játékszabályok'),action:()=>XP.dialog(t('Aknakereső'),t('Nyisd fel az összes aknamentes mezőt.\nA számok a szomszédos aknák számát mutatják.\nJobb kattintás: zászló.\nDupla kattintás a számon: szomszédok felnyitása, ha elég zászló áll mellette.\nAz első kattintás mindig biztonságos.'))} ]});
 const body=document.createElement('div');body.className='mines-body';body.innerHTML=`<div class="mines-scoreboard"><div class="led-number mine-count">010</div><button class="mine-face" title="${esc(t('Új játék'))}" aria-label="${esc(t('Új játék'))}"><img src="assets/mines/smile.png" alt=""></button><div class="led-number mine-time">000</div></div><div class="mine-grid" aria-label="${esc(t('Aknakereső játéktábla'))}"></div><div class="mines-help">${esc(t('Bal kattintás: felfedés · Jobb kattintás: zászló'))}<br><button class="xp-button" data-flag-mode style="margin-top:5px;min-height:21px">${esc(t('Zászló mód: ki'))}</button></div>`;w.body.append(body);const grid=$('.mine-grid',body);
 function reset(c=cols,r=rows,n=total,level=difficulty){cols=c;rows=r;total=n;difficulty=level;board=Array.from({length:cols*rows},()=>({mine:false,open:false,flag:false,count:0}));started=false;finished=false;elapsed=0;const height=rows*25+205,width=cols*25+38+(height>innerHeight-36?17:0);w.el.style.width=Math.min(innerWidth-6,width)+'px';w.el.style.height=Math.min(innerHeight-36,height)+'px';w.el.style.top=Math.max(0,Math.min(parseInt(w.el.style.top),innerHeight-30-Math.min(innerHeight-36,height)))+'px';w.el.style.left=Math.max(0,Math.min(parseInt(w.el.style.left),innerWidth-Math.min(innerWidth-6,width)))+'px';body.style.overflow='auto';grid.style.setProperty('--cols',cols);$('.mine-face img',body).src='assets/mines/smile.png';render();}
 function seed(first){const safe=new Set([first,...around(first)]);const pool=board.map((_,i)=>i).filter(i=>!safe.has(i));for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}pool.slice(0,total).forEach(i=>board[i].mine=true);board.forEach((b,i)=>b.count=around(i).filter(j=>board[j].mine).length);started=true;startTime=Date.now();}
 function reveal(i){if(finished||board[i].flag||board[i].open)return;if(!started)seed(i);if(board[i].mine){board[i].open=true;board[i].exploded=true;finished=true;$('.mine-face img',body).src='assets/mines/dead.png';XP.sound('error');render();return;}const queue=[i];while(queue.length){const k=queue.pop(),b=board[k];if(b.open||b.flag||b.mine)continue;b.open=true;if(b.count===0)queue.push(...around(k).filter(j=>!board[j].open));}if(board.filter(b=>b.open).length===board.length-total){finished=true;board.filter(b=>b.mine).forEach(b=>b.flag=true);$('.mine-face img',body).src='assets/mines/win.png';const best=state.mineBest||{};if(best[difficulty]===undefined||elapsed<best[difficulty]){best[difficulty]=elapsed;state.mineBest=best;persist();}notify(t('Gratulálunk!'),`Megnyerted a játékot ${elapsed} másodperc alatt!`);XP.sound('notify');}render();}
 function flag(i){if(finished||board[i].open)return;board[i].flag=!board[i].flag;render();}
 function chord(i){if(!board[i].open||finished)return;const neighbours=around(i);if(neighbours.filter(j=>board[j].flag).length===board[i].count)for(const j of neighbours){if(finished)break;reveal(j);}}
 function render(){const colors=['','#0000ff','#008000','#ff0000','#000080','#800000','#008080','#000','#808080'];grid.innerHTML=board.map((b,i)=>`<button class="mine-cell ${b.open?'open':''} ${b.exploded?'exploded':''}" data-cell="${i}" aria-label="${Math.floor(i/cols)+1}. sor ${i%cols+1}. oszlop, ${b.flag?t('zászló'):b.open?b.mine?'akna':b.count+t(' szomszédos akna'):t('fedett mező')}" style="color:${colors[b.count]||'#000'}">${b.flag?`<img src="assets/mines/flag.png" alt="${esc(t('Zászló'))}">`:b.mine&&(b.open||finished)?'<img src="assets/mines/mine-ceil.png" alt="Akna">':b.open&&b.count?b.count:''}</button>`).join('');$('.mine-count',body).textContent=String(total-board.filter(b=>b.flag).length).padStart(3,'0');$('.mine-time',body).textContent=String(Math.min(999,elapsed)).padStart(3,'0');}
 grid.onclick=e=>{const b=e.target.closest('[data-cell]');if(b)(flagMode?flag:reveal)(Number(b.dataset.cell));};grid.oncontextmenu=e=>{e.preventDefault();const b=e.target.closest('[data-cell]');if(b)flag(Number(b.dataset.cell));};grid.ondblclick=e=>{const b=e.target.closest('[data-cell]');if(b)chord(Number(b.dataset.cell));};$('.mine-face',body).onclick=()=>reset();$('[data-flag-mode]',body).onclick=e=>{flagMode=!flagMode;e.target.textContent=t('Zászló mód: ')+(flagMode?'be':'ki');e.target.classList.toggle('primary',flagMode);};
 const timer=setInterval(()=>{if(started&&!finished){elapsed=Math.floor((Date.now()-startTime)/1000);$('.mine-time',body).textContent=String(Math.min(999,elapsed)).padStart(3,'0');}},250);w.cleanup.push(()=>clearInterval(timer));w.el.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();reset();}});reset();return w;
});

register('solitaire',()=>{
 if(XP.singleton('solitaire'))return;const w=createWindow({title:t('Pasziánsz'),icon:'solitaire',app:'solitaire',width:595,height:565});let stock=[],waste=[],columns=[],foundations=[[],[],[],[]],selected=null,score=0,moves=0,snapshots=[];
 const suits=['♠','♥','♣','♦'];const red=c=>c.suit===1||c.suit===3;const label=c=>([null,'A','2','3','4','5','6','7','8','9','10','J','Q','K'][c.rank])+suits[c.suit];
 function saveMove(){snapshots.push(JSON.stringify({stock,waste,columns,foundations,score,moves}));if(snapshots.length>100)snapshots.shift();}
 function undo(){if(!snapshots.length)return;const prev=JSON.parse(snapshots.pop());({stock,waste,columns,foundations,score,moves}=prev);selected=null;render();}
 menubar(w,{[t('Játék')]:()=>[{label:t('Új osztás'),shortcut:'F2',action:reset},{label:t('Visszavonás'),shortcut:'Ctrl+Z',disabled:!snapshots.length,action:undo},{label:t('Automatikus gyűjtés'),action:autoCollect},null,{label:t('Kilépés'),action:()=>w.close()}],[t('Súgó')]:[{label:t('Játékszabályok'),action:()=>XP.dialog(t('Pasziánsz'),t('Kattints egy lapra, majd a céloszlopra.\nAz oszlopokban csökkenő sorrendben, váltakozó színnel rakhatod a lapokat. Üres oszlopba király kerülhet.\nA felső négy helyen színenként ásztól királyig gyűjtsd a lapokat. Dupla kattintás: gyűjtőhelyre rakás.\nA bal felső pakliból egyesével húzhatsz. Ha elfogy, kattints az üres helyére az újraosztáshoz.'))} ]});
 const body=document.createElement('div');body.className='solitaire-body';w.body.append(body);const bar=status(w,t('Pontszám: 0'),t('Lépések: 0'));
 function reset(){let deck=Array.from({length:52},(_,i)=>({rank:i%13+1,suit:Math.floor(i/13),face:false}));for(let i=51;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}columns=Array.from({length:7},(_,c)=>{const col=deck.splice(0,c+1);col.at(-1).face=true;return col;});stock=deck;waste=[];foundations=[[],[],[],[]];selected=null;score=0;moves=0;snapshots=[];render();}
 function card(c,attrs='',active=false,index=0){return `<button class="playing-card ${c.face?red(c)?'red':'':'back'} ${active?'selected':''}" ${attrs} style="--card-i:${index}" aria-label="${c.face?label(c):'Fedett lap'}">${c.face?`${[null,'A','2','3','4','5','6','7','8','9','10','J','Q','K'][c.rank]}<span class="suit">${suits[c.suit]}</span><span class="big-suit">${suits[c.suit]}</span>`:''}</button>`;}
 function render(){body.innerHTML=`<div class="card-top">${stock.length?card({face:false},'data-stock'): `<button class="card-slot" data-stock aria-label="${esc(t('Pakli újraosztása'))}">↻</button>`}${waste.length?card({...waste.at(-1),face:true},'data-waste',selected?.kind==='waste'):'<div class="card-slot"></div>'}<span class="spacer"></span>${foundations.map((pile,i)=>pile.length?card(pile.at(-1),`data-foundation="${i}"`,selected?.kind==='foundation'&&selected.pile===i):`<button class="card-slot foundation" data-foundation="${i}" aria-label="${suits[i]} gyűjtőhely">${suits[i]}</button>`).join('')}</div><div class="solitaire-columns">${columns.map((col,c)=>`<div class="card-column" data-column="${c}"><button class="card-slot" data-empty="${c}" aria-label="${c+1}. oszlop"></button>${col.map((cardData,i)=>card(cardData,`data-col="${c}" data-index="${i}"`,selected?.kind==='column'&&selected.col===c&&i>=selected.index,i)).join('')}</div>`).join('')}</div><div class="solitaire-help">${esc(t('Kattints egy lapra, majd a helyére. Dupla kattintás: gyűjtés.'))}</div>`;$('span',bar).textContent=t('Pontszám: ')+score;$('.status-part',bar).textContent=t('Lépések: ')+moves;const max=Math.max(...columns.map(c=>c.length));$$('.card-column',body).forEach(el=>el.style.minHeight=Math.max(240,max*22+65)+'px');}
 function source(){if(!selected)return[];if(selected.kind==='waste')return waste.length?[waste.at(-1)]:[];if(selected.kind==='foundation')return foundations[selected.pile].length?[foundations[selected.pile].at(-1)]:[];return columns[selected.col].slice(selected.index);}
 function detach(){if(selected.kind==='waste')waste.pop();else if(selected.kind==='foundation')foundations[selected.pile].pop();else{columns[selected.col].splice(selected.index);const top=columns[selected.col].at(-1);if(top&&!top.face){top.face=true;score+=5;}}}
 function moveTo(kind,target){const cards=source();if(!cards.length)return false;const first=cards[0];if(kind==='foundation'){const pile=foundations[target];if(cards.length!==1||first.suit!==target||first.rank!==pile.length+1)return false;if(selected.kind==='foundation'&&selected.pile===target)return false;saveMove();detach();first.face=true;pile.push(first);score+=10;}else{if(selected.kind==='column'&&selected.col===target)return false;const pile=columns[target],last=pile.at(-1);if(last?last.rank!==first.rank+1||red(last)===red(first):first.rank!==13)return false;for(let i=1;i<cards.length;i++)if(!cards[i].face||cards[i-1].rank!==cards[i].rank+1||red(cards[i-1])===red(cards[i]))return false;saveMove();detach();pile.push(...cards);score+=5;}moves++;selected=null;render();if(foundations.every(p=>p.length===13)){XP.sound('notify');notify(t('Gratulálunk!'),t('Sikerült kiraknod a pasziánszt! Pontszám: ')+score);}return true;}
 function autoCollect(){let changed=true;while(changed){changed=false;const sources=[...(waste.length?[{kind:'waste'}]:[]),...columns.map((c,i)=>c.length?{kind:'column',col:i,index:c.length-1}:null).filter(Boolean)];for(const s of sources){selected=s;const c=source()[0];if(c&&moveTo('foundation',c.suit)){changed=true;break;}}}selected=null;render();}
 body.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-stock')){saveMove();if(stock.length){const c=stock.pop();c.face=true;waste.push(c);}else{stock=waste.reverse().map(c=>({...c,face:false}));waste=[];score=Math.max(0,score-20);}moves++;selected=null;render();return;}if(b.hasAttribute('data-waste')){selected=selected?.kind==='waste'?null:{kind:'waste'};render();return;}if(b.hasAttribute('data-foundation')){const target=Number(b.dataset.foundation);if(selected&&moveTo('foundation',target))return;selected=foundations[target].length?{kind:'foundation',pile:target}:null;render();return;}const col=Number(b.dataset.col??b.dataset.empty);if(Number.isNaN(col))return;if(selected&&moveTo('column',col))return;const idx=Number(b.dataset.index);if(Number.isFinite(idx)&&columns[col][idx]?.face){selected=selected?.kind==='column'&&selected.col===col&&selected.index===idx?null:{kind:'column',col,index:idx};}else selected=null;render();};
 // A double click is handled by a short second-click check because cards are redrawn after selection.
 let lastClick={key:'',time:0};body.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-col],[data-waste]');if(!b)return;const key=b.hasAttribute('data-waste')?'waste':`${b.dataset.col}:${b.dataset.index}`;const now=Date.now();if(key===lastClick.key&&now-lastClick.time<350){const s=b.hasAttribute('data-waste')?{kind:'waste'}:{kind:'column',col:Number(b.dataset.col),index:Number(b.dataset.index)};selected=s;const c=source()[0];if(c&&source().length===1){e.preventDefault();moveTo('foundation',c.suit);}}lastClick={key,time:now};});
 w.el.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();reset();}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo();}});reset();return w;
});
})();
