'use strict';
(() => {
const {$,$$,esc,icon,state,register,createWindow,menubar,status,persist,notify,t}=XP;
const mineRules={
 presets:Object.freeze({beginner:{cols:9,rows:9,total:10},intermediate:{cols:16,rows:16,total:40},expert:{cols:30,rows:16,total:99}}),
 custom(width,height,mines){const cols=Math.max(9,Math.min(30,Math.floor(Number(width))||9)),rows=Math.max(9,Math.min(24,Math.floor(Number(height))||9));return {cols,rows,total:Math.max(10,Math.min((cols-1)*(rows-1),Math.floor(Number(mines))||10))};}
};
XP.mineRules=mineRules;
register('mines',()=>{
 if(XP.singleton('mines'))return;const w=createWindow({title:t("text_minesweeper"),icon:'mines',app:'mines',className:'mines-window',width:220,height:300,minWidth:210,minHeight:275,fixed:true});
 let mode=['beginner','intermediate','expert','custom'].includes(state.mineMode)?state.mineMode:'beginner';
 let custom=mineRules.custom(state.mineCustom?.cols,state.mineCustom?.rows,state.mineCustom?.total),initial=mode==='custom'?custom:mineRules.presets[mode];
 let {cols,rows,total}=initial,board=[],started=false,finished=false,elapsed=0,flagMode=false,startTime=0,marks=state.mineMarks!==false;
 const levelName=id=>t(({beginner:'text_beginner',intermediate:'text_intermediate',expert:'text_expert',custom:'text_custom'})[id]);
 const led=value=>value<0?'-'+String(Math.min(99,-value)).padStart(2,'0'):String(Math.min(999,value)).padStart(3,'0');
 const around=i=>{const x=i%cols,y=Math.floor(i/cols),list=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(nx>=0&&nx<cols&&ny>=0&&ny<rows)list.push(ny*cols+nx);}return list;};
 menubar(w,{[t("text_game")]:()=>[{label:t("text_new_game"),shortcut:'F2',action:()=>reset()},{label:t("text_beginner_9_9"),checked:mode==='beginner',action:()=>resetPreset('beginner')},{label:t("text_intermediate_16_16"),checked:mode==='intermediate',action:()=>resetPreset('intermediate')},{label:t("text_expert_30_16"),checked:mode==='expert',action:()=>resetPreset('expert')},{label:t("text_custom_ellipsis"),checked:mode==='custom',action:customGame},null,{label:t("text_marks_question"),checked:marks,action:()=>{marks=!marks;state.mineMarks=marks;if(!marks)board.forEach(cell=>cell.question=false);persist();render();}},{label:t("text_best_times"),action:()=>{const best=state.mineBest||{},lines=['beginner','intermediate','expert'].filter(id=>best[id]!==undefined).map(id=>t("text_level_seconds_seconds",{level:levelName(id),seconds:best[id]}));XP.dialog(t("text_minesweeper_best_times"),lines.join('\n')||t("text_no_game_won_yet_go_on"));}},null,{label:t("text_exit"),action:()=>w.close()}],[t("text_help")]:[{label:t("text_game_rules"),action:()=>XP.dialog(t("text_minesweeper"),t("text_uncover_every_square_that_has_no_mine_the_numbers_say_how_many_mines_s_defba89d"))} ]});
 const body=document.createElement('div');body.className='mines-body';body.innerHTML=`<div class="mines-scoreboard"><div class="led-number mine-count">010</div><button class="mine-face" title="${esc(t("text_new_game"))}" aria-label="${esc(t("text_new_game"))}"><img src="assets/mines/smile.png" alt=""></button><div class="led-number mine-time">000</div></div><div class="mine-grid" aria-label="${esc(t("text_minesweeper_board"))}"></div><div class="mines-help">${esc(t("text_left_click_uncover_right_click_flag"))}<br><button class="xp-button" data-flag-mode style="margin-top:5px;min-height:21px">${esc(t("text_flag_mode_off"))}</button></div>`;w.body.append(body);const grid=$('.mine-grid',body);
 function resetPreset(id){const p=mineRules.presets[id];reset(p.cols,p.rows,p.total,id);}
 function fitBoard(){
  const area=$('#desktop'),maxWidth=area.clientWidth-6,maxHeight=area.clientHeight-6;body.style.overflow='hidden';
  // Text and borders add a few browser-dependent pixels. Grow from the nominal
  // board size until the body really fits instead of showing empty scrollbars.
  for(let pass=0;pass<2;pass++){
   const growWidth=Math.max(0,body.scrollWidth-body.clientWidth),growHeight=Math.max(0,body.scrollHeight-body.clientHeight);
   if(!growWidth&&!growHeight)break;
   const rect=w.el.getBoundingClientRect();
   w.el.style.width=Math.min(maxWidth,rect.width+growWidth)+'px';w.el.style.height=Math.min(maxHeight,rect.height+growHeight)+'px';
  }
  body.style.overflow=body.scrollWidth>body.clientWidth||body.scrollHeight>body.clientHeight?'auto':'hidden';
  const rect=w.el.getBoundingClientRect();
  w.el.style.top=Math.max(0,Math.min(parseInt(w.el.style.top)||0,area.clientHeight-rect.height))+'px';
  w.el.style.left=Math.max(0,Math.min(parseInt(w.el.style.left)||0,area.clientWidth-rect.width))+'px';
 }
 function reset(c=cols,r=rows,n=total,nextMode=mode){({cols,rows,total}=nextMode==='custom'?mineRules.custom(c,r,n):{cols:c,rows:r,total:n});mode=nextMode;if(mode==='custom')custom={cols,rows,total};state.mineMode=mode;state.mineCustom=custom;state.mineMarks=marks;persist();board=Array.from({length:cols*rows},()=>({mine:false,open:false,flag:false,question:false,count:0}));started=false;finished=false;elapsed=0;const area=$('#desktop'),height=rows*20+125,width=cols*20+36;w.el.style.width=Math.min(area.clientWidth-6,width)+'px';w.el.style.height=Math.min(area.clientHeight-6,height)+'px';body.style.overflow='hidden';grid.style.setProperty('--cols',cols);$('.mine-face img',body).src='assets/mines/smile.png';render();fitBoard();}
 function customGame(){const d=createWindow({title:t("text_custom_field"),icon:'mines',width:330,height:245,fixed:true,modal:true});d.body.innerHTML=`<form class="mines-custom-form"><div class="dialog-body"><div><label>${esc(t("text_height_9_24"))}<input name="height" type="number" min="9" max="24" value="${custom.rows}"></label><label>${esc(t("text_width_9_30"))}<input name="width" type="number" min="9" max="30" value="${custom.cols}"></label><label>${esc(t("text_mines"))}<input name="mines" type="number" min="10" value="${custom.total}"></label><small data-limit></small></div></div><div class="button-row"><button class="xp-button primary" type="submit">OK</button><button class="xp-button" type="button" data-cancel>${esc(t("text_cancel"))}</button></div></form>`;const form=$('form',d.body),refresh=()=>{const next=mineRules.custom(form.elements.width.value,form.elements.height.value,form.elements.mines.value);form.elements.mines.max=(next.cols-1)*(next.rows-1);$('[data-limit]',form).textContent=t("text_custom_mine_limits",{min:10,max:(next.cols-1)*(next.rows-1)});};form.oninput=refresh;form.onsubmit=e=>{e.preventDefault();const next=mineRules.custom(form.elements.width.value,form.elements.height.value,form.elements.mines.value);d.close();reset(next.cols,next.rows,next.total,'custom');};$('[data-cancel]',form).onclick=()=>d.close();d.el.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();d.close();}});refresh();XP.fitDialog(d);}
 function seed(first){const pool=board.map((_,i)=>i).filter(i=>i!==first);for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}pool.slice(0,total).forEach(i=>board[i].mine=true);board.forEach((b,i)=>b.count=around(i).filter(j=>board[j].mine).length);started=true;startTime=Date.now();}
 function reveal(i){if(finished||board[i].flag||board[i].open)return;if(!started)seed(i);board[i].question=false;if(board[i].mine){board[i].open=true;board[i].exploded=true;finished=true;$('.mine-face img',body).src='assets/mines/dead.png';XP.sound('error');render();return;}const queue=[i];while(queue.length){const k=queue.pop(),b=board[k];if(b.open||b.flag||b.mine)continue;b.open=true;b.question=false;if(b.count===0)queue.push(...around(k).filter(j=>!board[j].open));}if(board.filter(b=>b.open).length===board.length-total){finished=true;board.filter(b=>b.mine).forEach(b=>{b.flag=true;b.question=false;});$('.mine-face img',body).src='assets/mines/win.png';if(mode!=='custom'){const best=state.mineBest||{};if(best[mode]===undefined||elapsed<best[mode]){best[mode]=elapsed;state.mineBest=best;persist();}}notify(t("text_congratulations"),t("text_you_won_the_game_in_seconds_seconds",{seconds:elapsed}));XP.sound('notify');}render();}
 function flag(i){if(finished||board[i].open)return;const cell=board[i];if(!cell.flag&&!cell.question)cell.flag=true;else if(cell.flag&&marks){cell.flag=false;cell.question=true;}else{cell.flag=false;cell.question=false;}render();}
 function chord(i){if(!board[i].open||finished)return;const neighbours=around(i);if(neighbours.filter(j=>board[j].flag).length===board[i].count)for(const j of neighbours){if(finished)break;reveal(j);}}
 function render(){const colors=['','#0000ff','#008000','#ff0000','#000080','#800000','#008080','#000','#808080'];grid.innerHTML=board.map((b,i)=>`<button class="mine-cell ${b.open?'open':''} ${b.exploded?'exploded':''} ${finished&&b.flag&&!b.mine?'wrong':''}" data-cell="${i}" aria-label="${esc(t("text_row_row_column_col_state",{row:Math.floor(i/cols)+1,col:i%cols+1,state:b.flag?t("text_flag"):b.question?t("text_question_mark"):b.open?b.mine?t("text_mine"):t("text_count_neighbouring_mines",{count:b.count}):t("text_covered_square")}))}" style="color:${colors[b.count]||'#000'}">${b.flag?`<img src="assets/mines/flag.png" alt="${esc(t("text_flag_819aae5e"))}">`:b.question?'?':b.mine&&(b.open||finished)?`<img src="assets/mines/mine-ceil.png" alt="${esc(t("text_mine_887c975b"))}">`:b.open&&b.count?b.count:''}</button>`).join('');$('.mine-count',body).textContent=led(total-board.filter(b=>b.flag).length);$('.mine-time',body).textContent=led(elapsed);}
 grid.onclick=e=>{const b=e.target.closest('[data-cell]');if(b)(flagMode?flag:reveal)(Number(b.dataset.cell));};grid.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();const b=e.target.closest('[data-cell]');if(b)flag(Number(b.dataset.cell));};grid.ondblclick=e=>{const b=e.target.closest('[data-cell]');if(b)chord(Number(b.dataset.cell));};$('.mine-face',body).onclick=()=>reset();$('[data-flag-mode]',body).onclick=e=>{flagMode=!flagMode;e.target.textContent=t(flagMode?"text_flag_mode_on":"text_flag_mode_off");e.target.classList.toggle('primary',flagMode);};
 grid.onpointerdown=e=>{const cell=e.target.closest('[data-cell]');if(!cell)return;const i=Number(cell.dataset.cell);if(board[i].open&&(((e.buttons&3)===3)||(e.button===0&&e.shiftKey))){e.preventDefault();chord(i);}};
 const timer=setInterval(()=>{if(started&&!finished){elapsed=Math.floor((Date.now()-startTime)/1000);$('.mine-time',body).textContent=led(elapsed);}},250);w.cleanup.push(()=>clearInterval(timer));w.el.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();reset();}});reset();return w;
});

register('solitaire',()=>{
 if(XP.singleton('solitaire'))return;const w=createWindow({title:t("text_solitaire"),icon:'solitaire',app:'solitaire',width:595,height:565});let stock=[],waste=[],columns=[],foundations=[[],[],[],[]],selected=null,score=0,moves=0,passes=0,snapshots=[],drawCount=state.solitaireDraw===3?3:1;
 const suits=['♠','♥','♣','♦'];const red=c=>c.suit===1||c.suit===3;const label=c=>([null,'A','2','3','4','5','6','7','8','9','10','J','Q','K'][c.rank])+suits[c.suit];
 function saveMove(){snapshots.push(JSON.stringify({stock,waste,columns,foundations,score,moves,passes}));if(snapshots.length>100)snapshots.shift();}
 function undo(){if(!snapshots.length)return;const prev=JSON.parse(snapshots.pop());({stock,waste,columns,foundations,score,moves}=prev);passes=prev.passes||0;selected=null;render();}
 menubar(w,{[t("text_game")]:()=>[{label:t("text_new_deal"),shortcut:'F2',action:reset},{label:t("text_undo"),shortcut:'Ctrl+Z',disabled:!snapshots.length,action:undo},null,{label:t("text_draw_one"),checked:drawCount===1,action:()=>{drawCount=1;state.solitaireDraw=1;persist();reset();}},{label:t("text_draw_three"),checked:drawCount===3,action:()=>{drawCount=3;state.solitaireDraw=3;persist();reset();}},{label:t("text_auto_collect"),action:autoCollect},null,{label:t("text_exit"),action:()=>w.close()}],[t("text_help")]:[{label:t("text_game_rules"),action:()=>XP.dialog(t("text_solitaire"),t("text_click_a_card_then_the_column_you_want_it_in_columns_run_down_in_altern_1f92a50a"))} ]});
 const body=document.createElement('div');body.className='solitaire-body';w.body.append(body);const bar=status(w,t("text_score_0"),t("text_moves_0"));
 function reset(){let deck=Array.from({length:52},(_,i)=>({rank:i%13+1,suit:Math.floor(i/13),face:false}));for(let i=51;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}columns=Array.from({length:7},(_,c)=>{const col=deck.splice(0,c+1);col.at(-1).face=true;return col;});stock=deck;waste=[];foundations=[[],[],[],[]];selected=null;score=0;moves=0;passes=0;snapshots=[];render();}
 function card(c,attrs='',active=false,index=0){return `<button class="playing-card ${c.face?red(c)?'red':'':'back'} ${active?'selected':''}" ${attrs} style="--card-i:${index}" aria-label="${c.face?label(c):esc(t("text_face_down_card"))}">${c.face?`${[null,'A','2','3','4','5','6','7','8','9','10','J','Q','K'][c.rank]}<span class="suit">${suits[c.suit]}</span><span class="big-suit">${suits[c.suit]}</span>`:''}</button>`;}
 function render(){body.innerHTML=`<div class="card-top">${stock.length?card({face:false},'data-stock'): `<button class="card-slot" data-stock aria-label="${esc(t("text_deal_the_stock_again"))}">↻</button>`}${waste.length?card({...waste.at(-1),face:true},'data-waste draggable="true"',selected?.kind==='waste'):'<div class="card-slot"></div>'}<span class="spacer"></span>${foundations.map((pile,i)=>pile.length?card(pile.at(-1),`data-foundation="${i}" draggable="true"`,selected?.kind==='foundation'&&selected.pile===i):`<button class="card-slot foundation" data-foundation="${i}" aria-label="${esc(t("text_suit_foundation",{suit:suits[i]}))}">${suits[i]}</button>`).join('')}</div><div class="solitaire-columns">${columns.map((col,c)=>`<div class="card-column" data-column="${c}"><button class="card-slot" data-empty="${c}" aria-label="${esc(t("text_column_n",{n:c+1}))}"></button>${col.map((cardData,i)=>card(cardData,`data-col="${c}" data-index="${i}" ${cardData.face?'draggable="true"':''}`,selected?.kind==='column'&&selected.col===c&&i>=selected.index,i)).join('')}</div>`).join('')}</div><div class="solitaire-help">${esc(t("text_drag_or_click_a_card_then_where_it_should_go_double_click_sends_it_home"))}</div>`;$('span',bar).textContent=t("text_score")+score;$('.status-part',bar).textContent=t("text_moves")+moves+' · '+t(drawCount===1?"text_draw_one":"text_draw_three");const max=Math.max(...columns.map(c=>c.length));$$('.card-column',body).forEach(el=>el.style.minHeight=Math.max(240,max*22+65)+'px');}
 function source(){if(!selected)return[];if(selected.kind==='waste')return waste.length?[waste.at(-1)]:[];if(selected.kind==='foundation')return foundations[selected.pile].length?[foundations[selected.pile].at(-1)]:[];return columns[selected.col].slice(selected.index);}
 function validRun(cards){return cards.length>0&&cards.every((card,i)=>card.face&&(!i||(cards[i-1].rank===card.rank+1&&red(cards[i-1])!==red(card))));}
 function detach(){if(selected.kind==='waste')waste.pop();else if(selected.kind==='foundation')foundations[selected.pile].pop();else{columns[selected.col].splice(selected.index);const top=columns[selected.col].at(-1);if(top&&!top.face){top.face=true;score+=5;}}}
 function canMove(kind,target){const cards=source();if(!cards.length)return false;const first=cards[0];if(kind==='foundation'){const pile=foundations[target];return cards.length===1&&first.suit===target&&first.rank===pile.length+1&&!(selected.kind==='foundation'&&selected.pile===target);}if(selected.kind==='column'&&selected.col===target||!validRun(cards))return false;const pile=columns[target],last=pile.at(-1);return last?last.rank===first.rank+1&&red(last)!==red(first):first.rank===13;}
 function moveTo(kind,target){if(!canMove(kind,target))return false;const cards=source(),from=selected.kind;saveMove();detach();if(kind==='foundation'){cards[0].face=true;foundations[target].push(cards[0]);score+=10;}else{columns[target].push(...cards);score+=from==='waste'?5:from==='foundation'?-15:0;}score=Math.max(0,score);moves++;selected=null;render();if(foundations.every(p=>p.length===13)){XP.sound('notify');notify(t("text_congratulations"),t("text_you_have_laid_out_the_whole_game_score")+score);}return true;}
 function autoCollect(){let changed=true;while(changed){changed=false;const sources=[...(waste.length?[{kind:'waste'}]:[]),...columns.map((c,i)=>c.length?{kind:'column',col:i,index:c.length-1}:null).filter(Boolean)];for(const s of sources){selected=s;const c=source()[0];if(c&&moveTo('foundation',c.suit)){changed=true;break;}}}selected=null;render();}
 body.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-stock')){saveMove();if(stock.length){for(let i=0;i<drawCount&&stock.length;i++){const c=stock.pop();c.face=true;waste.push(c);}}else{stock=waste.reverse().map(c=>({...c,face:false}));waste=[];passes++;if(drawCount===1)score=Math.max(0,score-100);else if(passes>=3)score=Math.max(0,score-20);}moves++;selected=null;render();return;}if(b.hasAttribute('data-waste')){selected=selected?.kind==='waste'?null:{kind:'waste'};render();return;}if(b.hasAttribute('data-foundation')){const target=Number(b.dataset.foundation);if(selected&&moveTo('foundation',target))return;selected=foundations[target].length?{kind:'foundation',pile:target}:null;render();return;}const col=Number(b.dataset.col??b.dataset.empty);if(Number.isNaN(col))return;if(selected&&moveTo('column',col))return;const idx=Number(b.dataset.index);if(Number.isFinite(idx)&&columns[col][idx]?.face){selected=selected?.kind==='column'&&selected.col===col&&selected.index===idx?null:{kind:'column',col,index:idx};}else selected=null;render();};
 // A double click is handled by a short second-click check because cards are redrawn after selection.
 let lastClick={key:'',time:0};body.addEventListener('pointerdown',e=>{if(e.button!==0)return;const b=e.target.closest('[data-col],[data-waste]');if(!b)return;const key=b.hasAttribute('data-waste')?'waste':`${b.dataset.col}:${b.dataset.index}`;const now=Date.now();if(key===lastClick.key&&now-lastClick.time<350){const s=b.hasAttribute('data-waste')?{kind:'waste'}:{kind:'column',col:Number(b.dataset.col),index:Number(b.dataset.index)};selected=s;const c=source()[0];if(c&&source().length===1){e.preventDefault();moveTo('foundation',c.suit);}}lastClick={key,time:now};});
 XP.enableCardDrag?.(body,{start:b=>{lastClick={key:'',time:0};if(b.dataset.waste!==undefined)selected={kind:'waste'};else if(b.dataset.foundation!==undefined)selected={kind:'foundation',pile:Number(b.dataset.foundation)};else selected={kind:'column',col:Number(b.dataset.col),index:Number(b.dataset.index)};const cards=source();if(!validRun(cards))return[];return selected.kind==='column'?$$(`[data-col="${selected.col}"]`,body).filter(el=>Number(el.dataset.index)>=selected.index):[b];},target:el=>{const foundation=el.closest?.('[data-foundation]');if(foundation)return{kind:'foundation',index:Number(foundation.dataset.foundation),el:foundation};const column=el.closest?.('.card-column');return column?{kind:'column',index:Number(column.dataset.column),el:column}:null;},accept:destination=>canMove(destination.kind,destination.index),drop:destination=>moveTo(destination.kind,destination.index),cancel:()=>{selected=null;render();}});
 w.el.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();reset();}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo();}});reset();return w;
});
})();
