'use strict';
(() => {
const { $,esc,icon,register,createWindow,menubar,state,persist,notify,t}=XP;
const pages=[
 {id:'xp',title:t('Microsoft Windows XP – Fedezd fel a lehetőségeket'),url:'www.microsoft.com/windowsxp',keywords:t('windows xp microsoft számítógép operációs rendszer 2001 luna bliss'),description:t('Ismerős. Megbízható. A Windows XP egyesíti a Windows 2000 stabilitását a Windows otthoni élményével.'),body:`<div class="page-header">${esc(t('Microsoft | Windows XP Professional'))}</div><h1>${esc(t('Igen, ez a Windows XP.'))}</h1><p>${esc(t('Az ismerős asztal. A zöld Start gomb. A lehetőség, hogy valami újat alkoss.'))}</p><h2>${esc(t('Egy új világ az asztalodon'))}</h2><p>${esc(t('A Windows XP 2001. október 25-én jelent meg. A Luna felület, az áttervezett Start menü és a Bliss háttérkép egy teljes generáció számítógépes élményeit határozta meg.'))}</p><h2>${esc(t('Kezdj hozzá!'))}</h2><p>${esc(t('Írj egy történetet a Jegyzettömbben, rajzolj a Painttel, vagy tarts egy kis szünetet az Aknakeresővel.'))}</p><p><button class="web-link" data-app="help">${esc(t('Bemutató és első lépések »'))}</button></p>`},
 {id:'wiki',title:t('Wikipédia – A szabad enciklopédia'),url:'hu.wikipedia.org',keywords:t('wikipédia wikipedia enciklopédia tudás történelem internet'),description:t('Üdvözlünk a Wikipédiában! Fedezd fel a számítógépek és az internet történetének néhány fejezetét.'),body:`<div class="wiki-logo">${esc(t('Wikipédia'))}</div><small>${esc(t('A szabad enciklopédia'))}</small><h1>${esc(t('Üdvözlünk a Wikipédiában!'))}</h1><p>${esc(t('Ez az enciklopédia néhány cikkének helyi, rövidített változata.'))}</p><h2>${esc(t('Kiemelt szócikkek'))}</h2><ul><li><button class="web-link" data-page="history">${esc(t('Az internet története'))}</button></li><li><button class="web-link" data-page="xp">Windows XP</button></li><li><button class="web-link" data-page="space">${esc(t('A Naprendszer'))}</button></li><li><button class="web-link" data-page="cats">${esc(t('A házimacska'))}</button></li></ul>`},
 {id:'history',title:t('Az internet története – Wikipédia'),url:'hu.wikipedia.org/wiki/Internet',keywords:t('internet történet arpanet világháló web www böngésző hálózat'),description:t('Az ARPANET-től a World Wide Webig: hogyan kapcsolódtak össze a számítógépek, és született meg a világháló?'),body:`<h1>${esc(t('Az internet története'))}</h1><p>${esc(t('Az internet egymással összekapcsolt számítógépes hálózatok rendszere. Egyik fontos elődje az 1969-ben elindult ARPANET volt.'))}</p><h2>${esc(t('A világháló születése'))}</h2><p>${esc(t('Tim Berners-Lee 1989-ben, a CERN-ben fogalmazta meg a World Wide Web tervét. A hiperhivatkozásokkal összekapcsolt dokumentumokat böngészőprogrammal lehetett elérni.'))}</p><h2>${esc(t('A kétezres évek'))}</h2><p>${esc(t('Betárcsázós modemek, személyes honlapok, fórumok és keresőoldalak. A böngésző címsora egy új világ bejárata lett.'))}</p>`},
 {id:'games',title:t('Játékbarlang – Egy kis szünet mindenkinek jár!'),url:'www.jatekbarlang.hu',keywords:t('játék játékok game games aknakereső minesweeper pasziánsz solitaire freecell pókpasziánsz spider hearts kártya kártyajáték flipper pinball space cadet retro'),description:t('Klasszikus játékok, amelyekhez egy egér és egy szabad délután is elég. Aknakereső, Pasziánsz, FreeCell, Pókpasziánsz, Hearts és 3D Pinball.'),body:`<div class="page-header">${esc(t('★ JÁTÉKBARLANG ★ &nbsp; A kedvenc játékaink, egy helyen'))}</div><h1>${esc(t('Indulhat a játék?'))}</h1><h2>${esc(t('Aknakereső'))}</h2><p>${esc(t('A számok megmutatják, hány akna rejtőzik a szomszédos mezőkön. Jobb kattintással zászlózhatsz. Az első lépésed mindig biztonságos.'))}</p><button class="xp-button" data-app="mines">${esc(t('Aknakereső indítása'))}</button><h2>${esc(t('Pasziánsz'))}</h2><p>${esc(t('Rendezd a lapokat váltakozó színnel csökkenő sorrendbe. Az ászokat tedd a felső gyűjtőhelyekre, majd építsd fel a négy sort királyig.'))}</p><button class="xp-button" data-app="solitaire">${esc(t('Pasziánsz indítása'))}</button><h2>FreeCell</h2><p>${esc(t('Itt mind az 52 lap az asztalon fekszik, semmi sincs elrejtve – szinte minden leosztás kirakható, csak jól kell gondolkodni. A négy szabad hely az átrendezéshez kell. A leosztások számozottak, így a 617-es játék mindig ugyanaz.'))}</p><button class="xp-button" data-app="freecell">${esc(t('FreeCell indítása'))}</button><h2>${esc(t('Pókpasziánsz'))}</h2><p>${esc(t('Két pakli, tíz oszlop, és nyolc teljes sor a győzelemhez királytól ászig. Kezdd egy színnel; ha az már megy, jöhet a kettő, majd a négy.'))}</p><button class="xp-button" data-app="spider">${esc(t('Pókpasziánsz indítása'))}</button><h2>Hearts</h2><p>${esc(t('Négyen játsszák, és itt a pont rossz: minden kőr egyet ér, a pikk dáma tizenhármat. Aki viszont mind a 26 pontot beviszi, az a másik hármat bünteti meg.'))}</p><button class="xp-button" data-app="hearts">${esc(t('Hearts indítása'))}</button><h2>3D Pinball – Space Cadet</h2><p>${esc(t('Az igazi flipperasztal a Windows XP-ből. Z és C a karok, szóközzel lősd ki a golyót, X-szel lökd meg az asztalt – de csak óvatosan, mert a sok lökés TILT-tel végződik.'))}</p><button class="xp-button" data-app="pinball">${esc(t('Space Cadet indítása'))}</button>`},
 {id:'paint',title:t('Paint suli – Rajzolj valami nagyszerűt!'),url:'www.paint-suli.hu',keywords:t('paint rajz festés kép képek kreatív művészet háttér'),description:t('Ceruza, ecset, radír és egy üres vászon. Minden itt kezdődik! Próbáld ki a klasszikus Paintet.'),body:`<h1>${esc(t('Üdv a Paint suliban!'))}</h1><p>${esc(t('Válassz egy színt, fogj egy ecsetet, és engedd szabadjára a képzeleted!'))}</p><h2>${esc(t('Három ötlet az első rajzodhoz'))}</h2><ol><li>${esc(t('Rajzolj egy házikót a domboldalon.'))}</li><li>${esc(t('Készíts saját asztali háttérképet.'))}</li><li>${esc(t('Rajzold le a kedvenc állatodat.'))}</li></ol><p>${esc(t('A téglalap- és ellipsziseszközzel szabályos alakzatokat rajzolhatsz. A Fájl menüből a kész rajzot a Képek mappába mentheted.'))}</p><button class="xp-button" data-app="paint">${esc(t('Paint megnyitása'))}</button>`},
 {id:'wallpapers',title:t('Windows XP háttérképek – Bliss, Azul és Autumn'),url:'www.xp-hatterkepek.hu',keywords:t('háttérkép háttér képek wallpaper bliss azul autumn táj természet hegy domb'),description:t('Emlékszel a zöld dombra? Nézd meg a Windows XP eredeti háttérképeit, és válaszd ki a kedvencedet.'),body:`<h1>${esc(t('Egy ablak a világra'))}</h1><p>${esc(t('A Windows XP ikonikus hátterei. Változtass hangulatot egy kattintással!'))}</p><div><img class="wallpaper-thumb" src="assets/wallpapers/bliss-hd.jpg" alt="Bliss"><img class="wallpaper-thumb" src="assets/wallpapers/azul.jpg" alt="Azul"><img class="wallpaper-thumb" src="assets/wallpapers/autumn.jpg" alt="Autumn"></div><p><button class="xp-button" data-app="display">${esc(t('Asztal testreszabása'))}</button></p>`},
 {id:'music',title:t('Zeneszoba – A Windows hangjai'),url:'www.zeneszoba.hu',keywords:t('zene music mp3 media player lejátszó hang windows startup hangok'),description:t('Néhány másodperc, amit sosem felejtesz el. Hallgasd meg a Windows XP eredeti rendszerhangjait.'),body:`<h1>${esc(t('Ismerős dallamok'))}</h1><p>${esc(t('Vannak hangok, amelyek azonnal visszarepítenek egy másik korszakba.'))}</p><h2>${esc(t('Most játszott: Windows XP Startup'))}</h2><p>${esc(t('Nyisd meg a Windows Media Playert, és hallgasd meg a helyben elérhető rendszerhangokat. Saját hangfájlt is megnyithatsz a gépedről.'))}</p><button class="xp-button" data-app="player">Windows Media Player</button>`},
 {id:'cats',title:t('Házimacska – Wikipédia'),url:'hu.wikipedia.org/wiki/Macska',keywords:t('macska cica cicák cat cats állat állatok kutya kedvenc'),description:t('A házimacska a macskafélék családjába tartozó, az ember mellett élő ragadozó emlős.'),body:`<h1>${esc(t('Házimacska'))}</h1><p>${esc(t('A házimacska ('))}<i>Felis catus</i>${esc(t(') a macskafélék családjába tartozó emlős. Az ember egyik legnépszerűbb társállata.'))}</p><h2>${esc(t('Tudtad?'))}</h2><ul><li>${esc(t('A macskák hallása és éjszakai látása különösen fejlett.'))}</li><li>${esc(t('A bajuszszálak a közvetlen környezet érzékelésében segítenek.'))}</li><li>${esc(t('A macskák a nap jelentős részét alvással töltik.'))}</li></ul><p>${esc(t('Vajon a macskád is a billentyűzeten szeret aludni?'))}</p>`},
 {id:'space',title:t('A Naprendszer – Csillagászati kisokos'),url:'www.csillagok.hu/naprendszer',keywords:t('űr csillag bolygó föld mars naprendszer nap hold jupiter űrhajó csillagászat'),description:t('Nyolc bolygó, egy csillag és megszámlálhatatlan felfedeznivaló. Ismerd meg a Naprendszert!'),body:`<h1>${esc(t('Fedezd fel a Naprendszert!'))}</h1><p>${esc(t('A Naprendszer központi csillaga a Nap. Körülötte nyolc bolygó kering: a Merkúr, a Vénusz, a Föld, a Mars, a Jupiter, a Szaturnusz, az Uránusz és a Neptunusz.'))}</p><h2>${esc(t('A mi bolygónk'))}</h2><p>${esc(t('A Föld a Naptól számított harmadik bolygó. Felszínének nagy részét víz borítja, és egyetlen természetes holdja van: a Hold.'))}</p><h2>${esc(t('A vörös bolygó'))}</h2><p>${esc(t('A Mars vöröses színét a felszínén található vas-oxid okozza. A bolygó felszínét robotjárművek is vizsgálják.'))}</p>`},
 {id:'recipes',title:t('Nagyi receptkönyve – Palacsinta'),url:'www.nagyi-receptjei.hu/palacsinta',keywords:t('étel recept főzés palacsinta süti sütemény konyha finom nagyi'),description:t('A klasszikus palacsinta receptje: liszt, tojás, tej, egy csipet só és egy kis türelem.'),body:`<h1>${esc(t('Nagyi palacsintája'))}</h1><p><i>${esc(t('A legegyszerűbb dolgok néha a legjobbak.'))}</i></p><h2>${esc(t('Hozzávalók'))}</h2><ul><li>${esc(t('20 dkg liszt'))}</li><li>${esc(t('2 tojás'))}</li><li>${esc(t('3 dl tej és kb. 2 dl szódavíz'))}</li><li>${esc(t('1 csipet só és kevés olaj'))}</li></ul><h2>${esc(t('Elkészítés'))}</h2><p>${esc(t('Keverd simára a hozzávalókat. Hagyd pihenni a tésztát, majd vékonyan kiolajozott, forró serpenyőben süsd meg mindkét oldalát. Töltsd meg lekvárral, kakaóval vagy túróval.'))}</p><p>${esc(t('Jó étvágyat!'))}</p>`},
 {id:'html',title:t('HTML suli – Az első honlapod'),url:'www.html-suli.hu',keywords:t('html javascript css programozás kód web honlap fejlesztés tanulás'),description:t('Minden honlap egy ötlettel kezdődik. Ismerkedj meg a HTML, a CSS és a JavaScript alapjaival.'),body:`<h1>${esc(t('Az első honlapod'))}</h1><p>${esc(t('A HTML adja a dokumentum szerkezetét, a CSS a megjelenését, a JavaScript pedig az interaktivitását.'))}</p><h2>${esc(t('Egy egyszerű HTML-dokumentum'))}</h2><pre>${esc(t('&lt;!doctype html&gt;\n&lt;html lang="hu"&gt;\n  &lt;head&gt;&lt;title&gt;Az én oldalam&lt;/title&gt;&lt;/head&gt;\n  &lt;body&gt;\n    &lt;h1&gt;Helló, világ!&lt;/h1&gt;\n  &lt;/body&gt;\n&lt;/html&gt;'))}</pre><p>${esc(t('Nyisd meg a Jegyzettömböt, és kezdd el írni a saját ötleteidet!'))}</p><button class="xp-button" data-app="notepad">${esc(t('Jegyzettömb megnyitása'))}</button>`},
 {id:'google',title:t('Google – Keress a helyi weben'),url:'www.google.hu',keywords:t('google kereső keresés web internet'),description:t('A jól ismert kereső, egy kicsit régebbi ruhában. Próbáld ki: Windows XP, játékok, macska, recept vagy világűr.'),body:''},
 {id:'about',title:t('Webkatalógus – Internet Explorer'),url:'about:offline',keywords:t('webkatalógus katalógus súgó offline helyi információ segítség kezdőlap oldalak'),description:t('A számítógépen tárolt weboldalak gyűjteménye. Kezdd itt, ha nem tudod, mire keress.'),body:`<h1>${esc(t('Webkatalógus'))}</h1><p>${esc(t('Az itt elérhető oldalak a számítógépen vannak eltárolva, így betárcsázás nélkül, azonnal megnyithatók. A keresés is a gépen fut.'))}</p><h2>${esc(t('Mit érdemes kipróbálni?'))}</h2><p>${esc(t('Keress ezekre:'))} <b>${esc(t('Windows XP, játékok, Paint, háttérkép, zene, macska, űr, recept, HTML'))}</b>.</p><p>${esc(t('A címsor is használható: például'))} <b>google.hu</b>, <b>hu.wikipedia.org</b> vagy <b>www.jatekbarlang.hu</b>${esc(t('. A többi internetcímhez helyi hibaoldal tartozik.'))}</p>`}
];
const normalize=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function search(q){const terms=normalize(q).split(/\s+/).filter(Boolean);return pages.map(p=>({p,score:terms.reduce((s,t)=>s+(normalize(p.title).includes(t)?4:0)+(normalize(p.keywords).includes(t)?3:0)+(normalize(p.description).includes(t)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.p);}
XP.webPages=pages;XP.searchWeb=search;
register('ie',(initial)=>{
const w=createWindow({title:t('Google – Microsoft Internet Explorer'),icon:'ie',app:'ie',width:920,height:Math.min(660,innerHeight-130)});
let history=[],pos=-1,current={kind:'home'},favoriteOpen=false;
menubar(w,{
 [t('Fájl')]:[{label:t('Új ablak'),shortcut:'Ctrl+N',action:()=>XP.open('ie')},null,{label:t('Bezárás'),action:()=>w.close()}],
 [t('Szerkesztés')]:[{label:t('Keresés ezen az oldalon…'),shortcut:'Ctrl+F',action:findText}],
 [t('Nézet')]:[{label:t('Frissítés'),shortcut:'F5',action:()=>render()},{label:t('Teljes képernyő'),action:()=>XP.maximize(w)}],
 [t('Kedvencek')]:()=>[{label:t('Hozzáadás a Kedvencekhez…'),action:addFavorite},null,...state.favorites.map(f=>({label:f.title,icon:'ie',action:()=>navigate(f.url)}))],
 [t('Eszközök')]:[{label:t('Kezdőlap beállítása…'),action:async()=>{const value=await XP.prompt('Internetbeállítások',t('Kezdőlap címe:'),state.browserHome||'google.hu');if(value?.trim()){state.browserHome=value.trim().slice(0,300);persist();}}},{label:t('Előzmények törlése'),action:()=>{history=[current];pos=0;updateNavigation();notify('Internet Explorer',t('A böngészési előzményeket töröltük.'));}}],
 [t('Súgó')]:[{label:t('Webkatalógus'),action:()=>navigate('about:offline')},{label:t('Az Internet Explorer névjegye'),action:()=>XP.dialog('Internet Explorer',t('Microsoft Internet Explorer 6\n\nVerzió: 6.0.2900.5512\nFrissítési verziók: SP3\nTermékazonosító: 55274-640-1234567-23456\n\nCopyright © 1995–2001 Microsoft Corporation')) }]
},true);
const toolbar=document.createElement('div');toolbar.className='toolbar';toolbar.innerHTML=`<button data-nav="back" title="${esc(t('Vissza'))}">${icon('back')}<span class="toolbar-label">${esc(t('Vissza'))}</span><span class="dropdown-triangle">▼</span></button><button data-nav="forward" title="Előre">${icon('forward')}</button><span class="toolbar-separator"></span><button data-nav="stop" title="Leállítás">${icon('stop')}</button><button data-nav="refresh" title="Frissítés">${icon('refresh')}</button><button data-nav="home" title="Kezdőlap">${icon('home')}</button><span class="toolbar-separator"></span><button data-nav="search">${icon('search')}<span class="toolbar-label">${esc(t('Keresés'))}</span></button><button data-nav="favorites">${icon('favorite')}<span class="toolbar-label">${esc(t('Kedvencek'))}</span></button><button data-nav="media">${icon('player')}<span class="toolbar-label">${esc(t('Média'))}</span></button>`;w.body.append(toolbar);
const addr=document.createElement('form');addr.className='address-bar';addr.innerHTML=`<label for="address-${w.id}">${esc(t('Cím'))}</label><div class="address-input">${icon('ie')}<input id="address-${w.id}" aria-label="Internet Explorer címsor" type="text" spellcheck="false" autocomplete="off"><span>▾</span></div><button class="go-button" type="submit"><b>➜</b> ${esc(t('Ugrás'))}</button>`;w.body.append(addr);
const layout=document.createElement('div');layout.className='ie-layout';layout.innerHTML='<aside class="favorites-pane" hidden></aside><div class="internet-view"></div>';w.body.append(layout);
const view=$('.internet-view',layout),favorites=$('.favorites-pane',layout),address=$('input',addr);
const status=document.createElement('footer');status.className='status-bar';status.innerHTML=`${icon('ie')}<span>${esc(t('Kész'))}</span><span class="status-part">${icon('network')} ${esc(t('Helyi web'))}</span>`;w.body.append(status);
addr.onsubmit=e=>{e.preventDefault();navigate(address.value);};
toolbar.onclick=e=>{const b=e.target.closest('[data-nav]');if(!b)return;const action=b.dataset.nav;if(action==='back'&&pos>0){current=history[--pos];render();}if(action==='forward'&&pos<history.length-1){current=history[++pos];render();}if(action==='home')navigate(state.browserHome||'google.hu');if(action==='search')navigate('google.hu');if(action==='refresh')render();if(action==='stop')$('span',status).textContent=t('Kész');if(action==='favorites'){favoriteOpen=!favoriteOpen;renderFavorites();}if(action==='media')XP.open('player');};
function updateNavigation(){$('[data-nav=back]',toolbar).disabled=pos<=0;$('[data-nav=forward]',toolbar).disabled=pos>=history.length-1;}
function commit(page){current=page;history=history.slice(0,pos+1);history.push(page);pos++;render();}
function navigate(raw){const value=String(raw||'').trim();if(!value)return;const clean=value.replace(/^https?:\/\//i,'').replace(/\/$/,'').toLowerCase();if(/^(www\.)?google\.(hu|com)(\/.*)?$/.test(clean)){const query=value.includes('?')?new URLSearchParams(value.split('?')[1]).get('q'):null;commit(query?{kind:'search',query}:{kind:'home'});return;}const p=pages.find(p=>p.url.toLowerCase()===clean||p.url.replace(/^www\./,'').toLowerCase()===clean);if(p){commit({kind:'page',id:p.id});return;}if(!/[.:/]/.test(value)||value.includes(' ')){commit({kind:'search',query:value});return;}commit({kind:'error',url:value});}
function addFavorite(){const title=current.kind==='home'?'Google':current.kind==='search'?current.query:pages.find(p=>p.id===current.id)?.title||address.value;const url=address.value;if(!state.favorites.some(f=>f.url===url)){state.favorites.push({title,url});persist();}renderFavorites();notify(t('Kedvencek'),`„${title}” hozzáadva a Kedvencekhez.`);}
async function findText(){
 const q=await XP.prompt('Keresés',t('Keresendő szöveg:'));if(!q)return;
 const walker=document.createTreeWalker(view,NodeFilter.SHOW_TEXT);let node;
 while((node=walker.nextNode())){const at=node.textContent.toLocaleLowerCase('hu').indexOf(q.toLocaleLowerCase('hu'));if(at<0)continue;const range=document.createRange();range.setStart(node,at);range.setEnd(node,at+q.length);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);node.parentElement.scrollIntoView({block:'center'});return;}
 notify(t('Keresés'),t('A keresett szöveg nem található ezen az oldalon.'));
}
function renderFavorites(){favorites.hidden=!favoriteOpen;favorites.innerHTML=`<strong>${esc(t('★ Kedvencek'))}</strong>${state.favorites.map((f,i)=>`<button data-favorite="${i}" title="${esc(f.url)}">${esc(f.title)}</button><button class="favorite-remove" data-remove-favorite="${i}" aria-label="${esc(f.title)} törlése a kedvencekből" title="Törlés">×</button>`).join('')}<button class="xp-button" data-add-favorite>${esc(t('Hozzáadás…'))}</button>`;favorites.onclick=e=>{const b=e.target.closest('[data-favorite]');if(b)navigate(state.favorites[Number(b.dataset.favorite)].url);const remove=e.target.closest('[data-remove-favorite]');if(remove){state.favorites.splice(Number(remove.dataset.removeFavorite),1);persist();renderFavorites();}if(e.target.closest('[data-add-favorite]'))addFavorite();};}
const navHTML=()=>`<nav class="google-nav"><b>${esc(t('Web'))}</b><button class="web-link" data-page="wallpapers">${esc(t('Képek'))}</button><button class="web-link" data-page="games">${esc(t('Játékok'))}</button><button class="web-link" data-page="wiki">${esc(t('Tudástár'))}</button><div class="right"><button class="web-link" data-page="about">${esc(t('Webkatalógus'))}</button><button class="web-link" data-action="favorite">${esc(t('Kedvencekhez'))}</button></div></nav>`;
function render(){updateNavigation();view.scrollTop=0;const page=pages.find(p=>p.id===current.id);if(current.kind==='home'||current.id==='google'){
 address.value='http://www.google.hu/';w.setTitle('Google – Microsoft Internet Explorer');view.innerHTML=navHTML()+`<section class="google-home"><img class="google-logo" src="assets/google.gif" alt="Google"><form class="google-form" data-search-form><div class="google-search-line"><input type="text" name="q" aria-label="Google keresés" autocomplete="off"><div class="advanced-links"><button class="web-link" type="button" data-page="about">${esc(t('Speciális keresés'))}</button><br><button class="web-link" type="button" data-page="about">${esc(t('Nyelvi eszközök'))}</button></div></div><div class="google-buttons"><button class="xp-button" type="submit">${esc(t('Google keresés'))}</button><button class="xp-button" type="button" data-action="lucky">${esc(t('Jó napom van'))}</button></div><div class="search-scope">${esc(t('Keresés:'))} <label><input type="radio" name="scope" value="web" checked> ${esc(t('a weben'))}</label> <label><input type="radio" name="scope" value="hu"> ${esc(t('magyar oldalak'))}</label></div></form><div class="google-footer"><div class="footer-links"><button class="web-link" data-page="xp">${esc(t('Minden a Windows XP-ről'))}</button><button class="web-link" data-page="wiki">${esc(t('Fedezd fel a webet'))}</button><button class="web-link" data-page="about">${esc(t('A Google-ról'))}</button></div><div class="copyright">© 2001 Google · <button class="web-link" data-page="about">${esc(t('Adatvédelem'))}</button></div><p class="google-local">${esc(t('Egy kis időutazás. Egy egész világ az asztalodon.'))}</p></div></section>`;
 }else if(current.kind==='search'){
 const results=search(current.query);address.value=`http://www.google.hu/search?q=${encodeURIComponent(current.query)}`;w.setTitle(`${current.query} – Google keresés`);view.innerHTML=navHTML()+`<div class="search-header"><button class="web-link" data-home><img src="assets/google.gif" alt="Google"></button><form data-search-form><input name="q" type="text" aria-label="Google keresés" value="${esc(current.query)}"><button class="xp-button">${esc(t('Keresés'))}</button></form></div><div class="search-summary">${results.length} találat erre: <b>${esc(current.query)}</b> ${esc(t('· a helyi weben'))}</div><div class="search-results">${results.length?results.map(p=>`<article class="search-result"><button class="web-link" data-page="${p.id}">${esc(p.title)}</button><p>${esc(p.description)}</p><span class="url">${esc(p.url)}</span> <span class="cached">${esc(t('– Helyi változat'))}</span></article>`).join(''):`<p>${esc(t('A keresés –'))} <b>${esc(current.query)}</b> ${esc(t('– nem hozott találatot.'))}</p><p>${esc(t('Próbálj más kulcsszót, vagy fedezd fel a helyi webet:'))}</p>${['windows xp',t('játékok'),'macska','recept',t('űr'),'HTML'].map(q=>`<p><button class="web-link" data-query="${q}">${q}</button></p>`).join('')}`}</div>`;
 }else if(current.kind==='error'){
 address.value=current.url;w.setTitle(t('A lap nem jeleníthető meg – Microsoft Internet Explorer'));view.innerHTML=`<article class="offline-page"><h1>${esc(t('A lap nem jeleníthető meg'))}</h1><p>${esc(t('Az Internet Explorer nem találja a kért oldalt a helyi weben.'))}</p><p><b>${esc(current.url)}</b></p><hr><p>${esc(t('A böngésző a számítógépen tárolt oldalakat éri el, és a megadott cím nincs közöttük.'))}</p><ul><li>${esc(t('Ellenőrizd a beírt címet.'))}</li><li><button class="web-link" data-home>${esc(t('Nyisd meg a Google kezdőlapját.'))}</button></li><li><button class="web-link" data-page="about">${esc(t('Nézd meg az elérhető oldalak súgóját.'))}</button></li></ul><small>${esc(t('HTTP 404 – Az oldal nem szerepel a helyi archívumban.'))}</small></article>`;
 }else if(page){address.value=page.url.startsWith('about:')?page.url:'http://'+page.url;w.setTitle(page.title+' – Microsoft Internet Explorer');view.innerHTML=`<article class="offline-page">${page.render?page.render():page.body}<hr><small>${esc(t('Helyi bemutatóoldal ·'))} <button class="web-link" data-home>${esc(t('Vissza a Google-hoz'))}</button></small></article>`;}
 $('span',status).textContent=t('Kész');}
const pageAPI={view,navigate,refresh:()=>{const top=view.scrollTop;render();view.scrollTop=top;}};
for(const type of ['click','submit','change'])view.addEventListener(type,event=>{const page=pages.find(p=>p.id===current.id);if(current.kind==='page'&&page?.handle){if(type==='submit')event.preventDefault();page.handle(event,pageAPI);}});
view.addEventListener('submit',e=>{const f=e.target.closest('[data-search-form]');if(f){e.preventDefault();const q=new FormData(f).get('q').trim();if(q)commit({kind:'search',query:q});}});
view.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){const target=pages.find(p=>p.id===b.dataset.page);if(target)navigate(target.url);}if(b.dataset.app)XP.open(b.dataset.app);if(b.hasAttribute('data-home'))navigate('google.hu');if(b.dataset.query)commit({kind:'search',query:b.dataset.query});if(b.dataset.action==='favorite')addFavorite();if(b.dataset.action==='lucky'){const q=$('[name=q]',view).value.trim(),p=q?search(q)[0]:pages[0];if(p)navigate(p.url);else commit({kind:'search',query:q});}});
w.el.addEventListener('keydown',e=>{if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();$('[data-nav=back]',toolbar).click();}if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();$('[data-nav=forward]',toolbar).click();}if(e.ctrlKey&&e.key.toLowerCase()==='l'){e.preventDefault();address.focus();address.select();}if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();findText();}if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();XP.open('ie',address.value);}if(e.key==='F5'){e.preventDefault();render();}});
navigate(initial||state.browserHome||'google.hu');return w;
});
})();
