'use strict';
(() => {
const { $,esc,icon,register,createWindow,menubar,state,persist,notify,t}=XP;
const pages=[
 {id:'xp',title:t("text_microsoft_windows_xp_discover_what_you_can_do"),url:'www.microsoft.com/windowsxp',keywords:t("text_windows_xp_microsoft_computer_operating_system_2001_luna_bliss"),description:t("text_familiar_dependable_windows_xp_joins_the_stability_of_windows_2000_wit_2fc5f2f8"),body:`<div class="page-header">${esc(t("text_microsoft_windows_xp_professional"))}</div><h1>${esc(t("text_yes_this_is_windows_xp"))}</h1><p>${esc(t("text_the_familiar_desktop_the_green_start_button_the_chance_to_make_something_new"))}</p><h2>${esc(t("text_a_new_world_on_your_desktop"))}</h2><p>${esc(t("text_windows_xp_arrived_on_25_october_2001_the_luna_theme_the_redrawn_start_4b16308c"))}</p><h2>${esc(t("text_get_started"))}</h2><p>${esc(t("text_write_a_story_in_notepad_draw_something_in_paint_or_take_a_break_with_a51469f8"))}</p><p><button class="web-link" data-app="help">${esc(t("text_tour_and_first_steps"))}</button></p>`},
 {id:'wiki',title:t("text_wikipedia_the_free_encyclopedia"),url:'hu.wikipedia.org',keywords:t("text_wikipedia_encyclopedia_knowledge_history_internet"),description:t("text_welcome_to_wikipedia_explore_a_few_chapters_from_the_history_of_comput_c55efaa5"),body:`<div class="wiki-logo">${esc(t("text_wikipedia"))}</div><small>${esc(t("text_the_free_encyclopedia"))}</small><h1>${esc(t("text_welcome_to_wikipedia"))}</h1><p>${esc(t("text_a_local_shortened_edition_of_a_few_articles_from_that_encyclopedia"))}</p><h2>${esc(t("text_featured_articles"))}</h2><ul><li><button class="web-link" data-page="history">${esc(t("text_the_history_of_the_internet"))}</button></li><li><button class="web-link" data-page="xp">Windows XP</button></li><li><button class="web-link" data-page="space">${esc(t("text_the_solar_system"))}</button></li><li><button class="web-link" data-page="cats">${esc(t("text_the_domestic_cat"))}</button></li></ul>`},
 {id:'history',title:t("text_the_history_of_the_internet_wikipedia"),url:'hu.wikipedia.org/wiki/Internet',keywords:t("text_internet_history_arpanet_world_wide_web_www_browser_network"),description:t("text_from_arpanet_to_the_world_wide_web_how_computers_were_linked_together_f2b17083"),body:`<h1>${esc(t("text_the_history_of_the_internet"))}</h1><p>${esc(t("text_the_internet_is_a_system_of_computer_networks_connected_to_one_another_5132a89d"))}</p><h2>${esc(t("text_the_birth_of_the_world_wide_web"))}</h2><p>${esc(t("text_tim_berners_lee_set_out_the_plan_for_the_world_wide_web_at_cern_in_198_3a554926"))}</p><h2>${esc(t("text_the_early_2000s"))}</h2><p>${esc(t("text_dial_up_modems_personal_home_pages_forums_and_search_engines_the_addre_157e09fe"))}</p>`},
 {id:'games',title:t("text_game_cave_everybody_deserves_a_little_break"),url:'www.jatekbarlang.hu',keywords:t("text_game_games_minesweeper_solitaire_freecell_spider_hearts_cards_card_gam_21caaa47"),description:t("text_classic_games_that_ask_for_no_more_than_a_mouse_and_a_free_afternoon_m_90989525"),body:`<div class="page-header">${esc(t("text_game_cave_and_nbsp_our_favourite_games_all_in_one_place"))}</div><h1>${esc(t("text_ready_to_play"))}</h1><h2>${esc(t("text_minesweeper"))}</h2><p>${esc(t("text_the_numbers_say_how_many_mines_hide_in_the_neighbouring_squares_right_8cfb0548"))}</p><button class="xp-button" data-app="mines">${esc(t("text_start_minesweeper"))}</button><h2>${esc(t("text_solitaire"))}</h2><p>${esc(t("text_order_the_cards_downwards_in_alternating_colours_move_the_aces_to_the_78e1e4d5"))}</p><button class="xp-button" data-app="solitaire">${esc(t("text_start_solitaire"))}</button><h2>FreeCell</h2><p>${esc(t("text_all_52_cards_lie_face_up_here_nothing_is_hidden_nearly_every_deal_can_f30e9a58"))}</p><button class="xp-button" data-app="freecell">${esc(t("text_start_freecell"))}</button><h2>${esc(t("text_spider_solitaire"))}</h2><p>${esc(t("text_two_decks_ten_columns_and_eight_complete_runs_from_king_to_ace_to_win_8b3c42cd"))}</p><button class="xp-button" data-app="spider">${esc(t("text_start_spider_solitaire"))}</button><h2>Hearts</h2><p>${esc(t("text_four_players_and_points_are_the_thing_to_avoid_every_heart_counts_one_1a058748"))}</p><button class="xp-button" data-app="hearts">${esc(t("text_start_hearts"))}</button><h2>3D Pinball – Space Cadet</h2><p>${esc(t("text_the_real_pinball_table_from_windows_xp_z_and_c_work_the_flippers_space_bfba8038"))}</p><button class="xp-button" data-app="pinball">${esc(t("text_start_space_cadet"))}</button>`},
 {id:'paint',title:t("text_paint_school_draw_something_great"),url:'www.paint-suli.hu',keywords:t("text_paint_drawing_painting_picture_pictures_creative_art_background"),description:t("text_a_pencil_a_brush_an_eraser_and_an_empty_canvas_it_all_starts_here_try_df96bd7e"),body:`<h1>${esc(t("text_welcome_to_paint_school"))}</h1><p>${esc(t("text_pick_a_colour_take_a_brush_and_let_your_imagination_go"))}</p><h2>${esc(t("text_three_ideas_for_your_first_drawing"))}</h2><ol><li>${esc(t("text_draw_a_little_house_on_the_hillside"))}</li><li>${esc(t("text_make_a_wallpaper_of_your_own"))}</li><li>${esc(t("text_draw_your_favourite_animal"))}</li></ol><p>${esc(t("text_the_rectangle_and_ellipse_tools_draw_regular_shapes_and_the_file_menu_beb56d94"))}</p><button class="xp-button" data-app="paint">${esc(t("text_open_paint"))}</button>`},
 {id:'wallpapers',title:t("text_windows_xp_wallpapers_bliss_azul_and_autumn"),url:'www.xp-hatterkepek.hu',keywords:t("text_wallpaper_background_pictures_bliss_azul_autumn_landscape_nature_hill_mountain"),description:t("text_remember_the_green_hill_look_through_the_original_windows_xp_wallpaper_cbc8eb2f"),body:`<h1>${esc(t("text_a_window_on_the_world"))}</h1><p>${esc(t("text_the_iconic_windows_xp_wallpapers_change_the_mood_with_a_single_click"))}</p><div><img class="wallpaper-thumb" src="assets/wallpapers/bliss-hd.jpg" alt="Bliss"><img class="wallpaper-thumb" src="assets/wallpapers/azul.jpg" alt="Azul"><img class="wallpaper-thumb" src="assets/wallpapers/autumn.jpg" alt="Autumn"></div><p><button class="xp-button" data-app="display">${esc(t("text_personalise_the_desktop"))}</button></p>`},
 {id:'music',title:t("text_zeneszoba_the_sounds_of_windows"),url:'www.zeneszoba.hu',keywords:t("text_music_mp3_media_player_sound_windows_startup_sounds"),description:t("text_a_few_seconds_you_never_forget_listen_to_the_original_windows_xp_system_sounds"),body:`<h1>${esc(t("text_familiar_tunes"))}</h1><p>${esc(t("text_some_sounds_take_you_straight_back_to_another_era"))}</p><h2>${esc(t("text_now_playing_windows_xp_startup"))}</h2><p>${esc(t("text_open_windows_media_player_and_listen_to_the_system_sounds_that_are_her_c2dd3676"))}</p><button class="xp-button" data-app="player">Windows Media Player</button>`},
 {id:'cats',title:t("text_domestic_cat_wikipedia"),url:'hu.wikipedia.org/wiki/Macska',keywords:t("text_cat_cats_kitten_animal_animals_dog_pet"),description:t("text_the_domestic_cat_is_a_carnivorous_mammal_of_the_cat_family_that_lives_d9d50128"),body:`<h1>${esc(t("text_domestic_cat"))}</h1><p>${esc(t("text_the_domestic_cat_ff4883e6"))}<i>Felis catus</i>${esc(t("text_is_a_mammal_of_the_cat_family_and_one_of_the_most_popular_companions_p_804ee140"))}</p><h2>${esc(t("text_did_you_know"))}</h2><ul><li>${esc(t("text_a_cat_s_hearing_and_night_vision_are_remarkably_good"))}</li><li>${esc(t("text_whiskers_help_a_cat_sense_what_is_right_around_it"))}</li><li>${esc(t("text_cats_spend_a_good_part_of_the_day_asleep"))}</li></ul><p>${esc(t("text_does_your_cat_sleep_on_the_keyboard_too"))}</p>`},
 {id:'space',title:t("text_the_solar_system_a_short_guide_to_astronomy"),url:'www.csillagok.hu/naprendszer',keywords:t("text_space_star_planet_earth_mars_solar_system_sun_moon_jupiter_spacecraft_astronomy"),description:t("text_eight_planets_one_star_and_no_end_of_things_to_discover_get_to_know_th_39c5a0e5"),body:`<h1>${esc(t("text_explore_the_solar_system"))}</h1><p>${esc(t("text_the_sun_sits_at_the_centre_of_the_solar_system_with_eight_planets_arou_988f8f06"))}</p><h2>${esc(t("text_our_planet"))}</h2><p>${esc(t("text_earth_is_the_third_planet_from_the_sun_water_covers_most_of_its_surfac_6ea29988"))}</p><h2>${esc(t("text_the_red_planet"))}</h2><p>${esc(t("text_mars_owes_its_reddish_colour_to_the_iron_oxide_on_its_surface_which_ro_68ef3bd1"))}</p>`},
 {id:'recipes',title:t("text_grandma_s_recipe_book_pancakes"),url:'www.nagyi-receptjei.hu/palacsinta',keywords:t("text_food_recipe_cooking_pancake_cake_baking_kitchen_tasty_grandma"),description:t("text_the_classic_pancake_recipe_flour_eggs_milk_a_pinch_of_salt_and_a_littl_96749ede"),body:`<h1>${esc(t("text_grandma_s_pancakes"))}</h1><p><i>${esc(t("text_the_simplest_things_are_sometimes_the_best"))}</i></p><h2>${esc(t("text_ingredients"))}</h2><ul><li>${esc(t("text_200_g_flour"))}</li><li>${esc(t("text_2_eggs"))}</li><li>${esc(t("text_300_ml_milk_and_about_200_ml_sparkling_water"))}</li><li>${esc(t("text_a_pinch_of_salt_and_a_little_oil"))}</li></ul><h2>${esc(t("text_method"))}</h2><p>${esc(t("text_whisk_the_ingredients_smooth_let_the_batter_rest_then_fry_it_on_both_s_0cbd5e16"))}</p><p>${esc(t("text_enjoy"))}</p>`},
 {id:'html',title:t("text_html_school_your_first_web_page"),url:'www.html-suli.hu',keywords:t("text_html_javascript_css_programming_code_web_page_development_learning"),description:t("text_every_web_page_starts_with_an_idea_get_to_know_the_basics_of_html_css_7812593f"),body:`<h1>${esc(t("text_your_first_web_page"))}</h1><p>${esc(t("text_html_gives_a_document_its_structure_css_its_looks_and_javascript_its_behaviour"))}</p><h2>${esc(t("text_a_simple_html_document"))}</h2><pre>${esc(t("text_and_lt_doctype_html_and_gt_and_lt_html_lang_en_and_gt_and_lt_head_and_671c36ec"))}</pre><p>${esc(t("text_open_notepad_and_start_writing_down_your_own_ideas"))}</p><button class="xp-button" data-app="notepad">${esc(t("text_open_notepad"))}</button>`},
 {id:'google',title:t("text_google_search_the_local_web"),url:'www.google.hu',keywords:t("text_google_search_engine_search_web_internet"),description:t("text_the_search_engine_everybody_knows_in_slightly_older_clothes_try_window_93330fc9"),body:''},
 {id:'about',title:t("text_web_directory_internet_explorer"),url:'about:offline',keywords:t("text_web_directory_catalogue_help_offline_local_information_guide_home_page_pages"),description:t("text_the_collection_of_web_pages_stored_on_this_computer_start_here_if_you_51f5d76b"),body:`<h1>${esc(t("text_web_directory"))}</h1><p>${esc(t("text_the_pages_here_are_stored_on_the_computer_so_they_open_at_once_without_f1555617"))}</p><h2>${esc(t("text_what_is_worth_trying"))}</h2><p>${esc(t("text_try_searching_for"))} <b>${esc(t("text_windows_xp_games_paint_wallpaper_music_cat_space_recipe_html"))}</b>.</p><p>${esc(t("text_the_address_bar_works_too_try"))} <b>google.hu</b>, <b>hu.wikipedia.org</b> ${esc(t("text_or"))} <b>www.jatekbarlang.hu</b>${esc(t("text_every_other_address_gets_a_local_error_page"))}</p>`}
];
const normalize=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function search(q){const terms=normalize(q).split(/\s+/).filter(Boolean);return pages.map(p=>({p,score:terms.reduce((s,t)=>s+(normalize(p.title).includes(t)?4:0)+(normalize(p.keywords).includes(t)?3:0)+(normalize(p.description).includes(t)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.p);}
XP.webPages=pages;XP.searchWeb=search;
register('ie',(initial)=>{
const w=createWindow({title:t("text_google_microsoft_internet_explorer"),icon:'ie',app:'ie',width:920,height:Math.min(660,innerHeight-130)});
let history=[],pos=-1,current={kind:'home'},favoriteOpen=false;
menubar(w,{
 [t("text_file")]:[{label:t("text_new_window"),shortcut:'Ctrl+N',action:()=>XP.open('ie')},null,{label:t("text_close"),action:()=>w.close()}],
 [t("text_edit")]:[{label:t("text_find_on_this_page"),shortcut:'Ctrl+F',action:findText}],
 [t("text_view")]:[{label:t("text_refresh"),shortcut:'F5',action:()=>render()},{label:t("text_full_screen"),action:()=>XP.maximize(w)}],
 [t("text_favorites")]:()=>[{label:t("text_add_to_favorites"),action:addFavorite},null,...state.favorites.map(f=>({label:f.title,icon:'ie',action:()=>navigate(f.url)}))],
 [t("text_tools")]:[{label:t("text_internet_options_7382f1bc"),action:()=>XP.open('internetOptions')}],
 [t("text_help")]:[{label:t("text_web_directory"),action:()=>navigate('about:offline')},{label:t("text_about_internet_explorer"),action:()=>XP.dialog('Internet Explorer',t("text_microsoft_internet_explorer_6_version_6_0_2900_5512_update_versions_sp_663c99c3")) }]
},true);
const toolbar=document.createElement('div');toolbar.className='toolbar';toolbar.innerHTML=`<button data-nav="back" title="${esc(t("text_back"))}">${icon('back')}<span class="toolbar-label">${esc(t("text_back"))}</span><span class="dropdown-triangle">▼</span></button><button data-nav="forward" title="${esc(t("text_forward"))}">${icon('forward')}</button><span class="toolbar-separator"></span><button data-nav="stop" title="${esc(t("text_stop"))}">${icon('stop')}</button><button data-nav="refresh" title="${esc(t("text_refresh"))}">${icon('refresh')}</button><button data-nav="home" title="${esc(t("text_home"))}">${icon('home')}</button><span class="toolbar-separator"></span><button data-nav="search">${icon('search')}<span class="toolbar-label">${esc(t("text_search"))}</span></button><button data-nav="favorites">${icon('favorite')}<span class="toolbar-label">${esc(t("text_favorites"))}</span></button><button data-nav="media">${icon('player')}<span class="toolbar-label">${esc(t("text_media"))}</span></button>`;w.body.append(toolbar);
const addr=document.createElement('form');addr.className='address-bar';addr.innerHTML=`<label for="address-${w.id}">${esc(t("text_address"))}</label><div class="address-input">${icon('ie')}<input id="address-${w.id}" aria-label="${esc(t("text_internet_explorer_address_bar"))}" type="text" spellcheck="false" autocomplete="off"><span>▾</span></div><button class="go-button" type="submit"><b>➜</b> ${esc(t("text_go"))}</button>`;w.body.append(addr);
const layout=document.createElement('div');layout.className='ie-layout';layout.innerHTML='<aside class="favorites-pane" hidden></aside><div class="internet-view"></div>';w.body.append(layout);
const view=$('.internet-view',layout),favorites=$('.favorites-pane',layout),address=$('input',addr);
const status=document.createElement('footer');status.className='status-bar';status.innerHTML=`${icon('ie')}<span>${esc(t("text_done"))}</span><span class="status-part">${icon('network')} ${esc(t("text_local_web"))}</span>`;w.body.append(status);
addr.onsubmit=e=>{e.preventDefault();navigate(address.value);};
toolbar.onclick=e=>{const b=e.target.closest('[data-nav]');if(!b)return;const action=b.dataset.nav;if(action==='back'&&pos>0){current=history[--pos];render();}if(action==='forward'&&pos<history.length-1){current=history[++pos];render();}if(action==='home')navigate(state.browserHome||'google.hu');if(action==='search')navigate('google.hu');if(action==='refresh')render();if(action==='stop')$('span',status).textContent=t("text_done");if(action==='favorites'){favoriteOpen=!favoriteOpen;renderFavorites();}if(action==='media')XP.open('player');};
function updateNavigation(){$('[data-nav=back]',toolbar).disabled=pos<=0;$('[data-nav=forward]',toolbar).disabled=pos>=history.length-1;}
function commit(page){current=page;history=history.slice(0,pos+1);history.push(page);pos++;render();state.browserCurrent=address.value;state.browserHistory=[{title:w.title,url:address.value,at:Date.now()},...(state.browserHistory||[]).filter(item=>item.url!==address.value)].slice(0,50);persist();}
function navigate(raw){const value=String(raw||'').trim();if(!value)return;const clean=value.replace(/^https?:\/\//i,'').replace(/\/$/,'').toLowerCase();if(/^(www\.)?google\.(hu|com)(\/.*)?$/.test(clean)){const query=value.includes('?')?new URLSearchParams(value.split('?')[1]).get('q'):null;commit(query?{kind:'search',query}:{kind:'home'});return;}const p=pages.find(p=>p.url.toLowerCase()===clean||p.url.replace(/^www\./,'').toLowerCase()===clean);if(p){commit({kind:'page',id:p.id});return;}if(!/[.:/]/.test(value)||value.includes(' ')){commit({kind:'search',query:value});return;}commit({kind:'error',url:value});}
function addFavorite(){const title=current.kind==='home'?'Google':current.kind==='search'?current.query:pages.find(p=>p.id===current.id)?.title||address.value;const url=address.value;if(!state.favorites.some(f=>f.url===url)){state.favorites.push({title,url});persist();}renderFavorites();notify(t("text_favorites"),t("text_title_has_been_added_to_your_favorites",{title}));}
async function findText(){
 const q=await XP.prompt(t("text_search"),t("text_find_what"));if(!q)return;
 const walker=document.createTreeWalker(view,NodeFilter.SHOW_TEXT);let node;
 while((node=walker.nextNode())){const at=node.textContent.toLocaleLowerCase('hu').indexOf(q.toLocaleLowerCase('hu'));if(at<0)continue;const range=document.createRange();range.setStart(node,at);range.setEnd(node,at+q.length);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);node.parentElement.scrollIntoView({block:'center'});return;}
 notify(t("text_search"),t("text_the_text_you_searched_for_is_not_on_this_page"));
}
function renderFavorites(){favorites.hidden=!favoriteOpen;favorites.innerHTML=`<strong>${esc(t("text_favorites_9a7cdcf3"))}</strong>${state.favorites.map((f,i)=>`<button data-favorite="${i}" title="${esc(f.url)}">${esc(f.title)}</button><button class="favorite-remove" data-remove-favorite="${i}" aria-label="${esc(t("text_remove_title_from_favorites",{title:f.title}))}" title="${esc(t("text_delete"))}">×</button>`).join('')}<button class="xp-button" data-add-favorite>${esc(t("text_add"))}</button>`;favorites.onclick=e=>{const b=e.target.closest('[data-favorite]');if(b)navigate(state.favorites[Number(b.dataset.favorite)].url);const remove=e.target.closest('[data-remove-favorite]');if(remove){state.favorites.splice(Number(remove.dataset.removeFavorite),1);persist();renderFavorites();}if(e.target.closest('[data-add-favorite]'))addFavorite();};}
const navHTML=()=>`<nav class="google-nav"><b>${esc(t("text_web"))}</b><button class="web-link" data-page="wallpapers">${esc(t("text_my_pictures"))}</button><button class="web-link" data-page="games">${esc(t("text_games"))}</button><button class="web-link" data-page="wiki">${esc(t("text_knowledge"))}</button><div class="right"><button class="web-link" data-page="about">${esc(t("text_web_directory"))}</button><button class="web-link" data-action="favorite">${esc(t("text_add_to_favorites_9f42c7d9"))}</button></div></nav>`;
function render(){updateNavigation();view.scrollTop=0;const page=pages.find(p=>p.id===current.id);if(current.kind==='home'||current.id==='google'){
 address.value='http://www.google.hu/';w.setTitle('Google – Microsoft Internet Explorer');view.innerHTML=navHTML()+`<section class="google-home"><img class="google-logo" src="assets/google.gif" alt="Google"><form class="google-form" data-search-form><div class="google-search-line"><input type="text" name="q" aria-label="${esc(t("text_google_search"))}" autocomplete="off"><div class="advanced-links"><button class="web-link" type="button" data-page="about">${esc(t("text_advanced_search"))}</button><br><button class="web-link" type="button" data-page="about">${esc(t("text_language_tools"))}</button></div></div><div class="google-buttons"><button class="xp-button" type="submit">${esc(t("text_google_search"))}</button><button class="xp-button" type="button" data-action="lucky">${esc(t("text_i_m_feeling_lucky"))}</button></div><div class="search-scope">${esc(t("text_search_f2e38fbf"))} <label><input type="radio" name="scope" value="web" checked> ${esc(t("text_the_web"))}</label> <label><input type="radio" name="scope" value="hu"> ${esc(t("text_pages_in_hungarian"))}</label></div></form><div class="google-footer"><div class="footer-links"><button class="web-link" data-page="xp">${esc(t("text_all_about_windows_xp"))}</button><button class="web-link" data-page="wiki">${esc(t("text_explore_the_web"))}</button><button class="web-link" data-page="about">${esc(t("text_about_google"))}</button></div><div class="copyright">© 2001 Google · <button class="web-link" data-page="about">${esc(t("text_privacy"))}</button></div><p class="google-local">${esc(t("text_a_little_time_travel_a_whole_world_on_your_desktop"))}</p></div></section>`;
 }else if(current.kind==='search'){
 const results=search(current.query);address.value=`http://www.google.hu/search?q=${encodeURIComponent(current.query)}`;w.setTitle(t("text_query_google_search",{query:current.query}));view.innerHTML=navHTML()+`<div class="search-header"><button class="web-link" data-home><img src="assets/google.gif" alt="Google"></button><form data-search-form><input name="q" type="text" aria-label="${esc(t("text_google_search"))}" value="${esc(current.query)}"><button class="xp-button">${esc(t("text_search"))}</button></form></div><div class="search-summary">${esc(t("text_count_results_for",{count:results.length}))} <b>${esc(current.query)}</b> ${esc(t("text_on_the_local_web"))}</div><div class="search-results">${results.length?results.map(p=>`<article class="search-result"><button class="web-link" data-page="${p.id}">${esc(p.title)}</button><p>${esc(p.description)}</p><span class="url">${esc(p.url)}</span> <span class="cached">${esc(t("text_local_edition"))}</span></article>`).join(''):`<p>${esc(t("text_the_search_for"))} <b>${esc(current.query)}</b> ${esc(t("text_returned_no_results"))}</p><p>${esc(t("text_try_another_keyword_or_explore_the_local_web"))}</p>${['windows xp',t("text_games_538f06c5"),'macska','recept',t("text_space_1a049ffd"),'HTML'].map(q=>`<p><button class="web-link" data-query="${q}">${q}</button></p>`).join('')}`}</div>`;
 }else if(current.kind==='error'){
 address.value=current.url;w.setTitle(t("text_the_page_cannot_be_displayed_microsoft_internet_explorer"));view.innerHTML=`<article class="offline-page"><h1>${esc(t("text_the_page_cannot_be_displayed"))}</h1><p>${esc(t("text_internet_explorer_cannot_find_the_page_you_asked_for_on_the_local_web"))}</p><p><b>${esc(current.url)}</b></p><hr><p>${esc(t("text_the_browser_reaches_the_pages_stored_on_this_computer_and_the_address_f672cbf5"))}</p><ul><li>${esc(t("text_check_the_address_you_typed"))}</li><li><button class="web-link" data-home>${esc(t("text_open_the_google_home_page"))}</button></li><li><button class="web-link" data-page="about">${esc(t("text_look_through_the_guide_to_the_pages_that_are_here"))}</button></li></ul><small>${esc(t("text_http_404_the_page_is_not_in_the_local_archive"))}</small></article>`;
 }else if(page){address.value=page.url.startsWith('about:')?page.url:'http://'+page.url;w.setTitle(page.title+' – Microsoft Internet Explorer');view.innerHTML=`<article class="offline-page">${page.render?page.render():page.body}<hr><small>${esc(t("text_local_demonstration_page"))} <button class="web-link" data-home>${esc(t("text_back_to_google"))}</button></small></article>`;}
 $('span',status).textContent=t("text_done");}
const pageAPI={view,navigate,refresh:()=>{const top=view.scrollTop;render();view.scrollTop=top;}};
for(const type of ['click','submit','change'])view.addEventListener(type,event=>{const page=pages.find(p=>p.id===current.id);if(current.kind==='page'&&page?.handle){if(type==='submit')event.preventDefault();page.handle(event,pageAPI);}});
view.addEventListener('submit',e=>{const f=e.target.closest('[data-search-form]');if(f){e.preventDefault();const q=new FormData(f).get('q').trim();if(q)commit({kind:'search',query:q});}});
view.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){const target=pages.find(p=>p.id===b.dataset.page);if(target)navigate(target.url);}if(b.dataset.app)XP.open(b.dataset.app);if(b.hasAttribute('data-home'))navigate('google.hu');if(b.dataset.query)commit({kind:'search',query:b.dataset.query});if(b.dataset.action==='favorite')addFavorite();if(b.dataset.action==='lucky'){const q=$('[name=q]',view).value.trim(),p=q?search(q)[0]:pages[0];if(p)navigate(p.url);else commit({kind:'search',query:q});}});
w.el.addEventListener('keydown',e=>{if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();$('[data-nav=back]',toolbar).click();}if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();$('[data-nav=forward]',toolbar).click();}if(e.ctrlKey&&e.key.toLowerCase()==='l'){e.preventDefault();address.focus();address.select();}if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();findText();}if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();XP.open('ie',address.value);}if(e.key==='F5'){e.preventDefault();render();}});
const clearHistory=()=>{history=[current];pos=0;updateNavigation();};document.addEventListener('xp-browser-history-cleared',clearHistory);w.cleanup.push(()=>document.removeEventListener('xp-browser-history-cleared',clearHistory));
navigate(initial||state.browserHome||'google.hu');return w;
});
})();
