'use strict';
(() => {
const { $,esc,icon,register,createWindow,menubar,state,persist,notify }=XP;
const pages=[
 {id:'xp',title:'Microsoft Windows XP – Fedezd fel a lehetőségeket',url:'www.microsoft.com/windowsxp',keywords:'windows xp microsoft számítógép operációs rendszer 2001 luna bliss',description:'Ismerős. Megbízható. A Windows XP egyesíti a Windows 2000 stabilitását a Windows otthoni élményével.',body:'<div class="page-header">Microsoft | Windows XP Professional</div><h1>Igen, ez a Windows XP.</h1><p>Az ismerős asztal. A zöld Start gomb. A lehetőség, hogy valami újat alkoss.</p><h2>Egy új világ az asztalodon</h2><p>A Windows XP 2001. október 25-én jelent meg. A Luna felület, az áttervezett Start menü és a Bliss háttérkép egy teljes generáció számítógépes élményeit határozta meg.</p><h2>Kezdj hozzá!</h2><p>Írj egy történetet a Jegyzettömbben, rajzolj a Painttel, vagy tarts egy kis szünetet az Aknakeresővel.</p><p><button class="web-link" data-app="help">Bemutató és első lépések »</button></p>'},
 {id:'wiki',title:'Wikipédia – A szabad enciklopédia',url:'hu.wikipedia.org',keywords:'wikipédia wikipedia enciklopédia tudás történelem internet',description:'Üdvözlünk a Wikipédiában! Fedezd fel a számítógépek és az internet történetének néhány fejezetét.',body:'<div class="wiki-logo">Wikipédia</div><small>A szabad enciklopédia</small><h1>Üdvözlünk a Wikipédiában!</h1><p>Ez az enciklopédia néhány cikkének helyi, rövidített változata.</p><h2>Kiemelt szócikkek</h2><ul><li><button class="web-link" data-page="history">Az internet története</button></li><li><button class="web-link" data-page="xp">Windows XP</button></li><li><button class="web-link" data-page="space">A Naprendszer</button></li><li><button class="web-link" data-page="cats">A házimacska</button></li></ul>'},
 {id:'history',title:'Az internet története – Wikipédia',url:'hu.wikipedia.org/wiki/Internet',keywords:'internet történet arpanet világháló web www böngésző hálózat',description:'Az ARPANET-től a World Wide Webig: hogyan kapcsolódtak össze a számítógépek, és született meg a világháló?',body:'<h1>Az internet története</h1><p>Az internet egymással összekapcsolt számítógépes hálózatok rendszere. Egyik fontos elődje az 1969-ben elindult ARPANET volt.</p><h2>A világháló születése</h2><p>Tim Berners-Lee 1989-ben, a CERN-ben fogalmazta meg a World Wide Web tervét. A hiperhivatkozásokkal összekapcsolt dokumentumokat böngészőprogrammal lehetett elérni.</p><h2>A kétezres évek</h2><p>Betárcsázós modemek, személyes honlapok, fórumok és keresőoldalak. A böngésző címsora egy új világ bejárata lett.</p>'},
 {id:'games',title:'Játékbarlang – Egy kis szünet mindenkinek jár!',url:'www.jatekbarlang.hu',keywords:'játék játékok game games aknakereső minesweeper pasziánsz solitaire retro',description:'Klasszikus játékok, amelyekhez egy egér és egy szabad délután is elég. Aknakereső és Pasziánsz.',body:'<div class="page-header">★ JÁTÉKBARLANG ★ &nbsp; A kedvenc játékaink, egy helyen</div><h1>Indulhat a játék?</h1><h2>Aknakereső</h2><p>A számok megmutatják, hány akna rejtőzik a szomszédos mezőkön. Jobb kattintással zászlózhatsz. Az első lépésed mindig biztonságos.</p><button class="xp-button" data-app="mines">Aknakereső indítása</button><h2>Pasziánsz</h2><p>Rendezd a lapokat váltakozó színnel csökkenő sorrendbe. Az ászokat tedd a felső gyűjtőhelyekre, majd építsd fel a négy sort királyig.</p><button class="xp-button" data-app="solitaire">Pasziánsz indítása</button>'},
 {id:'paint',title:'Paint suli – Rajzolj valami nagyszerűt!',url:'www.paint-suli.hu',keywords:'paint rajz festés kép képek kreatív művészet háttér',description:'Ceruza, ecset, radír és egy üres vászon. Minden itt kezdődik! Próbáld ki a klasszikus Paintet.',body:'<h1>Üdv a Paint suliban!</h1><p>Válassz egy színt, fogj egy ecsetet, és engedd szabadjára a képzeleted!</p><h2>Három ötlet az első rajzodhoz</h2><ol><li>Rajzolj egy házikót a domboldalon.</li><li>Készíts saját asztali háttérképet.</li><li>Rajzold le a kedvenc állatodat.</li></ol><p>A téglalap- és ellipsziseszközzel szabályos alakzatokat rajzolhatsz. A Fájl menüből a kész rajzot a Képek mappába mentheted.</p><button class="xp-button" data-app="paint">Paint megnyitása</button>'},
 {id:'wallpapers',title:'Windows XP háttérképek – Bliss, Azul és Autumn',url:'www.xp-hatterkepek.hu',keywords:'háttérkép háttér képek wallpaper bliss azul autumn táj természet hegy domb',description:'Emlékszel a zöld dombra? Nézd meg a Windows XP eredeti háttérképeit, és válaszd ki a kedvencedet.',body:'<h1>Egy ablak a világra</h1><p>A Windows XP ikonikus hátterei. Változtass hangulatot egy kattintással!</p><div><img class="wallpaper-thumb" src="assets/wallpapers/bliss-hd.jpg" alt="Bliss"><img class="wallpaper-thumb" src="assets/wallpapers/azul.jpg" alt="Azul"><img class="wallpaper-thumb" src="assets/wallpapers/autumn.jpg" alt="Autumn"></div><p><button class="xp-button" data-app="display">Asztal testreszabása</button></p>'},
 {id:'music',title:'Zeneszoba – A Windows hangjai',url:'www.zeneszoba.hu',keywords:'zene music mp3 media player lejátszó hang windows startup hangok',description:'Néhány másodperc, amit sosem felejtesz el. Hallgasd meg a Windows XP eredeti rendszerhangjait.',body:'<h1>Ismerős dallamok</h1><p>Vannak hangok, amelyek azonnal visszarepítenek egy másik korszakba.</p><h2>Most játszott: Windows XP Startup</h2><p>Nyisd meg a Windows Media Playert, és hallgasd meg a helyben elérhető rendszerhangokat. Saját hangfájlt is megnyithatsz a gépedről.</p><button class="xp-button" data-app="player">Windows Media Player</button>'},
 {id:'cats',title:'Házimacska – Wikipédia',url:'hu.wikipedia.org/wiki/Macska',keywords:'macska cica cicák cat cats állat állatok kutya kedvenc',description:'A házimacska a macskafélék családjába tartozó, az ember mellett élő ragadozó emlős.',body:'<h1>Házimacska</h1><p>A házimacska (<i>Felis catus</i>) a macskafélék családjába tartozó emlős. Az ember egyik legnépszerűbb társállata.</p><h2>Tudtad?</h2><ul><li>A macskák hallása és éjszakai látása különösen fejlett.</li><li>A bajuszszálak a közvetlen környezet érzékelésében segítenek.</li><li>A macskák a nap jelentős részét alvással töltik.</li></ul><p>Vajon a macskád is a billentyűzeten szeret aludni?</p>'},
 {id:'space',title:'A Naprendszer – Csillagászati kisokos',url:'www.csillagok.hu/naprendszer',keywords:'űr csillag bolygó föld mars naprendszer nap hold jupiter űrhajó csillagászat',description:'Nyolc bolygó, egy csillag és megszámlálhatatlan felfedeznivaló. Ismerd meg a Naprendszert!',body:'<h1>Fedezd fel a Naprendszert!</h1><p>A Naprendszer központi csillaga a Nap. Körülötte nyolc bolygó kering: a Merkúr, a Vénusz, a Föld, a Mars, a Jupiter, a Szaturnusz, az Uránusz és a Neptunusz.</p><h2>A mi bolygónk</h2><p>A Föld a Naptól számított harmadik bolygó. Felszínének nagy részét víz borítja, és egyetlen természetes holdja van: a Hold.</p><h2>A vörös bolygó</h2><p>A Mars vöröses színét a felszínén található vas-oxid okozza. A bolygó felszínét robotjárművek is vizsgálják.</p>'},
 {id:'recipes',title:'Nagyi receptkönyve – Palacsinta',url:'www.nagyi-receptjei.hu/palacsinta',keywords:'étel recept főzés palacsinta süti sütemény konyha finom nagyi',description:'A klasszikus palacsinta receptje: liszt, tojás, tej, egy csipet só és egy kis türelem.',body:'<h1>Nagyi palacsintája</h1><p><i>A legegyszerűbb dolgok néha a legjobbak.</i></p><h2>Hozzávalók</h2><ul><li>20 dkg liszt</li><li>2 tojás</li><li>3 dl tej és kb. 2 dl szódavíz</li><li>1 csipet só és kevés olaj</li></ul><h2>Elkészítés</h2><p>Keverd simára a hozzávalókat. Hagyd pihenni a tésztát, majd vékonyan kiolajozott, forró serpenyőben süsd meg mindkét oldalát. Töltsd meg lekvárral, kakaóval vagy túróval.</p><p>Jó étvágyat!</p>'},
 {id:'html',title:'HTML suli – Az első honlapod',url:'www.html-suli.hu',keywords:'html javascript css programozás kód web honlap fejlesztés tanulás',description:'Minden honlap egy ötlettel kezdődik. Ismerkedj meg a HTML, a CSS és a JavaScript alapjaival.',body:'<h1>Az első honlapod</h1><p>A HTML adja a dokumentum szerkezetét, a CSS a megjelenését, a JavaScript pedig az interaktivitását.</p><h2>Egy egyszerű HTML-dokumentum</h2><pre>&lt;!doctype html&gt;\n&lt;html lang="hu"&gt;\n  &lt;head&gt;&lt;title&gt;Az én oldalam&lt;/title&gt;&lt;/head&gt;\n  &lt;body&gt;\n    &lt;h1&gt;Helló, világ!&lt;/h1&gt;\n  &lt;/body&gt;\n&lt;/html&gt;</pre><p>Nyisd meg a Jegyzettömböt, és kezdd el írni a saját ötleteidet!</p><button class="xp-button" data-app="notepad">Jegyzettömb megnyitása</button>'},
 {id:'google',title:'Google – Keress a helyi weben',url:'www.google.hu',keywords:'google kereső keresés web internet',description:'A jól ismert kereső, egy kicsit régebbi ruhában. Próbáld ki: Windows XP, játékok, macska, recept vagy világűr.',body:''},
 {id:'about',title:'A helyi webről – Internet Explorer',url:'about:offline',keywords:'súgó offline helyi szimulátor információ segítség',description:'Ez a böngésző a szimulátor saját, helyben tárolt weboldalait jeleníti meg.',body:'<h1>Üdv a helyi weben!</h1><p>Az itt látható oldalak nosztalgikus, rövid bemutatóoldalak. Nem kapcsolódnak a valódi szolgáltatókhoz, és a kereséseid nem hagyják el ezt a számítógépet.</p><h2>Mit érdemes kipróbálni?</h2><p>Keress ezekre: <b>Windows XP, játékok, Paint, háttérkép, zene, macska, űr, recept, HTML</b>.</p><p>A címsor is használható: például <b>google.hu</b>, <b>hu.wikipedia.org</b> vagy <b>www.jatekbarlang.hu</b>. A többi internetcímhez helyi hibaoldal tartozik.</p>'}
];
const normalize=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function search(q){const terms=normalize(q).split(/\s+/).filter(Boolean);return pages.map(p=>({p,score:terms.reduce((s,t)=>s+(normalize(p.title).includes(t)?4:0)+(normalize(p.keywords).includes(t)?3:0)+(normalize(p.description).includes(t)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.p);}
XP.webPages=pages;XP.searchWeb=search;
register('ie',(initial)=>{
const w=createWindow({title:'Google – Microsoft Internet Explorer',icon:'ie',app:'ie',width:920,height:Math.min(660,innerHeight-130)});
let history=[],pos=-1,current={kind:'home'},favoriteOpen=false;
menubar(w,{
 'Fájl':[{label:'Új ablak',shortcut:'Ctrl+N',action:()=>XP.open('ie')},null,{label:'Bezárás',action:()=>w.close()}],
 'Szerkesztés':[{label:'Keresés ezen az oldalon…',shortcut:'Ctrl+F',action:async()=>{const q=await XP.prompt('Keresés','Keresendő szöveg:');if(q&&!window.find(q))notify('Keresés','A keresett szöveg nem található ezen az oldalon.');}}],
 'Nézet':[{label:'Frissítés',shortcut:'F5',action:()=>render()},{label:'Teljes képernyő',action:()=>XP.maximize(w)}],
 'Kedvencek':()=>[{label:'Hozzáadás a Kedvencekhez…',action:addFavorite},null,...state.favorites.map(f=>({label:f.title,icon:'ie',action:()=>navigate(f.url)}))],
 'Eszközök':[{label:'Internetbeállítások',action:()=>XP.dialog('Internetbeállítások','Kezdőlap: google.hu\nKapcsolat: helyi web\nA böngésző csak a szimulátor beépített oldalait nyitja meg. Minden keresés ezen a gépen történik.')},{label:'Előzmények törlése',action:()=>{history=[current];pos=0;updateNavigation();notify('Internet Explorer','A böngészési előzményeket töröltük.');}}],
 'Súgó':[{label:'A helyi webről',action:()=>navigate('about:offline')},{label:'Az Internet Explorer névjegye',action:()=>XP.dialog('Internet Explorer','Microsoft Internet Explorer 6\nWindows XP szimulátor\nHelyi, interaktív bemutató.') }]
},true);
const toolbar=document.createElement('div');toolbar.className='toolbar';toolbar.innerHTML=`<button data-nav="back" title="Vissza">${icon('back')}<span class="toolbar-label">Vissza</span><span class="dropdown-triangle">▼</span></button><button data-nav="forward" title="Előre">${icon('forward')}</button><span class="toolbar-separator"></span><button data-nav="stop" title="Leállítás">${icon('stop')}</button><button data-nav="refresh" title="Frissítés">${icon('refresh')}</button><button data-nav="home" title="Kezdőlap">${icon('home')}</button><span class="toolbar-separator"></span><button data-nav="search">${icon('search')}<span class="toolbar-label">Keresés</span></button><button data-nav="favorites">${icon('favorite')}<span class="toolbar-label">Kedvencek</span></button><button data-nav="media">${icon('player')}<span class="toolbar-label">Média</span></button>`;w.body.append(toolbar);
const addr=document.createElement('form');addr.className='address-bar';addr.innerHTML=`<label for="address-${w.id}">Cím</label><div class="address-input">${icon('ie')}<input id="address-${w.id}" aria-label="Internet Explorer címsor" type="text" spellcheck="false" autocomplete="off"><span>▾</span></div><button class="go-button" type="submit"><b>➜</b> Ugrás</button>`;w.body.append(addr);
const layout=document.createElement('div');layout.className='ie-layout';layout.innerHTML='<aside class="favorites-pane" hidden></aside><div class="internet-view"></div>';w.body.append(layout);
const view=$('.internet-view',layout),favorites=$('.favorites-pane',layout),address=$('input',addr);
const status=document.createElement('footer');status.className='status-bar';status.innerHTML=`${icon('ie')}<span>Kész</span><span class="status-part">${icon('network')} Helyi web</span>`;w.body.append(status);
addr.onsubmit=e=>{e.preventDefault();navigate(address.value);};
toolbar.onclick=e=>{const b=e.target.closest('[data-nav]');if(!b)return;const action=b.dataset.nav;if(action==='back'&&pos>0){current=history[--pos];render();}if(action==='forward'&&pos<history.length-1){current=history[++pos];render();}if(action==='home'||action==='search')navigate('google.hu');if(action==='refresh')render();if(action==='stop')$('span',status).textContent='Kész';if(action==='favorites'){favoriteOpen=!favoriteOpen;renderFavorites();}if(action==='media')XP.open('player');};
function updateNavigation(){$('[data-nav=back]',toolbar).disabled=pos<=0;$('[data-nav=forward]',toolbar).disabled=pos>=history.length-1;}
function commit(page){current=page;history=history.slice(0,pos+1);history.push(page);pos++;render();}
function navigate(raw){const value=String(raw||'').trim();if(!value)return;const clean=value.replace(/^https?:\/\//i,'').replace(/\/$/,'').toLowerCase();if(/^(www\.)?google\.(hu|com)(\/.*)?$/.test(clean)){const query=value.includes('?')?new URLSearchParams(value.split('?')[1]).get('q'):null;commit(query?{kind:'search',query}:{kind:'home'});return;}const p=pages.find(p=>p.url.toLowerCase()===clean||p.url.replace(/^www\./,'').toLowerCase()===clean);if(p){commit({kind:'page',id:p.id});return;}if(!/[.:/]/.test(value)||value.includes(' ')){commit({kind:'search',query:value});return;}commit({kind:'error',url:value});}
function addFavorite(){const title=current.kind==='home'?'Google':current.kind==='search'?current.query:pages.find(p=>p.id===current.id)?.title||address.value;const url=address.value;if(!state.favorites.some(f=>f.url===url)){state.favorites.push({title,url});persist();}renderFavorites();notify('Kedvencek',`„${title}” hozzáadva a Kedvencekhez.`);}
function renderFavorites(){favorites.hidden=!favoriteOpen;favorites.innerHTML=`<strong>★ Kedvencek</strong>${state.favorites.map((f,i)=>`<button data-favorite="${i}" title="${esc(f.url)}">${esc(f.title)}</button>`).join('')}<button class="xp-button" data-add-favorite>Hozzáadás…</button>`;favorites.onclick=e=>{const b=e.target.closest('[data-favorite]');if(b)navigate(state.favorites[Number(b.dataset.favorite)].url);if(e.target.closest('[data-add-favorite]'))addFavorite();};}
const navHTML=()=>`<nav class="google-nav"><b>Web</b><button class="web-link" data-page="wallpapers">Képek</button><button class="web-link" data-page="games">Játékok</button><button class="web-link" data-page="wiki">Tudástár</button><div class="right"><button class="web-link" data-page="about">A helyi webről</button><button class="web-link" data-action="favorite">Kedvencekhez</button></div></nav>`;
function render(){updateNavigation();view.scrollTop=0;const page=pages.find(p=>p.id===current.id);if(current.kind==='home'||current.id==='google'){
 address.value='http://www.google.hu/';w.setTitle('Google – Microsoft Internet Explorer');view.innerHTML=navHTML()+`<section class="google-home"><img class="google-logo" src="assets/google.gif" alt="Google"><form class="google-form" data-search-form><div class="google-search-line"><input type="text" name="q" aria-label="Google keresés" autocomplete="off"><div class="advanced-links"><button class="web-link" type="button" data-page="about">Speciális keresés</button><br><button class="web-link" type="button" data-page="about">Nyelvi eszközök</button></div></div><div class="google-buttons"><button class="xp-button" type="submit">Google keresés</button><button class="xp-button" type="button" data-action="lucky">Jó napom van</button></div><div class="search-scope">Keresés: <label><input type="radio" name="scope" value="web" checked> a weben</label> <label><input type="radio" name="scope" value="hu"> magyar oldalak</label></div></form><div class="google-footer"><div class="footer-links"><button class="web-link" data-page="xp">Minden a Windows XP-ről</button><button class="web-link" data-page="wiki">Fedezd fel a webet</button><button class="web-link" data-page="about">A Google-ról</button></div><div class="copyright">© 2001 Google · <button class="web-link" data-page="about">Adatvédelem</button></div><p class="google-local">Egy kis időutazás. Egy egész világ az asztalodon.</p></div></section>`;
 }else if(current.kind==='search'){
 const results=search(current.query);address.value=`http://www.google.hu/search?q=${encodeURIComponent(current.query)}`;w.setTitle(`${current.query} – Google keresés`);view.innerHTML=navHTML()+`<div class="search-header"><button class="web-link" data-home><img src="assets/google.gif" alt="Google"></button><form data-search-form><input name="q" type="text" aria-label="Google keresés" value="${esc(current.query)}"><button class="xp-button">Keresés</button></form></div><div class="search-summary">${results.length} találat erre: <b>${esc(current.query)}</b> · a helyi weben</div><div class="search-results">${results.length?results.map(p=>`<article class="search-result"><button class="web-link" data-page="${p.id}">${esc(p.title)}</button><p>${esc(p.description)}</p><span class="url">${esc(p.url)}</span> <span class="cached">– Helyi változat</span></article>`).join(''):`<p>A keresés – <b>${esc(current.query)}</b> – nem hozott találatot.</p><p>Próbálj más kulcsszót, vagy fedezd fel a helyi webet:</p>${['windows xp','játékok','macska','recept','űr','HTML'].map(q=>`<p><button class="web-link" data-query="${q}">${q}</button></p>`).join('')}`}</div>`;
 }else if(current.kind==='error'){
 address.value=current.url;w.setTitle('A lap nem jeleníthető meg – Microsoft Internet Explorer');view.innerHTML=`<article class="offline-page"><h1>A lap nem jeleníthető meg</h1><p>Az Internet Explorer nem találja a kért oldalt a helyi weben.</p><p><b>${esc(current.url)}</b></p><hr><p>Ez a szimulátor az előre eltárolt weboldalakat jeleníti meg. A külső webhelyek nem érhetők el.</p><ul><li>Ellenőrizd a beírt címet.</li><li><button class="web-link" data-home>Nyisd meg a Google kezdőlapját.</button></li><li><button class="web-link" data-page="about">Nézd meg az elérhető oldalak súgóját.</button></li></ul><small>HTTP 404 – Az oldal nem szerepel a helyi archívumban.</small></article>`;
 }else if(page){address.value=page.url.startsWith('about:')?page.url:'http://'+page.url;w.setTitle(page.title+' – Microsoft Internet Explorer');view.innerHTML=`<article class="offline-page">${page.body}<hr><small>Helyi bemutatóoldal · <button class="web-link" data-home>Vissza a Google-hoz</button></small></article>`;}
 $('span',status).textContent='Kész';}
view.addEventListener('submit',e=>{const f=e.target.closest('[data-search-form]');if(f){e.preventDefault();const q=new FormData(f).get('q').trim();if(q)commit({kind:'search',query:q});}});
view.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){navigate(pages.find(p=>p.id===b.dataset.page).url);}if(b.dataset.app)XP.open(b.dataset.app);if(b.hasAttribute('data-home'))navigate('google.hu');if(b.dataset.query)commit({kind:'search',query:b.dataset.query});if(b.dataset.action==='favorite')addFavorite();if(b.dataset.action==='lucky'){const q=$('[name=q]',view).value.trim(),p=q?search(q)[0]:pages[0];if(p)navigate(p.url);else commit({kind:'search',query:q});}});
w.el.addEventListener('keydown',e=>{if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();$('[data-nav=back]',toolbar).click();}if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();$('[data-nav=forward]',toolbar).click();}if(e.ctrlKey&&e.key.toLowerCase()==='l'){e.preventDefault();address.focus();address.select();}if(e.key==='F5'){e.preventDefault();render();}});
navigate(initial||'google.hu');return w;
});
})();
