'use strict';
(() => {
  const {esc,icon,state,webPages:pages}=XP;
  const link=(id,label)=>`<button type="button" class="web-link" data-page="${id}">${label}</button>`;
  const money=n=>n.toLocaleString('hu-HU')+' Ft';
  const data=()=>state.webDemo||(state.webDemo={cart:{},messages:[],draft:{},vote:''});
  const products=[
    {id:'pc',name:'Otthoni PC 2400+',price:129900,icon:'computer',spec:'2,4 GHz • 512 MB DDR • 80 GB HDD • Windows XP',tag:'A hónap ajánlata'},
    {id:'monitor',name:'17″ síkképcsöves monitor',price:39900,icon:'computer',spec:'1280 × 1024 • 85 Hz • ezüst ház',tag:'Éles kép, nagy munkaterület'},
    {id:'disc',name:'CD-R 700 MB, 10 darab',price:1490,icon:'cd',spec:'48× írható • 80 perc • hengeres csomagolás',tag:'Mentsd el az emlékeidet!'},
    {id:'audio',name:'Multimédiás hangszórópár',price:5990,icon:'volume',spec:'2.0 sztereó • 3,5 mm jack • hangerőszabályzó',tag:'A Windows is jobban szól'}
  ];
  const cartItems=()=>products.map(p=>({...p,quantity:Math.max(0,Math.min(9,Number(data().cart?.[p.id])||0))})).filter(p=>p.quantity);
  const cartTotal=()=>cartItems().reduce((sum,p)=>sum+p.price*p.quantity,0);
  function changeCart(id,delta){if(!products.some(p=>p.id===id))return;const cart=data().cart||(data().cart={});cart[id]=Math.max(0,Math.min(9,(Number(cart[id])||0)+delta));XP.persist();}
  function postMessage(name,message){
    name=String(name).trim().slice(0,30);message=String(message).trim().slice(0,600);
    if(!name||!message)return false;
    data().messages=[{name,message,date:new Date().toLocaleDateString('hu-HU')},...(data().messages||[])].slice(0,30);XP.persist();return true;
  }
  function saveDraft(draft){data().draft={to:String(draft.to||'').slice(0,100),subject:String(draft.subject||'').slice(0,120),body:String(draft.body||'').slice(0,4000)};XP.persist();}
  XP.webDemo={products,cartItems,cartTotal,changeCart,postMessage,saveDraft};
  function site(kind,title,tag,body){return `<div class="retro-site retro-${kind}"><header class="retro-masthead"><strong>${title}</strong><span>${tag}</span></header><nav class="retro-nav">${link('portal','Kezdőlap')} | ${link('shop','Számítástechnika')} | ${link('forum','Fórum')} | ${link('mail','Levelezés')} | ${link('about','Webkatalógus')}</nav>${body}<footer class="retro-footer">© 2004 · A kétezres évek webje · Helyi bemutató</footer></div>`;}
  function add(page){pages.push(page);}
  function update(id,props){Object.assign(pages.find(p=>p.id===id),props);}
  const card=(title,body)=>`<section class="retro-box"><h2>${title}</h2><div>${body}</div></section>`;
  add({id:'portal',title:'Netkapu – A nap itt kezdődik',url:'www.netkapu.hu',keywords:'portál hírek újság időjárás sport számítógép levelezés fórum',description:'Hírek, hasznos oldalak, időjárás és egy kis nosztalgia. A Netkapu 2004-es bemutatókiadása.',render:()=>site('portal','netkapu<span>.hu</span>','Hírek. Emberek. Internet.',`
    <div class="retro-date">2004. szeptember 1., szerda · Archív bemutatókiadás</div>
    <div class="retro-columns"><aside>${card('Navigátor',`<ul class="retro-links"><li>${link('weather','Időjárás')}</li><li>${link('rail','Menetrend')}</li><li>${link('mail','Levelezés')}</li><li>${link('games','Játékok')}</li><li>${link('recipes','Receptklub')}</li><li>${link('wallpapers','Képgaléria')}</li></ul>`)}${card('Szavazás',`<p>Mivel töltöd a szünetet?</p>${data().vote?`<p>Köszönjük a szavazatod!</p>${['Játék','Zene','Böngészés'].map((v,i)=>`<div class="retro-poll">${v} ${[46,32,22][i]}%<span style="width:${[46,32,22][i]}%"></span></div>`).join('')}<small>Bemutatóeredmények · A választásod: ${esc(data().vote)}</small>`:`<form data-web-form="vote">${['Játék','Zene','Böngészés'].map(v=>`<label class="retro-radio"><input type="radio" name="vote" value="${v}" required> ${v}</label>`).join('')}<button class="xp-button">Szavazok</button></form>`}`)}</aside>
    <main><article class="retro-lead"><img src="assets/wallpapers/bliss-hd.jpg" alt="Zöld domb a kék ég alatt"><small>TECHNIKA</small><h1>${link('magazine','Az otthoni számítógép új korszaka')}</h1><p>CD-író, digitális fényképek és az első saját honlap. Minden egyetlen asztalon.</p><p>${link('magazine','A teljes cikk »')}</p></article>${card('Friss a Netkapun',`<h3>${link('rail','Hová menjünk a hétvégén?')}</h3><p>Kirándulj vonattal! Nézd meg a bemutatómenetrendet.</p><h3>${link('html','Készítsd el az első honlapodat!')}</h3><p>Néhány sor szövegből máris személyes oldal lehet.</p><h3>${link('space','Utazás a Naprendszerben')}</h3><p>A vörös bolygótól a Szaturnusz gyűrűiig.</p>`)}</main>
    <aside>${card('Ma ajánljuk',`${icon('player')}<h3>Zene egy kattintásra</h3><p>A Windows ismerős dallamai a Zeneszobában.</p>${link('music','Belépek »')}`)}${card('Közösség',`<p>Mi volt az első számítógéped?</p>${link('forum','Írd meg a fórumban!')}`)}<div class="retro-ad">512 MB RAM<br><b>Elég hely az ötleteidnek.</b><br>${link('shop','PC Bazár »')}</div></aside></div>`),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='vote'){const value=new FormData(e.target).get('vote');if(['Játék','Zene','Böngészés'].includes(value)){data().vote=value;XP.persist();api.refresh();}}}});
  add({id:'magazine',title:'PC Magazin – Az otthoni számítógép új korszaka',url:'www.pc-magazin.hu/otthoni-pc',keywords:'magazin cikk számítógép pc cd író digitális fénykép technika',description:'Egy otthoni PC kalandjai: fényképek, zene, játék és a saját honlap. Nosztalgikus technikai magazin.',body:site('magazine','PC MAGAZIN','A számítógép személyes ügy.',`<div class="retro-article"><p class="retro-kicker">GÉPEK ÉS EMBEREK / 2004. SZEPTEMBER</p><h1>Az otthoni számítógép<br>új korszaka</h1><p class="retro-intro">Egy szürke doboz az asztal alatt. Benne a nyaralás képei, a kedvenc zenéid és néhány félbehagyott kaland.</p><img class="retro-article-photo" src="assets/wallpapers/azul-1920.jpg" alt="Azul: tengerpart és pálmafa"><h2>Az emlékeknek már mappája van</h2><p>A fényképezőgépről a Képek mappába kerülnek a felvételek. A legjobban sikerült kép lesz a háttér, a többit elrendezzük albumokba. Az asztal ettől lesz igazán a miénk.</p><p>${link('wallpapers','Válassz egy új háttérképet »')}</p><h2>Csak még egy menet</h2><p>A házi feladat kész. A Jegyzettömb bezárva. Egy szabad negyedóra épp elég egy leosztáshoz — vagy egy újabb flipperrekordhoz.</p><p>${link('games','A játékrovat ajánlatai »')}</p><h2>Saját hely a világhálón</h2><p>Válassz egy háttérszínt, írj néhány sort magadról, és készíts egy vendégkönyvet. A honlapod lehet egy apró sziget a nagy világhálón.</p><p>${link('html','Próbáld ki a honlapkészítőt »')}</p><hr><p>${link('forum','Szólj hozzá a fórumon')} · ${link('portal','Vissza a Netkapuhoz')}</p></div>`)});
  add({id:'shop',title:'PC Bazár – Számítástechnikai szaküzlet',url:'www.pcbazar.hu',keywords:'bolt vásárlás webshop számítógép monitor cd hardver memória kosár',description:'Korabeli számítógépek, monitorok és kiegészítők. Kipróbálható kosár, bemutatótermékekkel.',render:()=>site('shop','PC BAZÁR','Számítástechnika elérhető áron',`
    <div class="retro-shop-banner">SZEPTEMBERI AJÁNLATOK <span>Új tanév. Új számítógép.</span></div><p class="retro-disclaimer">Bemutatóüzlet, korabeli mintatermékekkel. A kosár helyben megmarad; rendelést és fizetést nem fogadunk.</p><div class="retro-products">${products.map(p=>`<article>${icon(p.icon)}<small>${p.tag}</small><h2>${p.name}</h2><p>${p.spec}</p><strong>${money(p.price)}</strong><button class="xp-button" data-cart-add="${p.id}">Kosárba</button></article>`).join('')}</div>
    <section class="retro-cart"><h2>Az Ön kosara</h2>${cartItems().length?`<table><thead><tr><th>Termék</th><th>Darab</th><th>Összesen</th></tr></thead><tbody>${cartItems().map(p=>`<tr><td>${p.name}</td><td><button class="xp-button" data-cart-remove="${p.id}" aria-label="${p.name}: kevesebb">−</button> ${p.quantity} <button class="xp-button" data-cart-add="${p.id}" aria-label="${p.name}: több" ${p.quantity===9?'disabled':''}>+</button></td><td>${money(p.quantity*p.price)}</td></tr>`).join('')}</tbody></table><p class="retro-total">Végösszeg: <b>${money(cartTotal())}</b></p>`:'<p>A kosár még üres. Válogasson ajánlataink között!</p>'}</section>`),handle(e,api){if(e.type!=='click')return;const b=e.target.closest('[data-cart-add],[data-cart-remove]');if(b){changeCart(b.dataset.cartAdd||b.dataset.cartRemove,b.hasAttribute('data-cart-add')?1:-1);api.refresh();}}});
  const seedMessages=[{name:'ModemMester',date:'2004. 09. 01.',message:'Sziasztok! Nekem egy Pentium II volt az első. A bekapcsolási hangot a mai napig felismerem.'},{name:'kocka_84',date:'2004. 09. 01.',message:'A 3D Pinball örök kedvenc. A küldetéseket érdemes figyelni, nem csak a karokat nyomkodni!'}];
  add({id:'forum',title:'Netklub Fórum – Az első számítógépem',url:'www.netklub.hu/forum',keywords:'fórum közösség hozzászólás vendégkönyv első számítógép beszélgetés',description:'Retró fórum felhasználói hozzászólásokkal. Írj egy emléket a saját gépeden megmaradó vendégkönyvbe.',render:()=>site('forum','NETKLUB FÓRUM','Mindenkinek van egy jó története.',`<div class="retro-forum-path">Fórumok » Számítástechnika » Az első számítógépem</div><h1 class="retro-page-title">Az első számítógépem</h1><p class="retro-disclaimer">Helyi vendégkönyv: a bejegyzéseidet csak ez a böngésző tárolja.</p>${[...(data().messages||[]),...seedMessages].map(m=>`<article class="retro-post"><aside>${icon('user')}<b>${esc(m.name)}</b><small>Klubtag</small></aside><div><header>${esc(m.date)}</header><p>${esc(m.message)}</p></div></article>`).join('')}<form class="retro-compose" data-web-form="guestbook"><h2>Új hozzászólás</h2><label>Becenév <input name="name" required maxlength="30" value="${esc(state.user)}"></label><label>Üzenet <textarea name="message" required maxlength="600" rows="4"></textarea></label><button class="xp-button">Hozzászólás mentése</button><small>Legfeljebb 30 saját hozzászólás marad meg.</small></form>`),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='guestbook'){const fields=new FormData(e.target);if(postMessage(fields.get('name'),fields.get('message')))api.refresh();}}});
  const inbox=[{from:'Netkapu csapata',subject:'Üdvözlünk a Postafiókban!',date:'szept. 1.',body:'Szia!\n\nEz a saját kis postafiókod. A bal oldalon megnyithatod a leveleket, a Piszkozatok fülön pedig írhatsz egy üzenetet, amely frissítés után is megmarad.\n\nJó böngészést!\nA Netkapu csapata'}, {from:'Peti',subject:'Flipper ma délután?',date:'aug. 31.',body:'Szia!\n\nMegvan az új rekordom a Space Cadetben! Nyisd meg a Játékok mappát, és próbáld meg túlszárnyalni.\n\nPeti'}, {from:'Fotóklub',subject:'Képeslap a nyárból',date:'aug. 30.',body:'Kedves Klubtag!\n\nMegérkeztek a nyári képek a galériába. A tengerparti Azul lett a kedvencünk — még asztali háttérnek is tökéletes.\n\nÜdvözlettel: a Fotóklub'}];
  const mailBody=(mode='inbox',selected=0)=>site('mail','postafiók<span>@netkapu</span>','Levelek egy régi ismerőstől',`<div class="retro-mail-layout"><aside><b>${esc(state.user)}</b><button data-mail-view="inbox">Beérkezett (${inbox.length})</button><button data-mail-view="draft">Piszkozatok</button><p>25 MB tárhely</p><div class="retro-mail-meter"><span></span></div><small>0,1 MB foglalt</small></aside><main><p class="retro-disclaimer">Bemutatópostafiók. A piszkozatot a géped tárolja; levélküldés nincs.</p>${mode==='draft'?`<form class="retro-compose" data-web-form="draft"><h2>Új levél – piszkozat</h2><label>Címzett <input name="to" maxlength="100" value="${esc(data().draft?.to||'')}"></label><label>Tárgy <input name="subject" maxlength="120" value="${esc(data().draft?.subject||'')}"></label><label>Üzenet <textarea name="body" maxlength="4000" rows="8">${esc(data().draft?.body||'')}</textarea></label><button class="xp-button">Piszkozat mentése</button><span role="status" data-draft-status></span></form>`:`<h2>Beérkezett levelek</h2><table><thead><tr><th>Feladó / Tárgy</th><th>Dátum</th></tr></thead><tbody>${inbox.map((m,i)=>`<tr class="${i===selected?'selected':''}"><td><button class="web-link" data-mail-id="${i}"><b>${m.from}</b><br>${m.subject}</button></td><td>${m.date}</td></tr>`).join('')}</tbody></table><article class="retro-letter"><h2>${inbox[selected].subject}</h2><small>Feladó: ${inbox[selected].from}</small><p>${inbox[selected].body}</p><button class="xp-button" data-mail-reply="${selected}">Válasz piszkozatban</button></article>`}</main></div>`);
  add({id:'mail',title:'Postafiók – Netkapu levelezés',url:'mail.netkapu.hu',keywords:'email mail levél levelezés freemail postafiók piszkozat',description:'Korabeli webmail három mintalevéllel és menthető piszkozattal.',render:()=>mailBody(),handle(e,api){if(e.type==='click'){const b=e.target.closest('[data-mail-view],[data-mail-id],[data-mail-reply]');if(!b)return;if(b.hasAttribute('data-mail-reply')){const m=inbox[Number(b.dataset.mailReply)];saveDraft({to:m.from,subject:'Re: '+m.subject,body:''});}const html=mailBody(b.dataset.mailView==='draft'||b.hasAttribute('data-mail-reply')?'draft':'inbox',Number(b.dataset.mailId)||0);api.view.querySelector('.offline-page').innerHTML=html;}if(e.type==='submit'&&e.target.dataset.webForm==='draft'){saveDraft(Object.fromEntries(new FormData(e.target)));e.target.querySelector('[data-draft-status]').textContent=' Piszkozat elmentve.';}}});
  const cities=[{name:'Budapest',temp:24,sky:'Napos',wind:'ÉNy, 12 km/h',humidity:52},{name:'Szeged',temp:27,sky:'Derült',wind:'D, 8 km/h',humidity:45},{name:'Debrecen',temp:22,sky:'Változóan felhős',wind:'É, 16 km/h',humidity:61},{name:'Pécs',temp:25,sky:'Napos',wind:'Ny, 9 km/h',humidity:49}];
  const weatherBody=(i=0)=>{const c=cities[i];return site('weather','időjárás<span>.net</span>','Milyen idő lesz holnap?',`<div class="retro-weather-date">2004. szeptember 1. · Szemléltető időjárási adatok</div><div class="retro-weather-content"><label>Város: <select data-weather-city aria-label="Időjárás: város">${cities.map((c,n)=>`<option value="${n}" ${i===n?'selected':''}>${c.name}</option>`).join('')}</select></label><section class="retro-weather-now"><div class="retro-weather-sun" aria-hidden="true">☀</div><div><h1>${c.name}</h1><strong>${c.temp} °C</strong><p>${c.sky}</p></div><dl><dt>Szél</dt><dd>${c.wind}</dd><dt>Páratartalom</dt><dd>${c.humidity}%</dd><dt>Napkelte / napnyugta</dt><dd>06:03 / 19:25</dd></dl></section><h2>Ötnapos előrejelzés – bemutató</h2><div class="retro-forecast">${['Csütörtök','Péntek','Szombat','Vasárnap','Hétfő'].map((day,n)=>`<div><b>${day}</b><span>${n===2?'☁':'☀'}</span><strong>${c.temp+[1,-1,-3,0,2][n]} °C</strong><small>${c.temp-10+n%3} °C</small><p>${n===2?'Felhős':'Napos'}</p></div>`).join('')}</div><p>Kirándulást tervezel? ${link('rail','Nézd meg a menetrendet!')}</p></div>`);};
  add({id:'weather',title:'Időjárás.net – Városi előrejelzés',url:'www.idojaras.net',keywords:'időjárás idő nap eső előrejelzés budapest szeged debrecen pécs',description:'Négy város bemutató-időjárása, hőmérséklettel és ötnapos táblázattal.',render:()=>weatherBody(),handle(e,api){if(e.type==='change'&&e.target.matches('[data-weather-city]'))api.view.querySelector('.offline-page').innerHTML=weatherBody(Number(e.target.value));}});
  const routes=[['Szeged','Napfény IC','06:50','09:12'],['Szeged','Tisza IC','08:50','11:12'],['Debrecen','Hajdú IC','07:23','09:58'],['Debrecen','Cívis IC','09:23','11:58'],['Pécs','Mecsek IC','06:45','09:40'],['Pécs','Sopianae IC','08:45','11:40']];
  const railBody=(city='Szeged')=>site('rail','ELVIRA','Elektronikus vasúti információ',`<div class="retro-rail-content"><h1>Belföldi menetrend</h1><p class="retro-disclaimer">Bemutatómenetrend, kitalált járatokkal és időpontokkal. Utazástervezésre nem használható.</p><form data-web-form="rail" class="retro-rail-form"><label>Honnan? <input value="Budapest" readonly aria-label="Indulási állomás"></label><label>Hová? <select name="city">${['Szeged','Debrecen','Pécs'].map(c=>`<option ${city===c?'selected':''}>${c}</option>`).join('')}</select></label><label>Mikor? <input value="2004. 09. 04." readonly aria-label="Utazás napja"></label><button class="xp-button">Keresés</button></form><h2>Budapest → ${city}</h2><table><thead><tr><th>Járat</th><th>Indulás</th><th>Érkezés</th><th>Átszállás</th></tr></thead><tbody>${routes.filter(r=>r[0]===city).map(r=>`<tr><td><b>${r[1]}</b></td><td>${r[2]}</td><td>${r[3]}</td><td>Közvetlen</td></tr>`).join('')}</tbody></table>${card('A kellemes utazásért','<p>A vonatra felszállás előtt ellenőrizd a vágányszámot. Az ablak mellől egészen más arcát mutatja a táj.</p>')}<p>${link('weather','Időjárás a célállomáson')} · ${link('wallpapers','Úti képeslapok')}</p></div>`);
  add({id:'rail',title:'ELVIRA – Belföldi bemutatómenetrend',url:'www.elvira.hu',keywords:'vonat vasút menetrend utazás kirándulás budapest szeged pécs debrecen',description:'Válassz célállomást, és keress járatot a nosztalgikus menetrendben. Kitalált bemutatóadatok.',render:()=>railBody(),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='rail'){const city=new FormData(e.target).get('city');if(['Szeged','Debrecen','Pécs'].includes(city))api.view.querySelector('.offline-page').innerHTML=railBody(city);}}});
  update('wallpapers',{body:site('gallery','XP KÉPGALÉRIA','Egy ablak a világra.',`<div class="retro-gallery-intro"><h1>Vidd magaddal a tájat!</h1><p>Az eredeti Windows XP hátterek 1920 × 1200 képpontos változatai.</p></div><div class="retro-gallery">${[['bliss','Bliss','A zöld domb, amelyet mindenki ismer.'],['azul','Azul','Egy pálmafa. Egy sziget. Egy kis nyugalom.'],['autumn','Autumn','Aranyló levelek és egy csendes őszi ösvény.']].map(([id,title,desc])=>`<figure><img src="${XP.wallpaperPath(id)}" alt="${title}"><figcaption><h2>${title}</h2><p>${desc}</p><button class="xp-button" data-wallpaper="${id}">Beállítás háttérként</button></figcaption></figure>`).join('')}</div>`),handle(e){if(e.type!=='click')return;const id=e.target.closest('[data-wallpaper]')?.dataset.wallpaper;if(['bliss','azul','autumn'].includes(id)){state.wallpaper=id;XP.persist();XP.applySettings();XP.notify('Asztali háttér','Az új háttérkép beállítva.');}}});
  update('html',{body:site('school','HTML SULI','Az első honlapod itt kezdődik.',`<div class="retro-school-content"><h1>Helló, világ!</h1><p>A HTML adja az oldal szerkezetét, a CSS a színeit. Próbáld ki a kis honlapkészítőt!</p><form data-web-form="homepage" class="retro-compose"><label>Az oldal címe <input name="title" maxlength="80" value="Üdv a honlapomon!"></label><label>Bemutatkozás <textarea name="body" maxlength="1000" rows="4">Szia! Ez az első honlapom. Szeretem a zenét, a játékokat és a számítógépeket.</textarea></label><label>Háttérszín <select name="color"><option value="cream">Vajszínű</option><option value="blue">Világoskék</option><option value="green">Világoszöld</option></select></label><button class="xp-button">Előnézet</button></form><section class="retro-home-preview" data-home-preview><h2>Üdv a honlapomon!</h2><p>Itt jelenik meg az oldalad előnézete.</p></section><h2>Mi van a háttérben?</h2><pre data-home-code>&lt;h1&gt;Üdv a honlapomon!&lt;/h1&gt;</pre><p>A szöveget a Jegyzettömbben is továbbírhatod.</p><button class="xp-button" data-app="notepad">Jegyzettömb megnyitása</button></div>`),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='homepage'){const f=new FormData(e.target),title=String(f.get('title')).slice(0,80),body=String(f.get('body')).slice(0,1000),preview=api.view.querySelector('[data-home-preview]');preview.style.backgroundColor=({cream:'#fffce6',blue:'#e4f0ff',green:'#eaf8e2'})[f.get('color')]||'#fffce6';preview.innerHTML=`<h2>${esc(title)}</h2><p>${esc(body)}</p>`;api.view.querySelector('[data-home-code]').textContent=`<h1>${esc(title)}</h1>\n<p>${esc(body)}</p>`;}}});
  update('music',{body:site('music','ZENE<span>SZOBA</span>','A hangok hazatalálnak.',`<div class="retro-music-hero">${icon('player')}<div><small>A HÉT ALBUMA</small><h1>A Windows hangjai</h1><p>Négy rövid dallam. Egy egész korszak.</p><button class="xp-button" data-app="player">Lejátszó megnyitása</button></div></div><div class="retro-music-content"><h2>Windows XP / Rendszerhangok</h2><table><tr><th>#</th><th>Cím</th><th>Előadó</th></tr>${['Startup','Shutdown','Notify','Ding'].map((t,i)=>`<tr><td>0${i+1}</td><td>${t}</td><td>Microsoft Windows XP</td></tr>`).join('')}</table><h2>A zene veled jön</h2><p>Nyiss meg saját MP3, WAV vagy OGG fájlokat a Windows Media Playerben. A médiatárban kereshetsz, a lejátszási listán sorrendet választhatsz, a vizualizáció pedig követi a dallamot.</p><h2>Azok a régi CD-k</h2><p>Kézzel felírt számlista, műanyag tok, kedvenc szám a hetedik helyen. Neked melyik lemez jut eszedbe?</p>${link('forum','Meséld el a fórumban »')}</div>`)});
  update('recipes',{body:site('recipe','Nagyi receptkönyve','Egy csipet szeretet.',`<div class="retro-recipe-content"><small>A CSALÁD KEDVENCEI / ÉDES TÉSZTÁK</small><h1>Nagyi palacsintája</h1><p class="retro-intro">Lekvárral, kakaóval vagy túróval. De leginkább együtt.</p><label>Adag: <select data-portions><option value="1">12 palacsinta</option><option value="2">24 palacsinta</option><option value="3">36 palacsinta</option></select></label><div class="retro-recipe-columns"><section><h2>Hozzávalók</h2><ul data-ingredients><li>20 dkg liszt</li><li>2 tojás</li><li>3 dl tej</li><li>2 dl szódavíz</li></ul><p>Egy csipet só és kevés olaj.</p></section><section><h2>Elkészítés</h2><ol><li>Keverd simára a lisztet, a tojást és a tejet.</li><li>Add hozzá a szódavizet és a sót. Pihentesd 20 percig.</li><li>Forró, vékonyan olajozott serpenyőbe merj egy kevés tésztát.</li><li>Süsd meg mindkét oldalát, majd töltsd meg a kedvenc töltelékeddel.</li></ol></section></div><blockquote>Nagyi tippje: az első palacsinta a szakácsé!</blockquote><p>${link('portal','Vissza a Netkapuhoz')}</p></div>`),handle(e,api){if(e.type==='change'&&e.target.matches('[data-portions]')){const n=Number(e.target.value);if([1,2,3].includes(n))api.view.querySelector('[data-ingredients]').innerHTML=`<li>${20*n} dkg liszt</li><li>${2*n} tojás</li><li>${3*n} dl tej</li><li>${2*n} dl szódavíz</li>`;}}});
  update('about',{render:()=>site('directory','Webkatalógus','A helyi web összes oldala, egy helyen.',`<div class="retro-directory"><h1>Merre induljunk?</h1><p>${pages.length} helyi oldal vár felfedezésre. A keresőben címre, témára és kulcsszóra is kereshetsz.</p><div>${pages.filter(p=>p.id!=='about').map(p=>`<article><h2>${link(p.id,esc(p.title))}</h2><small>${esc(p.url)}</small><p>${esc(p.description)}</p></article>`).join('')}</div></div>`)});
})();
