'use strict';
(() => {
  const {esc,icon,state,webPages:pages,t}=XP;
  const link=(id,label)=>`<button type="button" class="web-link" data-page="${id}">${label}</button>`;
  const money=n=>n.toLocaleString('hu-HU')+' Ft';
  const data=()=>state.webDemo||(state.webDemo={cart:{},messages:[],draft:{},vote:''});
  const products=[
    {id:'pc',name:t('Otthoni PC 2400+'),price:129900,icon:'computer',spec:'2,4 GHz • 512 MB DDR • 80 GB HDD • Windows XP',tag:t('A hónap ajánlata')},
    {id:'monitor',name:t('17″ síkképcsöves monitor'),price:39900,icon:'computer',spec:t('1280 × 1024 • 85 Hz • ezüst ház'),tag:t('Éles kép, nagy munkaterület')},
    {id:'disc',name:t('CD-R 700 MB, 10 darab'),price:1490,icon:'cd',spec:t('48× írható • 80 perc • hengeres csomagolás'),tag:t('Mentsd el az emlékeidet!')},
    {id:'audio',name:t('Multimédiás hangszórópár'),price:5990,icon:'volume',spec:t('2.0 sztereó • 3,5 mm jack • hangerőszabályzó'),tag:t('A Windows is jobban szól')}
  ];
  const cartItems=()=>products.map(p=>({...p,quantity:Math.max(0,Math.min(9,Number(data().cart?.[p.id])||0))})).filter(p=>p.quantity);
  const cartTotal=()=>cartItems().reduce((sum,p)=>sum+p.price*p.quantity,0);
  function changeCart(id,delta){if(!products.some(p=>p.id===id))return;const cart=data().cart||(data().cart={});cart[id]=Math.max(0,Math.min(9,(Number(cart[id])||0)+delta));XP.persist();}
  function postMessage(name,message){
    name=String(name).trim().slice(0,30);message=String(message).trim().slice(0,600);
    if(!name||!message)return false;
    data().messages=[{name,message,date:new Date().toLocaleDateString('hu-HU')},...(data().messages||[])].slice(0,30);XP.persist();return true;
  }
  function saveDraft(draft){data().draft={to:String(draft.to||'').slice(0,100),subject:String(draft.subject||'').slice(0,120),body:String(draft.body||'').slice(0,4000)};XP.persist();}
  XP.webDemo={products,cartItems,cartTotal,changeCart,postMessage,saveDraft};
  function site(kind,title,tag,body){return `<div class="retro-site retro-${kind}"><header class="retro-masthead"><strong>${title}</strong><span>${tag}</span></header><nav class="retro-nav">${link('portal',t('Kezdőlap'))} | ${link('shop',t('Számítástechnika'))} | ${link('forum',t('Fórum'))} | ${link('mail',t('Levelezés'))} | ${link('about',t('Webkatalógus'))}</nav>${body}<footer class="retro-footer">${esc(t('© 2004 · A kétezres évek webje · Helyi bemutató'))}</footer></div>`;}
  function add(page){pages.push(page);}
  function update(id,props){Object.assign(pages.find(p=>p.id===id),props);}
  const card=(title,body)=>`<section class="retro-box"><h2>${title}</h2><div>${body}</div></section>`;
  add({id:'portal',title:t('Netkapu – A nap itt kezdődik'),url:'www.netkapu.hu',keywords:t('portál hírek újság időjárás sport számítógép levelezés fórum'),description:t('Hírek, hasznos oldalak, időjárás és egy kis nosztalgia. A Netkapu 2004-es bemutatókiadása.'),render:()=>site('portal','netkapu<span>.hu</span>',t('Hírek. Emberek. Internet.'),`
    <div class="retro-date">${esc(t('2004. szeptember 1., szerda · Archív bemutatókiadás'))}</div>
    <div class="retro-columns"><aside>${card(t('Navigátor'),`<ul class="retro-links"><li>${link('weather',t('Időjárás'))}</li><li>${link('rail','Menetrend')}</li><li>${link('mail',t('Levelezés'))}</li><li>${link('games',t('Játékok'))}</li><li>${link('recipes','Receptklub')}</li><li>${link('wallpapers',t('Képgaléria'))}</li></ul>`)}${card(t('Szavazás'),`<p>${esc(t('Mivel töltöd a szünetet?'))}</p>${data().vote?`<p>${esc(t('Köszönjük a szavazatod!'))}</p>${[t('Játék'),'Zene',t('Böngészés')].map((v,i)=>`<div class="retro-poll">${v} ${[46,32,22][i]}%<span style="width:${[46,32,22][i]}%"></span></div>`).join('')}<small>Bemutatóeredmények · A választásod: ${esc(data().vote)}</small>`:`<form data-web-form="vote">${[t('Játék'),'Zene',t('Böngészés')].map(v=>`<label class="retro-radio"><input type="radio" name="vote" value="${v}" required> ${v}</label>`).join('')}<button class="xp-button">${esc(t('Szavazok'))}</button></form>`}`)}</aside>
    <main><article class="retro-lead"><img src="assets/wallpapers/bliss-hd.jpg" alt="Zöld domb a kék ég alatt"><small>${esc(t('TECHNIKA'))}</small><h1>${link('magazine',t('Az otthoni számítógép új korszaka'))}</h1><p>${esc(t('CD-író, digitális fényképek és az első saját honlap. Minden egyetlen asztalon.'))}</p><p>${link('magazine',t('A teljes cikk »'))}</p></article>${card('Friss a Netkapun',`<h3>${link('rail',t('Hová menjünk a hétvégén?'))}</h3><p>${esc(t('Kirándulj vonattal! Nézd meg a bemutatómenetrendet.'))}</p><h3>${link('html',t('Készítsd el az első honlapodat!'))}</h3><p>${esc(t('Néhány sor szövegből máris személyes oldal lehet.'))}</p><h3>${link('space',t('Utazás a Naprendszerben'))}</h3><p>${esc(t('A vörös bolygótól a Szaturnusz gyűrűiig.'))}</p>`)}</main>
    <aside>${card(t('Ma ajánljuk'),`${icon('player')}<h3>${esc(t('Zene egy kattintásra'))}</h3><p>${esc(t('A Windows ismerős dallamai a Zeneszobában.'))}</p>${link('music',t('Belépek »'))}`)}${card(t('Közösség'),`<p>${esc(t('Mi volt az első számítógéped?'))}</p>${link('forum',t('Írd meg a fórumban!'))}`)}<div class="retro-ad">512 MB RAM<br><b>${esc(t('Elég hely az ötleteidnek.'))}</b><br>${link('shop',t('PC Bazár »'))}</div></aside></div>`),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='vote'){const value=new FormData(e.target).get('vote');if([t('Játék'),'Zene',t('Böngészés')].includes(value)){data().vote=value;XP.persist();api.refresh();}}}});
  add({id:'magazine',title:t('PC Magazin – Az otthoni számítógép új korszaka'),url:'www.pc-magazin.hu/otthoni-pc',keywords:t('magazin cikk számítógép pc cd író digitális fénykép technika'),description:t('Egy otthoni PC kalandjai: fényképek, zene, játék és a saját honlap. Nosztalgikus technikai magazin.'),body:site('magazine','PC MAGAZIN',t('A számítógép személyes ügy.'),`<div class="retro-article"><p class="retro-kicker">${esc(t('GÉPEK ÉS EMBEREK / 2004. SZEPTEMBER'))}</p><h1>${esc(t('Az otthoni számítógép'))}<br>${esc(t('új korszaka'))}</h1><p class="retro-intro">${esc(t('Egy szürke doboz az asztal alatt. Benne a nyaralás képei, a kedvenc zenéid és néhány félbehagyott kaland.'))}</p><img class="retro-article-photo" src="assets/wallpapers/azul-1920.jpg" alt="Azul: tengerpart és pálmafa"><h2>${esc(t('Az emlékeknek már mappája van'))}</h2><p>${esc(t('A fényképezőgépről a Képek mappába kerülnek a felvételek. A legjobban sikerült kép lesz a háttér, a többit elrendezzük albumokba. Az asztal ettől lesz igazán a miénk.'))}</p><p>${link('wallpapers',t('Válassz egy új háttérképet »'))}</p><h2>${esc(t('Csak még egy menet'))}</h2><p>${esc(t('A házi feladat kész. A Jegyzettömb bezárva. Egy szabad negyedóra épp elég egy leosztáshoz — vagy egy újabb flipperrekordhoz.'))}</p><p>${link('games',t('A játékrovat ajánlatai »'))}</p><h2>${esc(t('Saját hely a világhálón'))}</h2><p>${esc(t('Válassz egy háttérszínt, írj néhány sort magadról, és készíts egy vendégkönyvet. A honlapod lehet egy apró sziget a nagy világhálón.'))}</p><p>${link('html',t('Próbáld ki a honlapkészítőt »'))}</p><hr><p>${link('forum',t('Szólj hozzá a fórumon'))} · ${link('portal','Vissza a Netkapuhoz')}</p></div>`)});
  add({id:'shop',title:t('PC Bazár – Számítástechnikai szaküzlet'),url:'www.pcbazar.hu',keywords:t('bolt vásárlás webshop számítógép monitor cd hardver memória kosár'),description:t('Korabeli számítógépek, monitorok és kiegészítők. Kipróbálható kosár, bemutatótermékekkel.'),render:()=>site('shop',t('PC BAZÁR'),t('Számítástechnika elérhető áron'),`
    <div class="retro-shop-banner">${esc(t('SZEPTEMBERI AJÁNLATOK'))} <span>${esc(t('Új tanév. Új számítógép.'))}</span></div><p class="retro-disclaimer">${esc(t('Bemutatóüzlet, korabeli mintatermékekkel. A kosár helyben megmarad; rendelést és fizetést nem fogadunk.'))}</p><div class="retro-products">${products.map(p=>`<article>${icon(p.icon)}<small>${p.tag}</small><h2>${p.name}</h2><p>${p.spec}</p><strong>${money(p.price)}</strong><button class="xp-button" data-cart-add="${p.id}">${esc(t('Kosárba'))}</button></article>`).join('')}</div>
    <section class="retro-cart"><h2>${esc(t('Az Ön kosara'))}</h2>${cartItems().length?`<table><thead><tr><th>${esc(t('Termék'))}</th><th>${esc(t('Darab'))}</th><th>${esc(t('Összesen'))}</th></tr></thead><tbody>${cartItems().map(p=>`<tr><td>${p.name}</td><td><button class="xp-button" data-cart-remove="${p.id}" aria-label="${p.name}: kevesebb">−</button> ${p.quantity} <button class="xp-button" data-cart-add="${p.id}" aria-label="${p.name}: több" ${p.quantity===9?'disabled':''}>+</button></td><td>${money(p.quantity*p.price)}</td></tr>`).join('')}</tbody></table><p class="retro-total">${esc(t('Végösszeg:'))} <b>${money(cartTotal())}</b></p>`:`<p>${esc(t('A kosár még üres. Válogasson ajánlataink között!'))}</p>`}</section>`),handle(e,api){if(e.type!=='click')return;const b=e.target.closest('[data-cart-add],[data-cart-remove]');if(b){changeCart(b.dataset.cartAdd||b.dataset.cartRemove,b.hasAttribute('data-cart-add')?1:-1);api.refresh();}}});
  const seedMessages=[{name:t('ModemMester'),date:'2004. 09. 01.',message:t('Sziasztok! Nekem egy Pentium II volt az első. A bekapcsolási hangot a mai napig felismerem.')},{name:t('kocka_84'),date:'2004. 09. 01.',message:t('A 3D Pinball örök kedvenc. A küldetéseket érdemes figyelni, nem csak a karokat nyomkodni!')}];
  add({id:'forum',title:t('Netklub Fórum – Az első számítógépem'),url:'www.netklub.hu/forum',keywords:t('fórum közösség hozzászólás vendégkönyv első számítógép beszélgetés'),description:t('Retró fórum felhasználói hozzászólásokkal. Írj egy emléket a saját gépeden megmaradó vendégkönyvbe.'),render:()=>site('forum',t('NETKLUB FÓRUM'),t('Mindenkinek van egy jó története.'),`<div class="retro-forum-path">${esc(t('Fórumok » Számítástechnika » Az első számítógépem'))}</div><h1 class="retro-page-title">${esc(t('Az első számítógépem'))}</h1><p class="retro-disclaimer">${esc(t('Helyi vendégkönyv: a bejegyzéseidet csak ez a böngésző tárolja.'))}</p>${[...(data().messages||[]),...seedMessages].map(m=>`<article class="retro-post"><aside>${icon('user')}<b>${esc(m.name)}</b><small>${esc(t('Klubtag'))}</small></aside><div><header>${esc(m.date)}</header><p>${esc(m.message)}</p></div></article>`).join('')}<form class="retro-compose" data-web-form="guestbook"><h2>${esc(t('Új hozzászólás'))}</h2><label>${esc(t('Becenév'))} <input name="name" required maxlength="30" value="${esc(state.user)}"></label><label>${esc(t('Üzenet'))} <textarea name="message" required maxlength="600" rows="4"></textarea></label><button class="xp-button">${esc(t('Hozzászólás mentése'))}</button><small>${esc(t('Legfeljebb 30 saját hozzászólás marad meg.'))}</small></form>`),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='guestbook'){const fields=new FormData(e.target);if(postMessage(fields.get('name'),fields.get('message')))api.refresh();}}});
  const inbox=[{from:'Netkapu csapata',subject:t('Üdvözlünk a Postafiókban!'),date:'szept. 1.',body:t('Szia!\n\nEz a saját kis postafiókod. A bal oldalon megnyithatod a leveleket, a Piszkozatok fülön pedig írhatsz egy üzenetet, amely frissítés után is megmarad.\n\nJó böngészést!\nA Netkapu csapata')}, {from:'Peti',subject:t('Flipper ma délután?'),date:'aug. 31.',body:t('Szia!\n\nMegvan az új rekordom a Space Cadetben! Nyisd meg a Játékok mappát, és próbáld meg túlszárnyalni.\n\nPeti')}, {from:t('Fotóklub'),subject:t('Képeslap a nyárból'),date:'aug. 30.',body:t('Kedves Klubtag!\n\nMegérkeztek a nyári képek a galériába. A tengerparti Azul lett a kedvencünk — még asztali háttérnek is tökéletes.\n\nÜdvözlettel: a Fotóklub')}];
  const mailBody=(mode='inbox',selected=0)=>site('mail',`postafiók<span>@netkapu</span>`,t('Levelek egy régi ismerőstől'),`<div class="retro-mail-layout"><aside><b>${esc(state.user)}</b><button data-mail-view="inbox">Beérkezett (${inbox.length})</button><button data-mail-view="draft">${esc(t('Piszkozatok'))}</button><p>${esc(t('25 MB tárhely'))}</p><div class="retro-mail-meter"><span></span></div><small>${esc(t('0,1 MB foglalt'))}</small></aside><main><p class="retro-disclaimer">${esc(t('Bemutatópostafiók. A piszkozatot a géped tárolja; levélküldés nincs.'))}</p>${mode==='draft'?`<form class="retro-compose" data-web-form="draft"><h2>${esc(t('Új levél – piszkozat'))}</h2><label>${esc(t('Címzett'))} <input name="to" maxlength="100" value="${esc(data().draft?.to||'')}"></label><label>${esc(t('Tárgy'))} <input name="subject" maxlength="120" value="${esc(data().draft?.subject||'')}"></label><label>${esc(t('Üzenet'))} <textarea name="body" maxlength="4000" rows="8">${esc(data().draft?.body||'')}</textarea></label><button class="xp-button">${esc(t('Piszkozat mentése'))}</button><span role="status" data-draft-status></span></form>`:`<h2>${esc(t('Beérkezett levelek'))}</h2><table><thead><tr><th>${esc(t('Feladó / Tárgy'))}</th><th>${esc(t('Dátum'))}</th></tr></thead><tbody>${inbox.map((m,i)=>`<tr class="${i===selected?'selected':''}"><td><button class="web-link" data-mail-id="${i}"><b>${m.from}</b><br>${m.subject}</button></td><td>${m.date}</td></tr>`).join('')}</tbody></table><article class="retro-letter"><h2>${inbox[selected].subject}</h2><small>Feladó: ${inbox[selected].from}</small><p>${inbox[selected].body}</p><button class="xp-button" data-mail-reply="${selected}">${esc(t('Válasz piszkozatban'))}</button></article>`}</main></div>`);
  add({id:'mail',title:t('Postafiók – Netkapu levelezés'),url:'mail.netkapu.hu',keywords:t('email mail levél levelezés freemail postafiók piszkozat'),description:t('Korabeli webmail három mintalevéllel és menthető piszkozattal.'),render:()=>mailBody(),handle(e,api){if(e.type==='click'){const b=e.target.closest('[data-mail-view],[data-mail-id],[data-mail-reply]');if(!b)return;if(b.hasAttribute('data-mail-reply')){const m=inbox[Number(b.dataset.mailReply)];saveDraft({to:m.from,subject:'Re: '+m.subject,body:''});}const html=mailBody(b.dataset.mailView==='draft'||b.hasAttribute('data-mail-reply')?'draft':'inbox',Number(b.dataset.mailId)||0);api.view.querySelector('.offline-page').innerHTML=html;}if(e.type==='submit'&&e.target.dataset.webForm==='draft'){saveDraft(Object.fromEntries(new FormData(e.target)));e.target.querySelector('[data-draft-status]').textContent=' Piszkozat elmentve.';}}});
  const cities=[{name:t('Budapest'),temp:24,sky:'Napos',wind:t('ÉNy, 12 km/h'),humidity:52},{name:t('Szeged'),temp:27,sky:t('Derült'),wind:'D, 8 km/h',humidity:45},{name:t('Debrecen'),temp:22,sky:t('Változóan felhős'),wind:t('É, 16 km/h'),humidity:61},{name:t('Pécs'),temp:25,sky:'Napos',wind:'Ny, 9 km/h',humidity:49}];
  const weatherBody=(i=0)=>{const c=cities[i];return site('weather',`időjárás<span>.net</span>`,t('Milyen idő lesz holnap?'),`<div class="retro-weather-date">${esc(t('2004. szeptember 1. · Szemléltető időjárási adatok'))}</div><div class="retro-weather-content"><label>${esc(t('Város:'))} <select data-weather-city aria-label="Időjárás: város">${cities.map((c,n)=>`<option value="${n}" ${i===n?'selected':''}>${c.name}</option>`).join('')}</select></label><section class="retro-weather-now"><div class="retro-weather-sun" aria-hidden="true">☀</div><div><h1>${c.name}</h1><strong>${c.temp} °C</strong><p>${c.sky}</p></div><dl><dt>${esc(t('Szél'))}</dt><dd>${c.wind}</dd><dt>${esc(t('Páratartalom'))}</dt><dd>${c.humidity}%</dd><dt>${esc(t('Napkelte / napnyugta'))}</dt><dd>06:03 / 19:25</dd></dl></section><h2>${esc(t('Ötnapos előrejelzés – bemutató'))}</h2><div class="retro-forecast">${[t('Csütörtök'),t('Péntek'),'Szombat',t('Vasárnap'),t('Hétfő')].map((day,n)=>`<div><b>${day}</b><span>${n===2?'☁':'☀'}</span><strong>${c.temp+[1,-1,-3,0,2][n]} °C</strong><small>${c.temp-10+n%3} °C</small><p>${n===2?t('Felhős'):'Napos'}</p></div>`).join('')}</div><p>Kirándulást tervezel? ${link('rail',t('Nézd meg a menetrendet!'))}</p></div>`);};
  add({id:'weather',title:t('Időjárás.net – Városi előrejelzés'),url:'www.idojaras.net',keywords:t('időjárás idő nap eső előrejelzés budapest szeged debrecen pécs'),description:t('Négy város bemutató-időjárása, hőmérséklettel és ötnapos táblázattal.'),render:()=>weatherBody(),handle(e,api){if(e.type==='change'&&e.target.matches('[data-weather-city]'))api.view.querySelector('.offline-page').innerHTML=weatherBody(Number(e.target.value));}});
  const routes=[['Szeged',t('Napfény IC'),'06:50','09:12'],['Szeged','Tisza IC','08:50','11:12'],['Debrecen',t('Hajdú IC'),'07:23','09:58'],['Debrecen',t('Cívis IC'),'09:23','11:58'],[t('Pécs'),'Mecsek IC','06:45','09:40'],[t('Pécs'),'Sopianae IC','08:45','11:40']];
  const railBody=(city='Szeged')=>site('rail','ELVIRA',t('Elektronikus vasúti információ'),`<div class="retro-rail-content"><h1>${esc(t('Belföldi menetrend'))}</h1><p class="retro-disclaimer">${esc(t('Bemutatómenetrend, kitalált járatokkal és időpontokkal. Utazástervezésre nem használható.'))}</p><form data-web-form="rail" class="retro-rail-form"><label>${esc(t('Honnan?'))} <input value="Budapest" readonly aria-label="Indulási állomás"></label><label>${esc(t('Hová?'))} <select name="city">${['Szeged','Debrecen',t('Pécs')].map(c=>`<option ${city===c?'selected':''}>${c}</option>`).join('')}</select></label><label>${esc(t('Mikor?'))} <input value="2004. 09. 04." readonly aria-label="Utazás napja"></label><button class="xp-button">${esc(t('Keresés'))}</button></form><h2>Budapest → ${city}</h2><table><thead><tr><th>${esc(t('Járat'))}</th><th>${esc(t('Indulás'))}</th><th>${esc(t('Érkezés'))}</th><th>${esc(t('Átszállás'))}</th></tr></thead><tbody>${routes.filter(r=>r[0]===city).map(r=>`<tr><td><b>${r[1]}</b></td><td>${r[2]}</td><td>${r[3]}</td><td>${esc(t('Közvetlen'))}</td></tr>`).join('')}</tbody></table>${card(t('A kellemes utazásért'),`<p>${esc(t('A vonatra felszállás előtt ellenőrizd a vágányszámot. Az ablak mellől egészen más arcát mutatja a táj.'))}</p>`)}<p>${link('weather',t('Időjárás a célállomáson'))} · ${link('wallpapers',t('Úti képeslapok'))}</p></div>`);
  add({id:'rail',title:t('ELVIRA – Belföldi bemutatómenetrend'),url:'www.elvira.hu',keywords:t('vonat vasút menetrend utazás kirándulás budapest szeged pécs debrecen'),description:t('Válassz célállomást, és keress járatot a nosztalgikus menetrendben. Kitalált bemutatóadatok.'),render:()=>railBody(),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='rail'){const city=new FormData(e.target).get('city');if(['Szeged','Debrecen',t('Pécs')].includes(city))api.view.querySelector('.offline-page').innerHTML=railBody(city);}}});
  update('wallpapers',{body:site('gallery',t('XP KÉPGALÉRIA'),t('Egy ablak a világra.'),`<div class="retro-gallery-intro"><h1>${esc(t('Vidd magaddal a tájat!'))}</h1><p>${esc(t('Az eredeti Windows XP hátterek 1920 × 1200 képpontos változatai.'))}</p></div><div class="retro-gallery">${[['bliss','Bliss',t('A zöld domb, amelyet mindenki ismer.')],['azul','Azul',t('Egy pálmafa. Egy sziget. Egy kis nyugalom.')],['autumn','Autumn',t('Aranyló levelek és egy csendes őszi ösvény.')]].map(([id,title,desc])=>`<figure><img src="${XP.wallpaperPath(id)}" alt="${title}"><figcaption><h2>${title}</h2><p>${desc}</p><button class="xp-button" data-wallpaper="${id}">${esc(t('Beállítás háttérként'))}</button></figcaption></figure>`).join('')}</div>`),handle(e){if(e.type!=='click')return;const id=e.target.closest('[data-wallpaper]')?.dataset.wallpaper;if(['bliss','azul','autumn'].includes(id)){state.wallpaper=id;XP.persist();XP.applySettings();XP.notify(t('Asztali háttér'),t('Az új háttérkép beállítva.'));}}});
  update('html',{body:site('school','HTML SULI',t('Az első honlapod itt kezdődik.'),`<div class="retro-school-content"><h1>${esc(t('Helló, világ!'))}</h1><p>${esc(t('A HTML adja az oldal szerkezetét, a CSS a színeit. Próbáld ki a kis honlapkészítőt!'))}</p><form data-web-form="homepage" class="retro-compose"><label>${esc(t('Az oldal címe'))} <input name="title" maxlength="80" value="Üdv a honlapomon!"></label><label>${esc(t('Bemutatkozás'))} <textarea name="body" maxlength="1000" rows="4">${esc(t('Szia! Ez az első honlapom. Szeretem a zenét, a játékokat és a számítógépeket.'))}</textarea></label><label>${esc(t('Háttérszín'))} <select name="color"><option value="cream">${esc(t('Vajszínű'))}</option><option value="blue">${esc(t('Világoskék'))}</option><option value="green">${esc(t('Világoszöld'))}</option></select></label><button class="xp-button">${esc(t('Előnézet'))}</button></form><section class="retro-home-preview" data-home-preview><h2>${esc(t('Üdv a honlapomon!'))}</h2><p>${esc(t('Itt jelenik meg az oldalad előnézete.'))}</p></section><h2>${esc(t('Mi van a háttérben?'))}</h2><pre data-home-code>${esc(t('&lt;h1&gt;Üdv a honlapomon!&lt;/h1&gt;'))}</pre><p>${esc(t('A szöveget a Jegyzettömbben is továbbírhatod.'))}</p><button class="xp-button" data-app="notepad">${esc(t('Jegyzettömb megnyitása'))}</button></div>`),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='homepage'){const f=new FormData(e.target),title=String(f.get('title')).slice(0,80),body=String(f.get('body')).slice(0,1000),preview=api.view.querySelector('[data-home-preview]');preview.style.backgroundColor=({cream:'#fffce6',blue:'#e4f0ff',green:'#eaf8e2'})[f.get('color')]||'#fffce6';preview.innerHTML=`<h2>${esc(title)}</h2><p>${esc(body)}</p>`;api.view.querySelector('[data-home-code]').textContent=`<h1>${esc(title)}</h1>\n<p>${esc(body)}</p>`;}}});
  update('music',{body:site('music',`ZENE<span>${esc(t('SZOBA'))}</span>`,t('A hangok hazatalálnak.'),`<div class="retro-music-hero">${icon('player')}<div><small>${esc(t('A HÉT ALBUMA'))}</small><h1>${esc(t('A Windows hangjai'))}</h1><p>${esc(t('Négy rövid dallam. Egy egész korszak.'))}</p><button class="xp-button" data-app="player">${esc(t('Lejátszó megnyitása'))}</button></div></div><div class="retro-music-content"><h2>${esc(t('Windows XP / Rendszerhangok'))}</h2><table><tr><th>#</th><th>${esc(t('Cím'))}</th><th>${esc(t('Előadó'))}</th></tr>${['Startup','Shutdown','Notify','Ding'].map((name,i)=>`<tr><td>0${i+1}</td><td>${name}</td><td>Microsoft Windows XP</td></tr>`).join('')}</table><h2>${esc(t('A zene veled jön'))}</h2><p>${esc(t('Nyiss meg saját MP3, WAV vagy OGG fájlokat a Windows Media Playerben. A médiatárban kereshetsz, a lejátszási listán sorrendet választhatsz, a vizualizáció pedig követi a dallamot.'))}</p><h2>${esc(t('Azok a régi CD-k'))}</h2><p>${esc(t('Kézzel felírt számlista, műanyag tok, kedvenc szám a hetedik helyen. Neked melyik lemez jut eszedbe?'))}</p>${link('forum',t('Meséld el a fórumban »'))}</div>`)});
  update('recipes',{body:site('recipe',t('Nagyi receptkönyve'),'Egy csipet szeretet.',`<div class="retro-recipe-content"><small>${esc(t('A CSALÁD KEDVENCEI / ÉDES TÉSZTÁK'))}</small><h1>${esc(t('Nagyi palacsintája'))}</h1><p class="retro-intro">${esc(t('Lekvárral, kakaóval vagy túróval. De leginkább együtt.'))}</p><label>${esc(t('Adag:'))} <select data-portions><option value="1">${esc(t('12 palacsinta'))}</option><option value="2">${esc(t('24 palacsinta'))}</option><option value="3">${esc(t('36 palacsinta'))}</option></select></label><div class="retro-recipe-columns"><section><h2>${esc(t('Hozzávalók'))}</h2><ul data-ingredients><li>20 dkg liszt</li><li>${esc(t('2 tojás'))}</li><li>${esc(t('3 dl tej'))}</li><li>${esc(t('2 dl szódavíz'))}</li></ul><p>${esc(t('Egy csipet só és kevés olaj.'))}</p></section><section><h2>${esc(t('Elkészítés'))}</h2><ol><li>${esc(t('Keverd simára a lisztet, a tojást és a tejet.'))}</li><li>${esc(t('Add hozzá a szódavizet és a sót. Pihentesd 20 percig.'))}</li><li>${esc(t('Forró, vékonyan olajozott serpenyőbe merj egy kevés tésztát.'))}</li><li>${esc(t('Süsd meg mindkét oldalát, majd töltsd meg a kedvenc töltelékeddel.'))}</li></ol></section></div><blockquote>${esc(t('Nagyi tippje: az első palacsinta a szakácsé!'))}</blockquote><p>${link('portal','Vissza a Netkapuhoz')}</p></div>`),handle(e,api){if(e.type==='change'&&e.target.matches('[data-portions]')){const n=Number(e.target.value);if([1,2,3].includes(n))api.view.querySelector('[data-ingredients]').innerHTML=`<li>${20*n} dkg liszt</li><li>${2*n} tojás</li><li>${3*n} dl tej</li><li>${2*n} dl szódavíz</li>`;}}});
  update('about',{render:()=>site('directory',t('Webkatalógus'),t('A helyi web összes oldala, egy helyen.'),`<div class="retro-directory"><h1>${esc(t('Merre induljunk?'))}</h1><p>${esc(t('{count} helyi oldal vár felfedezésre. A keresőben címre, témára és kulcsszóra is kereshetsz.',{count:pages.length}))}</p><div>${pages.filter(p=>p.id!=='about').map(p=>`<article><h2>${link(p.id,esc(p.title))}</h2><small>${esc(p.url)}</small><p>${esc(p.description)}</p></article>`).join('')}</div></div>`)});
})();
