'use strict';
(() => {
  const {esc,icon,state,webPages:pages,t,locale}=XP;
  const link=(id,label)=>`<button type="button" class="web-link" data-page="${id}">${label}</button>`;
  const money=n=>n.toLocaleString(locale())+' Ft';
  const data=()=>state.webDemo||(state.webDemo={cart:{},messages:[],draft:{},vote:''});
  const products=[
    {id:'pc',name:t("text_home_pc_2400"),price:129900,icon:'computer',spec:'2,4 GHz • 512 MB DDR • 80 GB HDD • Windows XP',tag:t("text_this_month_s_offer")},
    {id:'monitor',name:t("text_17_flat_crt_monitor"),price:39900,icon:'computer',spec:t("text_1280_1024_85_hz_silver_case"),tag:t("text_a_sharp_picture_and_plenty_of_room_to_work")},
    {id:'disc',name:t("text_cd_r_700_mb_pack_of_10"),price:1490,icon:'cd',spec:t("text_48_writable_80_minutes_spindle_pack"),tag:t("text_save_your_memories")},
    {id:'audio',name:t("text_a_pair_of_multimedia_speakers"),price:5990,icon:'volume',spec:t("text_2_0_stereo_3_5_mm_jack_volume_control"),tag:t("text_windows_sounds_better_too")}
  ];
  const cartItems=()=>products.map(p=>({...p,quantity:Math.max(0,Math.min(9,Number(data().cart?.[p.id])||0))})).filter(p=>p.quantity);
  const cartTotal=()=>cartItems().reduce((sum,p)=>sum+p.price*p.quantity,0);
  function changeCart(id,delta){if(!products.some(p=>p.id===id))return;const cart=data().cart||(data().cart={});cart[id]=Math.max(0,Math.min(9,(Number(cart[id])||0)+delta));XP.persist();}
  function postMessage(name,message){
    name=String(name).trim().slice(0,30);message=String(message).trim().slice(0,600);
    if(!name||!message)return false;
    data().messages=[{name,message,date:new Date().toLocaleDateString(locale())},...(data().messages||[])].slice(0,30);XP.persist();return true;
  }
  function saveDraft(draft){data().draft={to:String(draft.to||'').slice(0,100),subject:String(draft.subject||'').slice(0,120),body:String(draft.body||'').slice(0,4000)};XP.persist();}
  XP.webDemo={products,cartItems,cartTotal,changeCart,postMessage,saveDraft};
  function site(kind,title,tag,body){return `<div class="retro-site retro-${kind}"><header class="retro-masthead"><strong>${title}</strong><span>${tag}</span></header><nav class="retro-nav">${link('portal',t("text_home"))} | ${link('shop',t("text_computing"))} | ${link('forum',t("text_forum"))} | ${link('mail',t("text_mail"))} | ${link('about',t("text_web_directory"))}</nav>${body}<footer class="retro-footer">${esc(t("text_2004_the_web_of_the_early_2000s_local_demonstration"))}</footer></div>`;}
  function add(page){pages.push(page);}
  function update(id,props){Object.assign(pages.find(p=>p.id===id),props);}
  const card=(title,body)=>`<section class="retro-box"><h2>${title}</h2><div>${body}</div></section>`;
  add({id:'portal',title:t("text_netkapu_the_day_starts_here"),url:'www.netkapu.hu',keywords:t("text_portal_news_paper_weather_sport_computer_mail_forum"),description:t("text_news_useful_pages_weather_and_a_little_nostalgia_the_2004_demonstratio_2f58e630"),render:()=>site('portal','netkapu<span>.hu</span>',t("text_news_people_internet"),`
    <div class="retro-date">${esc(t("text_wednesday_1_september_2004_archive_demonstration_edition"))}</div>
    <div class="retro-columns"><aside>${card(t("text_navigator"),`<ul class="retro-links"><li>${link('weather',t("text_weather"))}</li><li>${link('rail','Menetrend')}</li><li>${link('mail',t("text_mail"))}</li><li>${link('games',t("text_games"))}</li><li>${link('recipes','Receptklub')}</li><li>${link('wallpapers',t("text_picture_gallery"))}</li></ul>`)}${card(t("text_poll"),`<p>${esc(t("text_how_do_you_spend_the_break"))}</p>${data().vote?`<p>${esc(t("text_thank_you_for_voting"))}</p>${[t("text_game"),t("text_my_music"),t("text_browse")].map((v,i)=>`<div class="retro-poll">${v} ${[46,32,22][i]}%<span style="width:${[46,32,22][i]}%"></span></div>`).join('')}<small>${esc(t("text_sample_results_you_chose_choice",{choice:data().vote}))}</small>`:`<form data-web-form="vote">${[t("text_game"),t("text_my_music"),t("text_browse")].map(v=>`<label class="retro-radio"><input type="radio" name="vote" value="${v}" required> ${v}</label>`).join('')}<button class="xp-button">${esc(t("text_vote"))}</button></form>`}`)}</aside>
    <main><article class="retro-lead"><img src="assets/wallpapers/bliss-hd.jpg" alt="${esc(t("text_a_green_hill_under_a_blue_sky"))}"><small>${esc(t("text_technology"))}</small><h1>${link('magazine',t("text_a_new_era_for_the_home_computer"))}</h1><p>${esc(t("text_a_cd_writer_digital_photographs_and_a_first_web_page_of_one_s_own_all_0653cb21"))}</p><p>${link('magazine',t("text_read_the_whole_article"))}</p></article>${card('Friss a Netkapun',`<h3>${link('rail',t("text_where_shall_we_go_at_the_weekend"))}</h3><p>${esc(t("text_take_a_trip_by_train_have_a_look_at_the_demonstration_timetable"))}</p><h3>${link('html',t("text_build_your_first_web_page"))}</h3><p>${esc(t("text_a_few_lines_of_text_already_make_a_personal_page"))}</p><h3>${link('space',t("text_a_journey_through_the_solar_system"))}</h3><p>${esc(t("text_from_the_red_planet_to_the_rings_of_saturn"))}</p>`)}</main>
    <aside>${card(t("text_today_s_pick"),`${icon('player')}<h3>${esc(t("text_music_one_click_away"))}</h3><p>${esc(t("text_the_familiar_tunes_of_windows_in_the_zeneszoba"))}</p>${link('music',t("text_sign_in"))}`)}${card(t("text_community"),`<p>${esc(t("text_what_was_your_first_computer"))}</p>${link('forum',t("text_tell_us_on_the_forum"))}`)}<div class="retro-ad">512 MB RAM<br><b>${esc(t("text_room_enough_for_your_ideas"))}</b><br>${link('shop',t("text_pc_bazar_027ca8f1"))}</div></aside></div>`),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='vote'){const value=new FormData(e.target).get('vote');if([t("text_game"),t("text_my_music"),t("text_browse")].includes(value)){data().vote=value;XP.persist();api.refresh();}}}});
  add({id:'magazine',title:t("text_pc_magazine_a_new_era_for_the_home_computer"),url:'www.pc-magazin.hu/otthoni-pc',keywords:t("text_magazine_article_computer_pc_cd_writer_digital_photo_technology"),description:t("text_the_adventures_of_a_home_pc_photographs_music_games_and_a_web_page_of_6d4d1524"),body:site('magazine','PC MAGAZIN',t("text_a_computer_is_a_personal_matter"),`<div class="retro-article"><p class="retro-kicker">${esc(t("text_machines_and_people_september_2004"))}</p><h1>${esc(t("text_the_home_computer"))}<br>${esc(t("text_a_new_era"))}</h1><p class="retro-intro">${esc(t("text_a_grey_box_under_the_desk_inside_the_holiday_pictures_your_favourite_m_9842ae63"))}</p><img class="retro-article-photo" src="assets/wallpapers/azul-1920.jpg" alt="${esc(t("text_azul_a_beach_and_a_palm_tree"))}"><h2>${esc(t("text_memories_have_a_folder_of_their_own_now"))}</h2><p>${esc(t("text_photographs_come_off_the_camera_into_my_pictures_the_best_one_becomes_7df682a7"))}</p><p>${link('wallpapers',t("text_choose_a_new_wallpaper"))}</p><h2>${esc(t("text_just_one_more_round"))}</h2><p>${esc(t("text_homework_done_notepad_closed_a_free_quarter_of_an_hour_is_just_enough_8016da3f"))}</p><p>${link('games',t("text_from_the_games_section"))}</p><h2>${esc(t("text_a_place_of_your_own_on_the_web"))}</h2><p>${esc(t("text_choose_a_background_colour_write_a_few_lines_about_yourself_and_add_a_54c03ba3"))}</p><p>${link('html',t("text_try_the_page_builder"))}</p><hr><p>${link('forum',t("text_join_in_on_the_forum"))} · ${link('portal',t("text_back_to_netkapu"))}</p></div>`)});
  add({id:'shop',title:t("text_pc_bazar_computer_shop"),url:'www.pcbazar.hu',keywords:t("text_shop_shopping_store_computer_monitor_cd_hardware_memory_basket"),description:t("text_computers_monitors_and_accessories_of_the_day_a_working_basket_with_sa_657cf2d3"),render:()=>site('shop',t("text_pc_bazar_448e9143"),t("text_computing_at_a_price_that_works"),`
    <div class="retro-shop-banner">${esc(t("text_september_offers"))} <span>${esc(t("text_new_school_year_new_computer"))}</span></div><p class="retro-disclaimer">${esc(t("text_a_demonstration_shop_with_sample_products_of_the_day_the_basket_is_kep_1b74d16d"))}</p><div class="retro-products">${products.map(p=>`<article>${icon(p.icon)}<small>${p.tag}</small><h2>${p.name}</h2><p>${p.spec}</p><strong>${money(p.price)}</strong><button class="xp-button" data-cart-add="${p.id}">${esc(t("text_add_to_basket"))}</button></article>`).join('')}</div>
    <section class="retro-cart"><h2>${esc(t("text_your_basket"))}</h2>${cartItems().length?`<table><thead><tr><th>${esc(t("text_product"))}</th><th>${esc(t("text_qty"))}</th><th>${esc(t("text_total"))}</th></tr></thead><tbody>${cartItems().map(p=>`<tr><td>${p.name}</td><td><button class="xp-button" data-cart-remove="${p.id}" aria-label="${esc(t("text_name_fewer",{name:p.name}))}">−</button> ${p.quantity} <button class="xp-button" data-cart-add="${p.id}" aria-label="${esc(t("text_name_more",{name:p.name}))}" ${p.quantity===9?'disabled':''}>+</button></td><td>${money(p.quantity*p.price)}</td></tr>`).join('')}</tbody></table><p class="retro-total">${esc(t("text_total_45b3f942"))} <b>${money(cartTotal())}</b></p>`:`<p>${esc(t("text_the_basket_is_still_empty_have_a_look_at_our_offers"))}</p>`}</section>`),handle(e,api){if(e.type!=='click')return;const b=e.target.closest('[data-cart-add],[data-cart-remove]');if(b){changeCart(b.dataset.cartAdd||b.dataset.cartRemove,b.hasAttribute('data-cart-add')?1:-1);api.refresh();}}});
  const seedMessages=[{name:t("text_modemmaster"),date:'2004. 09. 01.',message:t("text_hi_all_mine_was_a_pentium_ii_i_still_recognise_the_start_up_sound_today")},{name:t("text_geek_84"),date:'2004. 09. 01.',message:t("text_3d_pinball_never_gets_old_watch_the_missions_do_not_just_hammer_the_flippers")}];
  add({id:'forum',title:t("text_netklub_forum_my_first_computer"),url:'www.netklub.hu/forum',keywords:t("text_forum_community_post_guestbook_first_computer_conversation"),description:t("text_a_retro_forum_with_posts_from_its_users_write_a_memory_into_the_guestb_17b6a0df"),render:()=>site('forum',t("text_netklub_forum_f2aa33e5"),t("text_everybody_has_a_good_story"),`<div class="retro-forum-path">${esc(t("text_forums_computing_my_first_computer"))}</div><h1 class="retro-page-title">${esc(t("text_my_first_computer"))}</h1><p class="retro-disclaimer">${esc(t("text_a_local_guestbook_only_this_browser_keeps_what_you_write"))}</p>${[...(data().messages||[]),...seedMessages].map(m=>`<article class="retro-post"><aside>${icon('user')}<b>${esc(m.name)}</b><small>${esc(t("text_club_member"))}</small></aside><div><header>${esc(m.date)}</header><p>${esc(m.message)}</p></div></article>`).join('')}<form class="retro-compose" data-web-form="guestbook"><h2>${esc(t("text_new_post"))}</h2><label>${esc(t("text_nickname"))} <input name="name" required maxlength="30" value="${esc(state.user)}"></label><label>${esc(t("text_message"))} <textarea name="message" required maxlength="600" rows="4"></textarea></label><button class="xp-button">${esc(t("text_save_post"))}</button><small>${esc(t("text_at_most_30_of_your_own_posts_are_kept"))}</small></form>`),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='guestbook'){const fields=new FormData(e.target);if(postMessage(fields.get('name'),fields.get('message')))api.refresh();}}});
  const inbox=[{from:'Netkapu csapata',subject:t("text_welcome_to_your_mailbox"),date:'szept. 1.',body:t("text_hi_this_is_your_own_little_mailbox_open_the_messages_on_the_left_and_o_aa0f0969")}, {from:'Peti',subject:t("text_pinball_this_afternoon"),date:'aug. 31.',body:t("text_hi_i_have_a_new_space_cadet_record_open_the_games_folder_and_try_to_be_f455403a")}, {from:t("text_photo_club"),subject:t("text_a_postcard_from_summer"),date:'aug. 30.',body:t("text_dear_member_the_summer_pictures_are_in_the_gallery_azul_the_one_by_the_80812809")}];
  const mailBody=(mode='inbox',selected=0)=>site('mail',`${esc(t("text_mailbox"))}<span>@netkapu</span>`,t("text_letters_from_an_old_acquaintance"),`<div class="retro-mail-layout"><aside><b>${esc(state.user)}</b><button data-mail-view="inbox">${esc(t("text_inbox_count",{count:inbox.length}))}</button><button data-mail-view="draft">${esc(t("text_drafts"))}</button><p>${esc(t("text_25_mb_of_space"))}</p><div class="retro-mail-meter"><span></span></div><small>${esc(t("text_0_1_mb_used"))}</small></aside><main><p class="retro-disclaimer">${esc(t("text_a_demonstration_mailbox_your_machine_keeps_the_draft_nothing_is_actually_sent"))}</p>${mode==='draft'?`<form class="retro-compose" data-web-form="draft"><h2>${esc(t("text_new_message_draft"))}</h2><label>${esc(t("text_to_96c8a4be"))} <input name="to" maxlength="100" value="${esc(data().draft?.to||'')}"></label><label>${esc(t("text_subject"))} <input name="subject" maxlength="120" value="${esc(data().draft?.subject||'')}"></label><label>${esc(t("text_message"))} <textarea name="body" maxlength="4000" rows="8">${esc(data().draft?.body||'')}</textarea></label><button class="xp-button">${esc(t("text_save_draft"))}</button><span role="status" data-draft-status></span></form>`:`<h2>${esc(t("text_inbox_340d79a8"))}</h2><table><thead><tr><th>${esc(t("text_from_subject"))}</th><th>${esc(t("text_date"))}</th></tr></thead><tbody>${inbox.map((m,i)=>`<tr class="${i===selected?'selected':''}"><td><button class="web-link" data-mail-id="${i}"><b>${m.from}</b><br>${m.subject}</button></td><td>${m.date}</td></tr>`).join('')}</tbody></table><article class="retro-letter"><h2>${inbox[selected].subject}</h2><small>${esc(t("text_from_name",{name:inbox[selected].from}))}</small><p>${inbox[selected].body}</p><button class="xp-button" data-mail-reply="${selected}">${esc(t("text_reply_in_a_draft"))}</button></article>`}</main></div>`);
  add({id:'mail',title:t("text_mailbox_netkapu_mail"),url:'mail.netkapu.hu',keywords:t("text_email_mail_message_webmail_mailbox_draft"),description:t("text_webmail_of_the_day_with_three_sample_messages_and_a_draft_you_can_save"),render:()=>mailBody(),handle(e,api){if(e.type==='click'){const b=e.target.closest('[data-mail-view],[data-mail-id],[data-mail-reply]');if(!b)return;if(b.hasAttribute('data-mail-reply')){const m=inbox[Number(b.dataset.mailReply)];saveDraft({to:m.from,subject:'Re: '+m.subject,body:''});}const html=mailBody(b.dataset.mailView==='draft'||b.hasAttribute('data-mail-reply')?'draft':'inbox',Number(b.dataset.mailId)||0);api.view.querySelector('.offline-page').innerHTML=html;}if(e.type==='submit'&&e.target.dataset.webForm==='draft'){saveDraft(Object.fromEntries(new FormData(e.target)));e.target.querySelector('[data-draft-status]').textContent=' Piszkozat elmentve.';}}});
  const cities=[{name:t("text_budapest"),temp:24,sky:'Napos',wind:t("text_nw_12_km_h"),humidity:52},{name:t("text_szeged"),temp:27,sky:t("text_clear"),wind:'D, 8 km/h',humidity:45},{name:t("text_debrecen"),temp:22,sky:t("text_partly_cloudy"),wind:t("text_n_16_km_h"),humidity:61},{name:t("text_pecs"),temp:25,sky:'Napos',wind:'Ny, 9 km/h',humidity:49}];
  const weatherBody=(i=0)=>{const c=cities[i];return site('weather',`${esc(t("text_weather_ed8c27d4"))}<span>.net</span>`,t("text_what_will_the_weather_be_tomorrow"),`<div class="retro-weather-date">${esc(t("text_1_september_2004_illustrative_weather_data"))}</div><div class="retro-weather-content"><label>${esc(t("text_city"))} <select data-weather-city aria-label="${esc(t("text_weather_town"))}">${cities.map((c,n)=>`<option value="${n}" ${i===n?'selected':''}>${c.name}</option>`).join('')}</select></label><section class="retro-weather-now"><div class="retro-weather-sun" aria-hidden="true">☀</div><div><h1>${c.name}</h1><strong>${c.temp} °C</strong><p>${c.sky}</p></div><dl><dt>${esc(t("text_wind"))}</dt><dd>${c.wind}</dd><dt>${esc(t("text_humidity"))}</dt><dd>${c.humidity}%</dd><dt>${esc(t("text_sunrise_sunset"))}</dt><dd>06:03 / 19:25</dd></dl></section><h2>${esc(t("text_five_day_forecast_demonstration"))}</h2><div class="retro-forecast">${[t("text_thursday"),t("text_friday"),'Szombat',t("text_sunday"),t("text_monday")].map((day,n)=>`<div><b>${day}</b><span>${n===2?'☁':'☀'}</span><strong>${c.temp+[1,-1,-3,0,2][n]} °C</strong><small>${c.temp-10+n%3} °C</small><p>${n===2?t("text_cloudy"):'Napos'}</p></div>`).join('')}</div><p>${esc(t("text_planning_a_trip"))} ${link('rail',t("text_look_at_the_timetable"))}</p></div>`);};
  add({id:'weather',title:t("text_weather_net_city_forecast"),url:'www.idojaras.net',keywords:t("text_weather_sun_rain_forecast_budapest_szeged_debrecen_pecs"),description:t("text_demonstration_weather_for_four_cities_with_temperatures_and_a_five_day_table"),render:()=>weatherBody(),handle(e,api){if(e.type==='change'&&e.target.matches('[data-weather-city]'))api.view.querySelector('.offline-page').innerHTML=weatherBody(Number(e.target.value));}});
  const routes=[['Szeged',t("text_napfeny_ic"),'06:50','09:12'],['Szeged','Tisza IC','08:50','11:12'],['Debrecen',t("text_hajdu_ic"),'07:23','09:58'],['Debrecen',t("text_civis_ic"),'09:23','11:58'],[t("text_pecs"),'Mecsek IC','06:45','09:40'],[t("text_pecs"),'Sopianae IC','08:45','11:40']];
  const railBody=(city='Szeged')=>site('rail','ELVIRA',t("text_electronic_railway_information"),`<div class="retro-rail-content"><h1>${esc(t("text_domestic_timetable"))}</h1><p class="retro-disclaimer">${esc(t("text_a_demonstration_timetable_with_invented_services_and_times_not_for_pla_5d80e71d"))}</p><form data-web-form="rail" class="retro-rail-form"><label>${esc(t("text_from_a69a93d3"))} <input value="Budapest" readonly aria-label="${esc(t("text_departure_station"))}"></label><label>${esc(t("text_to_f0c31a44"))} <select name="city">${['Szeged','Debrecen',t("text_pecs")].map(c=>`<option ${city===c?'selected':''}>${c}</option>`).join('')}</select></label><label>${esc(t("text_when"))} <input value="2004. 09. 04." readonly aria-label="${esc(t("text_day_of_travel"))}"></label><button class="xp-button">${esc(t("text_search"))}</button></form><h2>Budapest → ${city}</h2><table><thead><tr><th>${esc(t("text_service"))}</th><th>${esc(t("text_departure"))}</th><th>${esc(t("text_arrival"))}</th><th>${esc(t("text_change"))}</th></tr></thead><tbody>${routes.filter(r=>r[0]===city).map(r=>`<tr><td><b>${r[1]}</b></td><td>${r[2]}</td><td>${r[3]}</td><td>${esc(t("text_direct"))}</td></tr>`).join('')}</tbody></table>${card(t("text_for_a_pleasant_journey"),`<p>${esc(t("text_check_the_platform_number_before_you_board_from_the_window_seat_the_la_fd22bf8f"))}</p>`)}<p>${link('weather',t("text_weather_at_the_destination"))} · ${link('wallpapers',t("text_postcards_from_the_road"))}</p></div>`);
  add({id:'rail',title:t("text_elvira_domestic_demonstration_timetable"),url:'www.elvira.hu',keywords:t("text_train_railway_timetable_travel_trip_budapest_szeged_pecs_debrecen"),description:t("text_pick_a_destination_and_look_for_a_service_in_the_nostalgic_timetable_t_ec0e6825"),render:()=>railBody(),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='rail'){const city=new FormData(e.target).get('city');if(['Szeged','Debrecen',t("text_pecs")].includes(city))api.view.querySelector('.offline-page').innerHTML=railBody(city);}}});
  update('wallpapers',{body:site('gallery',t("text_xp_picture_gallery"),t("text_a_window_on_the_world_cd2c1201"),`<div class="retro-gallery-intro"><h1>${esc(t("text_take_the_landscape_with_you"))}</h1><p>${esc(t("text_the_original_windows_xp_wallpapers_at_1920_1200"))}</p></div><div class="retro-gallery">${[['bliss','Bliss',t("text_the_green_hill_everybody_knows")],['azul','Azul',t("text_a_palm_tree_an_island_a_little_peace")],['autumn','Autumn',t("text_golden_leaves_and_a_quiet_autumn_path")]].map(([id,title,desc])=>`<figure><img src="${XP.wallpaperPath(id)}" alt="${title}"><figcaption><h2>${title}</h2><p>${desc}</p><button class="xp-button" data-wallpaper="${id}">${esc(t("text_set_as_wallpaper"))}</button></figcaption></figure>`).join('')}</div>`),handle(e){if(e.type!=='click')return;const id=e.target.closest('[data-wallpaper]')?.dataset.wallpaper;if(['bliss','azul','autumn'].includes(id)){state.wallpaper=id;XP.persist();XP.applySettings();XP.notify(t("text_desktop_wallpaper"),t("text_the_new_wallpaper_is_set"));}}});
  update('html',{body:site('school','HTML SULI',t("text_your_first_web_page_starts_here"),`<div class="retro-school-content"><h1>${esc(t("text_hello_world"))}</h1><p>${esc(t("text_html_gives_the_page_its_structure_and_css_its_colours_try_the_little_p_1cd828da"))}</p><form data-web-form="homepage" class="retro-compose"><label>${esc(t("text_page_title"))} <input name="title" maxlength="80" value="Üdv a honlapomon!"></label><label>${esc(t("text_about_me"))} <textarea name="body" maxlength="1000" rows="4">${esc(t("text_hi_this_is_my_first_web_page_i_like_music_games_and_computers"))}</textarea></label><label>${esc(t("text_background_colour"))} <select name="color"><option value="cream">${esc(t("text_cream"))}</option><option value="blue">${esc(t("text_light_blue"))}</option><option value="green">${esc(t("text_light_green"))}</option></select></label><button class="xp-button">${esc(t("text_preview"))}</button></form><section class="retro-home-preview" data-home-preview><h2>${esc(t("text_welcome_to_my_page"))}</h2><p>${esc(t("text_the_preview_of_your_page_appears_here"))}</p></section><h2>${esc(t("text_what_is_in_the_background"))}</h2><pre data-home-code>${esc(t("text_and_lt_h1_and_gt_welcome_to_my_page_and_lt_h1_and_gt"))}</pre><p>${esc(t("text_you_can_carry_on_writing_the_text_in_notepad"))}</p><button class="xp-button" data-app="notepad">${esc(t("text_open_notepad"))}</button></div>`),handle(e,api){if(e.type==='submit'&&e.target.dataset.webForm==='homepage'){const f=new FormData(e.target),title=String(f.get('title')).slice(0,80),body=String(f.get('body')).slice(0,1000),preview=api.view.querySelector('[data-home-preview]');preview.style.backgroundColor=({cream:'#fffce6',blue:'#e4f0ff',green:'#eaf8e2'})[f.get('color')]||'#fffce6';preview.innerHTML=`<h2>${esc(title)}</h2><p>${esc(body)}</p>`;api.view.querySelector('[data-home-code]').textContent=`<h1>${esc(title)}</h1>\n<p>${esc(body)}</p>`;}}});
  update('music',{body:site('music',`ZENE<span>${esc(t("text_room"))}</span>`,t("text_the_sounds_find_their_way_home"),`<div class="retro-music-hero">${icon('player')}<div><small>${esc(t("text_album_of_the_week"))}</small><h1>${esc(t("text_the_sounds_of_windows"))}</h1><p>${esc(t("text_four_short_tunes_a_whole_era"))}</p><button class="xp-button" data-app="player">${esc(t("text_open_the_player"))}</button></div></div><div class="retro-music-content"><h2>${esc(t("text_windows_xp_system_sounds"))}</h2><table><tr><th>#</th><th>${esc(t("text_address"))}</th><th>${esc(t("text_artist"))}</th></tr>${['Startup','Shutdown','Notify','Ding'].map((name,i)=>`<tr><td>0${i+1}</td><td>${name}</td><td>Microsoft Windows XP</td></tr>`).join('')}</table><h2>${esc(t("text_the_music_comes_with_you"))}</h2><p>${esc(t("text_open_your_own_mp3_wav_or_ogg_files_in_windows_media_player_the_library_b8510f0b"))}</p><h2>${esc(t("text_those_old_cds"))}</h2><p>${esc(t("text_a_track_list_written_by_hand_a_plastic_case_the_favourite_song_in_seve_0d7e2333"))}</p>${link('forum',t("text_tell_the_story_on_the_forum"))}</div>`)});
  update('recipes',{body:site('recipe',t("text_grandma_s_recipe_book"),'Egy csipet szeretet.',`<div class="retro-recipe-content"><small>${esc(t("text_family_favourites_sweet_batters"))}</small><h1>${esc(t("text_grandma_s_pancakes"))}</h1><p class="retro-intro">${esc(t("text_with_jam_cocoa_or_curd_cheese_but_best_of_all_together"))}</p><label>${esc(t("text_servings"))} <select data-portions><option value="1">${esc(t("text_12_pancakes"))}</option><option value="2">${esc(t("text_24_pancakes"))}</option><option value="3">${esc(t("text_36_pancakes"))}</option></select></label><div class="retro-recipe-columns"><section><h2>${esc(t("text_ingredients"))}</h2><ul data-ingredients><li>20 dkg liszt</li><li>${esc(t("text_2_eggs"))}</li><li>${esc(t("text_300_ml_milk"))}</li><li>${esc(t("text_200_ml_sparkling_water"))}</li></ul><p>${esc(t("text_a_pinch_of_salt_and_a_little_oil_081142f6"))}</p></section><section><h2>${esc(t("text_method"))}</h2><ol><li>${esc(t("text_whisk_the_flour_the_eggs_and_the_milk_smooth"))}</li><li>${esc(t("text_add_the_sparkling_water_and_the_salt_let_it_rest_for_20_minutes"))}</li><li>${esc(t("text_ladle_a_little_batter_into_a_hot_lightly_oiled_pan"))}</li><li>${esc(t("text_fry_it_on_both_sides_then_fill_it_with_whatever_you_like_best"))}</li></ol></section></div><blockquote>${esc(t("text_grandma_s_tip_the_first_pancake_belongs_to_the_cook"))}</blockquote><p>${link('portal',t("text_back_to_netkapu"))}</p></div>`),handle(e,api){if(e.type==='change'&&e.target.matches('[data-portions]')){const n=Number(e.target.value);if([1,2,3].includes(n))api.view.querySelector('[data-ingredients]').innerHTML=`<li>${esc(t("text_n_g_flour",{n:20*n}))}</li><li>${esc(t("text_n_eggs",{n:2*n}))}</li><li>${esc(t("text_n_ml_milk",{n:3*n}))}</li><li>${esc(t("text_n_ml_soda_water",{n:2*n}))}</li>`;}}});
  update('about',{render:()=>site('directory',t("text_web_directory"),t("text_every_page_of_the_local_web_in_one_place"),`<div class="retro-directory"><h1>${esc(t("text_which_way_shall_we_go"))}</h1><p>${esc(t("text_count_local_pages_are_waiting_to_be_explored_the_search_looks_at_title_c60c529e",{count:pages.length}))}</p><div>${pages.filter(p=>p.id!=='about').map(p=>`<article><h2>${link(p.id,esc(p.title))}</h2><small>${esc(p.url)}</small><p>${esc(p.description)}</p></article>`).join('')}</div></div>`)});
})();
